/* async.c generated by valac 0.30.0, the Vala compiler
 * generated from async.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <libvaladate.h>
#include <gio/gio.h>


#define TEST_TYPE_ASYNC_TEST (test_async_test_get_type ())
#define TEST_ASYNC_TEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TEST_TYPE_ASYNC_TEST, TestAsyncTest))
#define TEST_ASYNC_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TEST_TYPE_ASYNC_TEST, TestAsyncTestClass))
#define TEST_IS_ASYNC_TEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TEST_TYPE_ASYNC_TEST))
#define TEST_IS_ASYNC_TEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TEST_TYPE_ASYNC_TEST))
#define TEST_ASYNC_TEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TEST_TYPE_ASYNC_TEST, TestAsyncTestClass))

typedef struct _TestAsyncTest TestAsyncTest;
typedef struct _TestAsyncTestClass TestAsyncTestClass;
typedef struct _TestAsyncTestPrivate TestAsyncTestPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _TestAsyncTestTestNoncancellableData TestAsyncTestTestNoncancellableData;
typedef struct _Block1Data Block1Data;
typedef struct _TestAsyncTestTestCancellableData TestAsyncTestTestCancellableData;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _TestAsyncTest {
	GObject parent_instance;
	TestAsyncTestPrivate * priv;
};

struct _TestAsyncTestClass {
	GObjectClass parent_class;
};

struct _TestAsyncTestTestNoncancellableData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	TestAsyncTest* self;
};

struct _Block1Data {
	int _ref_count_;
	TestAsyncTest* self;
	GSourceFunc acb;
	gpointer acb_target;
	GDestroyNotify acb_target_destroy_notify;
	gpointer _async_data_;
};

struct _TestAsyncTestTestCancellableData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	TestAsyncTest* self;
	GCancellable* cancel;
	Block1Data* _data1_;
	GCancellable* _tmp0_;
};


static gpointer test_async_test_parent_class = NULL;
static ValadateFixtureIface* test_async_test_valadate_fixture_parent_iface = NULL;

GType test_async_test_get_type (void) G_GNUC_CONST;
enum  {
	TEST_ASYNC_TEST_DUMMY_PROPERTY
};
static void test_async_test_real_set_up (ValadateFixture* base);
static void test_async_test_test_noncancellable_data_free (gpointer _data);
void test_async_test_test_noncancellable (TestAsyncTest* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void test_async_test_test_noncancellable_finish (TestAsyncTest* self, GAsyncResult* _res_);
static gboolean test_async_test_test_noncancellable_co (TestAsyncTestTestNoncancellableData* _data_);
static gboolean _test_async_test_test_noncancellable_co_gsource_func (gpointer self);
static void test_async_test_test_cancellable_data_free (gpointer _data);
void test_async_test_test_cancellable (TestAsyncTest* self, GCancellable* cancel, GAsyncReadyCallback _callback_, gpointer _user_data_);
void test_async_test_test_cancellable_finish (TestAsyncTest* self, GAsyncResult* _res_);
static gboolean test_async_test_test_cancellable_co (TestAsyncTestTestCancellableData* _data_);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gboolean _test_async_test_test_cancellable_co_gsource_func (gpointer self);
static void __lambda4_ (Block1Data* _data1_, GCancellable* o);
static void ___lambda4__g_cancellable_cancelled (GCancellable* _sender, gpointer self);
TestAsyncTest* test_async_test_new (void);
TestAsyncTest* test_async_test_construct (GType object_type);


static void test_async_test_real_set_up (ValadateFixture* base) {
	TestAsyncTest * self;
	self = (TestAsyncTest*) base;
	valadate_fixture_set_timeout ((ValadateFixture*) self, 1000);
}


static void test_async_test_test_noncancellable_data_free (gpointer _data) {
	TestAsyncTestTestNoncancellableData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (TestAsyncTestTestNoncancellableData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void test_async_test_test_noncancellable (TestAsyncTest* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	TestAsyncTestTestNoncancellableData* _data_;
	TestAsyncTest* _tmp0_ = NULL;
	_data_ = g_slice_new0 (TestAsyncTestTestNoncancellableData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, test_async_test_test_noncancellable);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, test_async_test_test_noncancellable_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	test_async_test_test_noncancellable_co (_data_);
}


void test_async_test_test_noncancellable_finish (TestAsyncTest* self, GAsyncResult* _res_) {
	TestAsyncTestTestNoncancellableData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean _test_async_test_test_noncancellable_co_gsource_func (gpointer self) {
	gboolean result;
	result = test_async_test_test_noncancellable_co (self);
	return result;
}


static gboolean test_async_test_test_noncancellable_co (TestAsyncTestTestNoncancellableData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 100, _test_async_test_test_noncancellable_co_gsource_func, _data_, NULL);
	_data_->_state_ = 1;
	return FALSE;
	_state_1:
	;
	_vala_assert (1 == 1, "1 == 1");
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void test_async_test_test_cancellable_data_free (gpointer _data) {
	TestAsyncTestTestCancellableData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->cancel);
	_g_object_unref0 (_data_->self);
	g_slice_free (TestAsyncTestTestCancellableData, _data_);
}


void test_async_test_test_cancellable (TestAsyncTest* self, GCancellable* cancel, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	TestAsyncTestTestCancellableData* _data_;
	TestAsyncTest* _tmp0_ = NULL;
	GCancellable* _tmp1_ = NULL;
	GCancellable* _tmp2_ = NULL;
	_data_ = g_slice_new0 (TestAsyncTestTestCancellableData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, test_async_test_test_cancellable);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, test_async_test_test_cancellable_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = cancel;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	_g_object_unref0 (_data_->cancel);
	_data_->cancel = _tmp2_;
	test_async_test_test_cancellable_co (_data_);
}


void test_async_test_test_cancellable_finish (TestAsyncTest* self, GAsyncResult* _res_) {
	TestAsyncTestTestCancellableData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		TestAsyncTest* self;
		self = _data1_->self;
		(_data1_->acb_target_destroy_notify == NULL) ? NULL : (_data1_->acb_target_destroy_notify (_data1_->acb_target), NULL);
		_data1_->acb = NULL;
		_data1_->acb_target = NULL;
		_data1_->acb_target_destroy_notify = NULL;
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static gboolean _test_async_test_test_cancellable_co_gsource_func (gpointer self) {
	gboolean result;
	result = test_async_test_test_cancellable_co (self);
	return result;
}


static void __lambda4_ (Block1Data* _data1_, GCancellable* o) {
	TestAsyncTest* self;
	self = _data1_->self;
	g_return_if_fail (o != NULL);
	_data1_->acb (_data1_->acb_target);
}


static void ___lambda4__g_cancellable_cancelled (GCancellable* _sender, gpointer self) {
	__lambda4_ (self, _sender);
}


static gboolean test_async_test_test_cancellable_co (TestAsyncTestTestCancellableData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_data1_ = g_slice_new0 (Block1Data);
	_data_->_data1_->_ref_count_ = 1;
	_data_->_data1_->self = g_object_ref (_data_->self);
	_data_->_data1_->_async_data_ = _data_;
	_data_->_data1_->acb = _test_async_test_test_cancellable_co_gsource_func;
	_data_->_data1_->acb_target = _data_;
	_data_->_data1_->acb_target_destroy_notify = NULL;
	_data_->_tmp0_ = NULL;
	_data_->_tmp0_ = _data_->cancel;
	g_signal_connect_data (_data_->_tmp0_, "cancelled", (GCallback) ___lambda4__g_cancellable_cancelled, block1_data_ref (_data_->_data1_), (GClosureNotify) block1_data_unref, 0);
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 100, _test_async_test_test_cancellable_co_gsource_func, _data_, NULL);
	_data_->_state_ = 1;
	return FALSE;
	_state_1:
	;
	_vala_assert (1 == 1, "1 == 1");
	block1_data_unref (_data_->_data1_);
	_data_->_data1_ = NULL;
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


TestAsyncTest* test_async_test_construct (GType object_type) {
	TestAsyncTest * self = NULL;
	self = (TestAsyncTest*) g_object_new (object_type, NULL);
	return self;
}


TestAsyncTest* test_async_test_new (void) {
	return test_async_test_construct (TEST_TYPE_ASYNC_TEST);
}


static void test_async_test_class_init (TestAsyncTestClass * klass) {
	test_async_test_parent_class = g_type_class_peek_parent (klass);
}


static void test_async_test_valadate_fixture_interface_init (ValadateFixtureIface * iface) {
	test_async_test_valadate_fixture_parent_iface = g_type_interface_peek_parent (iface);
	iface->set_up = (void (*)(ValadateFixture*)) test_async_test_real_set_up;
}


static void test_async_test_instance_init (TestAsyncTest * self) {
}


GType test_async_test_get_type (void) {
	static volatile gsize test_async_test_type_id__volatile = 0;
	if (g_once_init_enter (&test_async_test_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TestAsyncTestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) test_async_test_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TestAsyncTest), 0, (GInstanceInitFunc) test_async_test_instance_init, NULL };
		static const GInterfaceInfo valadate_fixture_info = { (GInterfaceInitFunc) test_async_test_valadate_fixture_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType test_async_test_type_id;
		test_async_test_type_id = g_type_register_static (G_TYPE_OBJECT, "TestAsyncTest", &g_define_type_info, 0);
		g_type_add_interface_static (test_async_test_type_id, VALADATE_TYPE_FIXTURE, &valadate_fixture_info);
		g_once_init_leave (&test_async_test_type_id__volatile, test_async_test_type_id);
	}
	return test_async_test_type_id__volatile;
}



