def build(bld):
    lib = bld.new_task_gen(
            features='cc cshlib',
            target='test',
            gir='Test-0',
            packages='glib-2.0 gobject-2.0',
            uselib='glib-2.0 gobject-2.0',
            uselib_local='valadate-%(API_VER)s' % bld.env,
            ccflags=['-ggdb'],
            install_path=None)
    lib.find_sources_in_dirs('.')
# vim: set ft=python sw=4 sts=4 et:
