def build(bld):
    bld.shlib(source=bld.path.ant_glob('*.vala'),
              target='test',
              gir='Test-0',
              packages='glib-2.0 gobject-2.0 libvala-0.12 ',
              uselib='glib-2.0 gobject-2.0 libvala-0.12 ',
              use='valadate-%(API_VER)s' % bld.env,
              cflags=['-ggdb'],
              install_path=None)

