/* application.c generated by valac 0.30.0, the Vala compiler
 * generated from application.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define EXAMPLE_TYPE_APPLICATION (example_application_get_type ())
#define EXAMPLE_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXAMPLE_TYPE_APPLICATION, ExampleApplication))
#define EXAMPLE_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXAMPLE_TYPE_APPLICATION, ExampleApplicationClass))
#define EXAMPLE_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXAMPLE_TYPE_APPLICATION))
#define EXAMPLE_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXAMPLE_TYPE_APPLICATION))
#define EXAMPLE_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXAMPLE_TYPE_APPLICATION, ExampleApplicationClass))

typedef struct _ExampleApplication ExampleApplication;
typedef struct _ExampleApplicationClass ExampleApplicationClass;
typedef struct _ExampleApplicationPrivate ExampleApplicationPrivate;

#define EXAMPLE_TYPE_APPLICATION_WINDOW (example_application_window_get_type ())
#define EXAMPLE_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXAMPLE_TYPE_APPLICATION_WINDOW, ExampleApplicationWindow))
#define EXAMPLE_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXAMPLE_TYPE_APPLICATION_WINDOW, ExampleApplicationWindowClass))
#define EXAMPLE_IS_APPLICATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXAMPLE_TYPE_APPLICATION_WINDOW))
#define EXAMPLE_IS_APPLICATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXAMPLE_TYPE_APPLICATION_WINDOW))
#define EXAMPLE_APPLICATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXAMPLE_TYPE_APPLICATION_WINDOW, ExampleApplicationWindowClass))

typedef struct _ExampleApplicationWindow ExampleApplicationWindow;
typedef struct _ExampleApplicationWindowClass ExampleApplicationWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define EXAMPLE_TYPE_APPLICATION_PREFERENCES (example_application_preferences_get_type ())
#define EXAMPLE_APPLICATION_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXAMPLE_TYPE_APPLICATION_PREFERENCES, ExampleApplicationPreferences))
#define EXAMPLE_APPLICATION_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXAMPLE_TYPE_APPLICATION_PREFERENCES, ExampleApplicationPreferencesClass))
#define EXAMPLE_IS_APPLICATION_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXAMPLE_TYPE_APPLICATION_PREFERENCES))
#define EXAMPLE_IS_APPLICATION_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXAMPLE_TYPE_APPLICATION_PREFERENCES))
#define EXAMPLE_APPLICATION_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXAMPLE_TYPE_APPLICATION_PREFERENCES, ExampleApplicationPreferencesClass))

typedef struct _ExampleApplicationPreferences ExampleApplicationPreferences;
typedef struct _ExampleApplicationPreferencesClass ExampleApplicationPreferencesClass;

struct _ExampleApplication {
	GtkApplication parent_instance;
	ExampleApplicationPrivate * priv;
};

struct _ExampleApplicationClass {
	GtkApplicationClass parent_class;
};

struct _ExampleApplicationPrivate {
	ExampleApplicationWindow* window;
};


static gpointer example_application_parent_class = NULL;

GType example_application_get_type (void) G_GNUC_CONST;
GType example_application_window_get_type (void) G_GNUC_CONST;
#define EXAMPLE_APPLICATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXAMPLE_TYPE_APPLICATION, ExampleApplicationPrivate))
enum  {
	EXAMPLE_APPLICATION_DUMMY_PROPERTY
};
ExampleApplication* example_application_new (void);
ExampleApplication* example_application_construct (GType object_type);
static void example_application_real_activate (GApplication* base);
ExampleApplicationWindow* example_application_window_new (GtkApplication* application);
ExampleApplicationWindow* example_application_window_construct (GType object_type, GtkApplication* application);
static void example_application_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint);
void example_application_window_open (ExampleApplicationWindow* self, GFile* file);
static void example_application_preferences (ExampleApplication* self);
GType example_application_preferences_get_type (void) G_GNUC_CONST;
ExampleApplicationPreferences* example_application_preferences_new (ExampleApplicationWindow* window);
ExampleApplicationPreferences* example_application_preferences_construct (GType object_type, ExampleApplicationWindow* window);
static void example_application_real_startup (GApplication* base);
static void _example_application_preferences_g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void _g_application_quit_g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void example_application_finalize (GObject* obj);


ExampleApplication* example_application_construct (GType object_type) {
	ExampleApplication * self = NULL;
	GApplicationFlags _tmp0_ = 0;
	GApplicationFlags _tmp1_ = 0;
	self = (ExampleApplication*) g_object_new (object_type, NULL);
	g_application_set_application_id ((GApplication*) self, "org.gtk.exampleapp");
	_tmp0_ = g_application_get_flags ((GApplication*) self);
	_tmp1_ = _tmp0_;
	g_application_set_flags ((GApplication*) self, _tmp1_ | G_APPLICATION_HANDLES_OPEN);
	return self;
}


ExampleApplication* example_application_new (void) {
	return example_application_construct (EXAMPLE_TYPE_APPLICATION);
}


static void example_application_real_activate (GApplication* base) {
	ExampleApplication * self;
	ExampleApplicationWindow* _tmp0_ = NULL;
	ExampleApplicationWindow* _tmp1_ = NULL;
	self = (ExampleApplication*) base;
	_tmp0_ = example_application_window_new ((GtkApplication*) self);
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->window);
	self->priv->window = _tmp0_;
	_tmp1_ = self->priv->window;
	gtk_window_present ((GtkWindow*) _tmp1_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void example_application_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint) {
	ExampleApplication * self;
	ExampleApplicationWindow* _tmp0_ = NULL;
	GFile** _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	ExampleApplicationWindow* _tmp6_ = NULL;
	self = (ExampleApplication*) base;
	g_return_if_fail (hint != NULL);
	_tmp0_ = self->priv->window;
	if (_tmp0_ == NULL) {
		ExampleApplicationWindow* _tmp1_ = NULL;
		_tmp1_ = example_application_window_new ((GtkApplication*) self);
		g_object_ref_sink (_tmp1_);
		_g_object_unref0 (self->priv->window);
		self->priv->window = _tmp1_;
	}
	_tmp2_ = files;
	_tmp2__length1 = files_length1;
	{
		GFile** file_collection = NULL;
		gint file_collection_length1 = 0;
		gint _file_collection_size_ = 0;
		gint file_it = 0;
		file_collection = _tmp2_;
		file_collection_length1 = _tmp2__length1;
		for (file_it = 0; file_it < _tmp2__length1; file_it = file_it + 1) {
			GFile* _tmp3_ = NULL;
			GFile* file = NULL;
			_tmp3_ = _g_object_ref0 (file_collection[file_it]);
			file = _tmp3_;
			{
				ExampleApplicationWindow* _tmp4_ = NULL;
				GFile* _tmp5_ = NULL;
				_tmp4_ = self->priv->window;
				_tmp5_ = file;
				example_application_window_open (_tmp4_, _tmp5_);
				_g_object_unref0 (file);
			}
		}
	}
	_tmp6_ = self->priv->window;
	gtk_window_present ((GtkWindow*) _tmp6_);
}


static void example_application_preferences (ExampleApplication* self) {
	ExampleApplicationPreferences* prefs = NULL;
	ExampleApplicationWindow* _tmp0_ = NULL;
	ExampleApplicationPreferences* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->window;
	_tmp1_ = example_application_preferences_new (_tmp0_);
	g_object_ref_sink (_tmp1_);
	prefs = _tmp1_;
	gtk_window_present ((GtkWindow*) prefs);
	_g_object_unref0 (prefs);
}


static void _example_application_preferences_g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	example_application_preferences ((ExampleApplication*) self);
}


static void _g_application_quit_g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	g_application_quit ((GApplication*) self);
}


static void example_application_real_startup (GApplication* base) {
	ExampleApplication * self;
	GSimpleAction* action = NULL;
	GSimpleAction* _tmp0_ = NULL;
	GSimpleAction* _tmp1_ = NULL;
	GSimpleAction* _tmp2_ = NULL;
	GSimpleAction* _tmp3_ = NULL;
	GSimpleAction* _tmp4_ = NULL;
	GSimpleAction* _tmp5_ = NULL;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp6_ = NULL;
	GMenuModel* app_menu = NULL;
	GObject* _tmp7_ = NULL;
	GMenuModel* _tmp8_ = NULL;
	self = (ExampleApplication*) base;
	G_APPLICATION_CLASS (example_application_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	_tmp0_ = g_simple_action_new ("preferences", NULL);
	action = _tmp0_;
	_tmp1_ = action;
	g_signal_connect_object (_tmp1_, "activate", (GCallback) _example_application_preferences_g_simple_action_activate, self, 0);
	_tmp2_ = action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp2_);
	_tmp3_ = g_simple_action_new ("quit", NULL);
	_g_object_unref0 (action);
	action = _tmp3_;
	_tmp4_ = action;
	g_signal_connect_object (_tmp4_, "activate", (GCallback) _g_application_quit_g_simple_action_activate, (GApplication*) self, 0);
	_tmp5_ = action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp5_);
	gtk_application_add_accelerator ((GtkApplication*) self, "<Ctrl>Q", "app.quit", NULL);
	_tmp6_ = gtk_builder_new_from_resource ("/org/gtk/exampleapp/app-menu.ui");
	builder = _tmp6_;
	_tmp7_ = gtk_builder_get_object (builder, "appmenu");
	_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, g_menu_model_get_type ()) ? ((GMenuModel*) _tmp7_) : NULL);
	app_menu = _tmp8_;
	gtk_application_set_app_menu ((GtkApplication*) self, app_menu);
	_g_object_unref0 (app_menu);
	_g_object_unref0 (builder);
	_g_object_unref0 (action);
}


static void example_application_class_init (ExampleApplicationClass * klass) {
	example_application_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExampleApplicationPrivate));
	((GApplicationClass *) klass)->activate = example_application_real_activate;
	((GApplicationClass *) klass)->open = example_application_real_open;
	((GApplicationClass *) klass)->startup = example_application_real_startup;
	G_OBJECT_CLASS (klass)->finalize = example_application_finalize;
}


static void example_application_instance_init (ExampleApplication * self) {
	self->priv = EXAMPLE_APPLICATION_GET_PRIVATE (self);
}


static void example_application_finalize (GObject* obj) {
	ExampleApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, EXAMPLE_TYPE_APPLICATION, ExampleApplication);
	_g_object_unref0 (self->priv->window);
	G_OBJECT_CLASS (example_application_parent_class)->finalize (obj);
}


GType example_application_get_type (void) {
	static volatile gsize example_application_type_id__volatile = 0;
	if (g_once_init_enter (&example_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExampleApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) example_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExampleApplication), 0, (GInstanceInitFunc) example_application_instance_init, NULL };
		GType example_application_type_id;
		example_application_type_id = g_type_register_static (gtk_application_get_type (), "ExampleApplication", &g_define_type_info, 0);
		g_once_init_leave (&example_application_type_id__volatile, example_application_type_id);
	}
	return example_application_type_id__volatile;
}



