/* tests_PIE.vapi generated by valac 0.30.0, do not modify. */

[CCode (gir_namespace = "Valadate", gir_version = "1.0")]
namespace Valadate {
	namespace Framework {
		namespace Tests {
			[CCode (cheader_filename = "testpie.h")]
			public class TestPIE : Valadate.Framework.TestCase {
				public TestPIE ();
				[Test (name = "test_pie_fail")]
				public void test_pie_fail ();
				[Test (name = "test_pie_pass")]
				public void test_pie_pass ();
			}
		}
	}
}
