/* testload_PIE.vapi generated by valac 0.34.7, do not modify. */

[CCode (gir_namespace = "Valadate", gir_version = "1.0")]
namespace Valadate {
	namespace Tests {
		[CCode (cheader_filename = "testloadpie.h")]
		public class TestLoadPIE : Valadate.TestCase {
			public TestLoadPIE ();
			[Test (name = "test if the binary has a test method")]
			public void has_test_method ();
			[Test (name = "test loading pie binary")]
			public void load_pie ();
		}
	}
}
