/* tests_PIE.vapi generated by valac 0.34.7, do not modify. */

[CCode (gir_namespace = "Valadate", gir_version = "1.0")]
namespace Valadate {
	[CCode (gir_namespace = "ValadateTests", gir_version = "1.0")]
	namespace Tests {
		[CCode (cheader_filename = "testpie.h")]
		public class TestPIE : Valadate.TestCase {
			public TestPIE ();
			[Test (name = "tests fails")]
			public void test_pie_fail ();
			[Test (name = "tests passes")]
			public void test_pie_pass ();
		}
	}
}
