/* main.c generated by valac 0.30.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




void valadate_add_tests (void);
static void __lambda4_ (void);
static void ___lambda4__gcallback (void);
void valadate_main (gchar** args, int args_length1);


static void __lambda4_ (void) {
}


static void ___lambda4__gcallback (void) {
#line 4 "/home/bizarro/Documents/projects/valadate/tests/libvaladate/main.vala"
	__lambda4_ ();
#line 27 "main.c"
}


void valadate_add_tests (void) {
#line 4 "/home/bizarro/Documents/projects/valadate/tests/libvaladate/main.vala"
	g_test_add_func ("/libvaladate/testcase/new", ___lambda4__gcallback);
#line 34 "main.c"
}


void valadate_main (gchar** args, int args_length1) {
#line 11 "/home/bizarro/Documents/projects/valadate/tests/libvaladate/main.vala"
	g_test_init (&args_length1, &args, NULL);
#line 12 "/home/bizarro/Documents/projects/valadate/tests/libvaladate/main.vala"
	valadate_add_tests ();
#line 13 "/home/bizarro/Documents/projects/valadate/tests/libvaladate/main.vala"
	g_test_run ();
#line 45 "main.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 10 "/home/bizarro/Documents/projects/valadate/tests/libvaladate/main.vala"
	valadate_main (argv, argc);
#line 10 "/home/bizarro/Documents/projects/valadate/tests/libvaladate/main.vala"
	return 0;
#line 57 "main.c"
}



