/* testplan.c generated by valac 0.34.7, the Vala compiler
 * generated from testplan.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <libvaladate-1.0.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _valadate_test_options_unref0(var) ((var == NULL) ? NULL : (var = (valadate_test_options_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);



void valadate_tests_new_test_plan (void);
void valadate_tests_test_plan_no_of_testsuites (void);
void valadate_tests_test_plan_no_of_tests (void);
void valadate_tests_test_plan_tests_abstract (void);
void valadate_tests_test_plan_no_of_inherited_tests (void);
void valadate_tests_test_plan_tests_with_label (void);
void valadate_tests_test_plan_run_single_test (void);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


void valadate_tests_new_test_plan (void) {
	gchar* oldenv = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* builddir = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GFile* newenv = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GFile* _tmp6_ = NULL;
	GFile* _tmp7_ = NULL;
	GFile* binary = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	GFile* _tmp10_ = NULL;
	GFile* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	ValadateTestOptions* options = NULL;
	gchar* _tmp14_ = NULL;
	gchar** _tmp15_ = NULL;
	gchar** _tmp16_ = NULL;
	gint _tmp16__length1 = 0;
	ValadateTestOptions* _tmp17_ = NULL;
	ValadateTestOptions* _tmp18_ = NULL;
	ValadateTestPlan* tplan = NULL;
	ValadateTestPlan* _tmp19_ = NULL;
	ValadateTestPlan* _tmp20_ = NULL;
	ValadateTestPlan* _tmp21_ = NULL;
	GError * _inner_error_ = NULL;
#line 5 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp0_ = g_getenv ("G_TEST_SRCDIR");
#line 5 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 5 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	oldenv = _tmp1_;
#line 6 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp2_ = g_getenv ("G_TEST_BUILDDIR");
#line 6 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 6 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	builddir = _tmp3_;
#line 8 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp4_ = g_build_filename (oldenv, "..", "data", NULL);
#line 8 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp5_ = _tmp4_;
#line 8 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp6_ = g_file_new_for_path (_tmp5_);
#line 8 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_ = _tmp6_;
#line 8 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp5_);
#line 8 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	newenv = _tmp7_;
#line 11 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = g_build_filename (builddir, "..", "data", ".libs", "testexe-0", NULL);
#line 11 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp9_ = _tmp8_;
#line 11 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_ = g_file_new_for_path (_tmp9_);
#line 11 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11_ = _tmp10_;
#line 11 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp9_);
#line 11 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	binary = _tmp11_;
#line 14 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp12_ = g_file_get_path (newenv);
#line 14 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp13_ = _tmp12_;
#line 14 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	g_setenv ("G_TEST_SRCDIR", _tmp13_, TRUE);
#line 14 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp13_);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp14_ = g_file_get_path (binary);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp15_ = g_new0 (gchar*, 1 + 1);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp15_[0] = _tmp14_;
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16_ = _tmp15_;
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16__length1 = 1;
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp17_ = valadate_test_options_new (_tmp16_, 1, &_inner_error_);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp18_ = _tmp17_;
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16_ = (_vala_array_free (_tmp16_, _tmp16__length1, (GDestroyNotify) g_free), NULL);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	options = _tmp18_;
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_object_unref0 (binary);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_object_unref0 (newenv);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (builddir);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (oldenv);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_clear_error (&_inner_error_);
#line 16 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		return;
#line 143 "testplan.c"
	}
#line 18 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp19_ = valadate_test_plan_new (options);
#line 18 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	tplan = _tmp19_;
#line 20 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp20_ = tplan;
#line 20 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (G_TYPE_CHECK_INSTANCE_TYPE (_tmp20_, VALADATE_TYPE_TEST_PLAN), "tplan is TestPlan");
#line 21 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp21_ = tplan;
#line 21 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (G_TYPE_CHECK_INSTANCE_TYPE (_tmp21_, VALADATE_TYPE_GIR_TEST_PLAN), "tplan is GirTestPlan");
#line 3 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (tplan);
#line 3 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_valadate_test_options_unref0 (options);
#line 3 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (binary);
#line 3 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (newenv);
#line 3 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (builddir);
#line 3 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (oldenv);
#line 169 "testplan.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 35 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	return self ? g_object_ref (self) : NULL;
#line 176 "testplan.c"
}


void valadate_tests_test_plan_no_of_testsuites (void) {
	gchar* builddir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* binary = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	ValadateTestOptions* options = NULL;
	gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	ValadateTestOptions* _tmp9_ = NULL;
	ValadateTestOptions* _tmp10_ = NULL;
	ValadateTestPlan* tplan = NULL;
	ValadateTestPlan* _tmp11_ = NULL;
	ValadateTestConfig* conf = NULL;
	ValadateTestPlan* _tmp12_ = NULL;
	ValadateTestConfig* _tmp13_ = NULL;
	ValadateTestConfig* _tmp14_ = NULL;
	ValadateTestConfig* _tmp15_ = NULL;
	ValadateTestConfig* _tmp16_ = NULL;
	ValadateTestSuite* _tmp17_ = NULL;
	ValadateTestSuite* _tmp18_ = NULL;
	ValadateTest* _tmp19_ = NULL;
	ValadateTest* _tmp20_ = NULL;
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
	GError * _inner_error_ = NULL;
#line 26 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp0_ = g_getenv ("G_TEST_BUILDDIR");
#line 26 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 26 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	builddir = _tmp1_;
#line 28 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp2_ = g_build_filename (builddir, "..", "data", ".libs", "testexe-0", NULL);
#line 28 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp3_ = _tmp2_;
#line 28 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp4_ = g_file_new_for_path (_tmp3_);
#line 28 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp5_ = _tmp4_;
#line 28 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp3_);
#line 28 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	binary = _tmp5_;
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp6_ = g_file_get_path (binary);
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_ = g_new0 (gchar*, 1 + 1);
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_[0] = _tmp6_;
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = _tmp7_;
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8__length1 = 1;
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp9_ = valadate_test_options_new (_tmp8_, 1, &_inner_error_);
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_ = _tmp9_;
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	options = _tmp10_;
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_object_unref0 (binary);
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (builddir);
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_clear_error (&_inner_error_);
#line 31 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		return;
#line 259 "testplan.c"
	}
#line 33 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11_ = valadate_test_plan_new (options);
#line 33 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	tplan = _tmp11_;
#line 35 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp12_ = tplan;
#line 35 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp13_ = valadate_test_plan_get_config (_tmp12_);
#line 35 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp14_ = _tmp13_;
#line 35 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp15_ = _g_object_ref0 (_tmp14_);
#line 35 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	conf = _tmp15_;
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16_ = conf;
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp17_ = valadate_test_config_get_root (_tmp16_);
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp18_ = _tmp17_;
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp19_ = valadate_test_get ((ValadateTest*) _tmp18_, 0);
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp20_ = _tmp19_;
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp21_ = valadate_test_get_count (_tmp20_);
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp22_ = _tmp21_;
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (_tmp22_ == 4, "conf.root[0].count == 4");
#line 37 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp20_);
#line 24 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (conf);
#line 24 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (tplan);
#line 24 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_valadate_test_options_unref0 (options);
#line 24 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (binary);
#line 24 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (builddir);
#line 303 "testplan.c"
}


void valadate_tests_test_plan_no_of_tests (void) {
	gchar* builddir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* binary = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	ValadateTestOptions* options = NULL;
	gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	ValadateTestOptions* _tmp9_ = NULL;
	ValadateTestOptions* _tmp10_ = NULL;
	ValadateTestPlan* tplan = NULL;
	ValadateTestPlan* _tmp11_ = NULL;
	ValadateTestConfig* conf = NULL;
	ValadateTestPlan* _tmp12_ = NULL;
	ValadateTestConfig* _tmp13_ = NULL;
	ValadateTestConfig* _tmp14_ = NULL;
	ValadateTestConfig* _tmp15_ = NULL;
	ValadateTestConfig* _tmp16_ = NULL;
	ValadateTestSuite* _tmp17_ = NULL;
	ValadateTestSuite* _tmp18_ = NULL;
	ValadateTest* _tmp19_ = NULL;
	ValadateTest* _tmp20_ = NULL;
	ValadateTest* _tmp21_ = NULL;
	ValadateTest* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	ValadateTestConfig* _tmp25_ = NULL;
	ValadateTestSuite* _tmp26_ = NULL;
	ValadateTestSuite* _tmp27_ = NULL;
	ValadateTest* _tmp28_ = NULL;
	ValadateTest* _tmp29_ = NULL;
	ValadateTest* _tmp30_ = NULL;
	ValadateTest* _tmp31_ = NULL;
	gint _tmp32_ = 0;
	gint _tmp33_ = 0;
	GError * _inner_error_ = NULL;
#line 42 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp0_ = g_getenv ("G_TEST_BUILDDIR");
#line 42 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 42 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	builddir = _tmp1_;
#line 44 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp2_ = g_build_filename (builddir, "..", "data", ".libs", "testexe-0", NULL);
#line 44 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp3_ = _tmp2_;
#line 44 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp4_ = g_file_new_for_path (_tmp3_);
#line 44 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp5_ = _tmp4_;
#line 44 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp3_);
#line 44 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	binary = _tmp5_;
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp6_ = g_file_get_path (binary);
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_ = g_new0 (gchar*, 1 + 1);
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_[0] = _tmp6_;
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = _tmp7_;
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8__length1 = 1;
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp9_ = valadate_test_options_new (_tmp8_, 1, &_inner_error_);
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_ = _tmp9_;
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	options = _tmp10_;
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_object_unref0 (binary);
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (builddir);
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_clear_error (&_inner_error_);
#line 47 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		return;
#line 397 "testplan.c"
	}
#line 49 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11_ = valadate_test_plan_new (options);
#line 49 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	tplan = _tmp11_;
#line 51 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp12_ = tplan;
#line 51 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp13_ = valadate_test_plan_get_config (_tmp12_);
#line 51 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp14_ = _tmp13_;
#line 51 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp15_ = _g_object_ref0 (_tmp14_);
#line 51 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	conf = _tmp15_;
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16_ = conf;
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp17_ = valadate_test_config_get_root (_tmp16_);
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp18_ = _tmp17_;
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp19_ = valadate_test_get ((ValadateTest*) _tmp18_, 0);
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp20_ = _tmp19_;
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp21_ = valadate_test_get (_tmp20_, 0);
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp22_ = _tmp21_;
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp23_ = valadate_test_get_name (_tmp22_);
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp24_ = _tmp23_;
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (g_strcmp0 (_tmp24_, "TestsTestExe") == 0, "conf.root[0][0].name == \"TestsTestExe\"");
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp22_);
#line 53 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp20_);
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp25_ = conf;
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp26_ = valadate_test_config_get_root (_tmp25_);
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp27_ = _tmp26_;
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp28_ = valadate_test_get ((ValadateTest*) _tmp27_, 0);
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp29_ = _tmp28_;
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp30_ = valadate_test_get (_tmp29_, 0);
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp31_ = _tmp30_;
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp32_ = valadate_test_get_count (_tmp31_);
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp33_ = _tmp32_;
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (_tmp33_ == 5, "conf.root[0][0].count == 5");
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp31_);
#line 54 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp29_);
#line 40 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (conf);
#line 40 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (tplan);
#line 40 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_valadate_test_options_unref0 (options);
#line 40 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (binary);
#line 40 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (builddir);
#line 471 "testplan.c"
}


void valadate_tests_test_plan_tests_abstract (void) {
	gchar* builddir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* binary = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	ValadateTestOptions* options = NULL;
	gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	ValadateTestOptions* _tmp9_ = NULL;
	ValadateTestOptions* _tmp10_ = NULL;
	ValadateTestPlan* tplan = NULL;
	ValadateTestPlan* _tmp11_ = NULL;
	ValadateTestConfig* conf = NULL;
	ValadateTestPlan* _tmp12_ = NULL;
	ValadateTestConfig* _tmp13_ = NULL;
	ValadateTestConfig* _tmp14_ = NULL;
	ValadateTestConfig* _tmp15_ = NULL;
	ValadateTestConfig* _tmp16_ = NULL;
	ValadateTestSuite* _tmp17_ = NULL;
	ValadateTestSuite* _tmp18_ = NULL;
	ValadateTest* _tmp19_ = NULL;
	ValadateTest* _tmp20_ = NULL;
	ValadateTest* _tmp21_ = NULL;
	ValadateTest* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	ValadateTestConfig* _tmp25_ = NULL;
	ValadateTestSuite* _tmp26_ = NULL;
	ValadateTestSuite* _tmp27_ = NULL;
	ValadateTest* _tmp28_ = NULL;
	ValadateTest* _tmp29_ = NULL;
	ValadateTest* _tmp30_ = NULL;
	ValadateTest* _tmp31_ = NULL;
	gint _tmp32_ = 0;
	gint _tmp33_ = 0;
	GError * _inner_error_ = NULL;
#line 59 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp0_ = g_getenv ("G_TEST_BUILDDIR");
#line 59 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 59 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	builddir = _tmp1_;
#line 61 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp2_ = g_build_filename (builddir, "..", "data", ".libs", "testexe-0", NULL);
#line 61 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp3_ = _tmp2_;
#line 61 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp4_ = g_file_new_for_path (_tmp3_);
#line 61 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp5_ = _tmp4_;
#line 61 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp3_);
#line 61 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	binary = _tmp5_;
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp6_ = g_file_get_path (binary);
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_ = g_new0 (gchar*, 1 + 1);
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_[0] = _tmp6_;
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = _tmp7_;
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8__length1 = 1;
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp9_ = valadate_test_options_new (_tmp8_, 1, &_inner_error_);
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_ = _tmp9_;
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	options = _tmp10_;
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_object_unref0 (binary);
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (builddir);
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_clear_error (&_inner_error_);
#line 64 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		return;
#line 565 "testplan.c"
	}
#line 66 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11_ = valadate_test_plan_new (options);
#line 66 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	tplan = _tmp11_;
#line 68 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp12_ = tplan;
#line 68 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp13_ = valadate_test_plan_get_config (_tmp12_);
#line 68 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp14_ = _tmp13_;
#line 68 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp15_ = _g_object_ref0 (_tmp14_);
#line 68 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	conf = _tmp15_;
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16_ = conf;
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp17_ = valadate_test_config_get_root (_tmp16_);
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp18_ = _tmp17_;
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp19_ = valadate_test_get ((ValadateTest*) _tmp18_, 0);
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp20_ = _tmp19_;
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp21_ = valadate_test_get (_tmp20_, 3);
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp22_ = _tmp21_;
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp23_ = valadate_test_get_name (_tmp22_);
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp24_ = _tmp23_;
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (g_strcmp0 (_tmp24_, "TestsTestExeAbstractImpl") == 0, "conf.root[0][3].name == \"TestsTestExeAbstractImpl\"");
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp22_);
#line 70 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp20_);
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp25_ = conf;
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp26_ = valadate_test_config_get_root (_tmp25_);
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp27_ = _tmp26_;
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp28_ = valadate_test_get ((ValadateTest*) _tmp27_, 0);
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp29_ = _tmp28_;
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp30_ = valadate_test_get (_tmp29_, 3);
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp31_ = _tmp30_;
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp32_ = valadate_test_get_count (_tmp31_);
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp33_ = _tmp32_;
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (_tmp33_ == 4, "conf.root[0][3].count == 4");
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp31_);
#line 71 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp29_);
#line 57 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (conf);
#line 57 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (tplan);
#line 57 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_valadate_test_options_unref0 (options);
#line 57 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (binary);
#line 57 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (builddir);
#line 639 "testplan.c"
}


void valadate_tests_test_plan_no_of_inherited_tests (void) {
	gchar* builddir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* binary = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	ValadateTestOptions* options = NULL;
	gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	ValadateTestOptions* _tmp9_ = NULL;
	ValadateTestOptions* _tmp10_ = NULL;
	ValadateTestPlan* tplan = NULL;
	ValadateTestPlan* _tmp11_ = NULL;
	ValadateTestConfig* conf = NULL;
	ValadateTestPlan* _tmp12_ = NULL;
	ValadateTestConfig* _tmp13_ = NULL;
	ValadateTestConfig* _tmp14_ = NULL;
	ValadateTestConfig* _tmp15_ = NULL;
	ValadateTestConfig* _tmp16_ = NULL;
	ValadateTestSuite* _tmp17_ = NULL;
	ValadateTestSuite* _tmp18_ = NULL;
	ValadateTest* _tmp19_ = NULL;
	ValadateTest* _tmp20_ = NULL;
	ValadateTest* _tmp21_ = NULL;
	ValadateTest* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	ValadateTestConfig* _tmp25_ = NULL;
	ValadateTestSuite* _tmp26_ = NULL;
	ValadateTestSuite* _tmp27_ = NULL;
	ValadateTest* _tmp28_ = NULL;
	ValadateTest* _tmp29_ = NULL;
	ValadateTest* _tmp30_ = NULL;
	ValadateTest* _tmp31_ = NULL;
	gint _tmp32_ = 0;
	gint _tmp33_ = 0;
	GError * _inner_error_ = NULL;
#line 76 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp0_ = g_getenv ("G_TEST_BUILDDIR");
#line 76 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 76 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	builddir = _tmp1_;
#line 78 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp2_ = g_build_filename (builddir, "..", "data", ".libs", "testexe-0", NULL);
#line 78 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp3_ = _tmp2_;
#line 78 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp4_ = g_file_new_for_path (_tmp3_);
#line 78 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp5_ = _tmp4_;
#line 78 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp3_);
#line 78 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	binary = _tmp5_;
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp6_ = g_file_get_path (binary);
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_ = g_new0 (gchar*, 1 + 1);
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_[0] = _tmp6_;
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = _tmp7_;
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8__length1 = 1;
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp9_ = valadate_test_options_new (_tmp8_, 1, &_inner_error_);
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_ = _tmp9_;
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	options = _tmp10_;
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_object_unref0 (binary);
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (builddir);
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_clear_error (&_inner_error_);
#line 81 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		return;
#line 733 "testplan.c"
	}
#line 83 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11_ = valadate_test_plan_new (options);
#line 83 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	tplan = _tmp11_;
#line 85 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp12_ = tplan;
#line 85 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp13_ = valadate_test_plan_get_config (_tmp12_);
#line 85 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp14_ = _tmp13_;
#line 85 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp15_ = _g_object_ref0 (_tmp14_);
#line 85 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	conf = _tmp15_;
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16_ = conf;
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp17_ = valadate_test_config_get_root (_tmp16_);
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp18_ = _tmp17_;
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp19_ = valadate_test_get ((ValadateTest*) _tmp18_, 0);
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp20_ = _tmp19_;
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp21_ = valadate_test_get (_tmp20_, 1);
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp22_ = _tmp21_;
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp23_ = valadate_test_get_name (_tmp22_);
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp24_ = _tmp23_;
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (g_strcmp0 (_tmp24_, "TestsTestExeSubClass") == 0, "conf.root[0][1].name == \"TestsTestExeSubClass\"");
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp22_);
#line 87 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp20_);
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp25_ = conf;
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp26_ = valadate_test_config_get_root (_tmp25_);
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp27_ = _tmp26_;
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp28_ = valadate_test_get ((ValadateTest*) _tmp27_, 0);
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp29_ = _tmp28_;
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp30_ = valadate_test_get (_tmp29_, 1);
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp31_ = _tmp30_;
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp32_ = valadate_test_get_count (_tmp31_);
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp33_ = _tmp32_;
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (_tmp33_ == 6, "conf.root[0][1].count == 6");
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp31_);
#line 88 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp29_);
#line 74 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (conf);
#line 74 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (tplan);
#line 74 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_valadate_test_options_unref0 (options);
#line 74 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (binary);
#line 74 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (builddir);
#line 807 "testplan.c"
}


void valadate_tests_test_plan_tests_with_label (void) {
	gchar* builddir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* binary = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	ValadateTestOptions* options = NULL;
	gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	ValadateTestOptions* _tmp9_ = NULL;
	ValadateTestOptions* _tmp10_ = NULL;
	ValadateTestPlan* tplan = NULL;
	ValadateTestPlan* _tmp11_ = NULL;
	ValadateTestConfig* conf = NULL;
	ValadateTestPlan* _tmp12_ = NULL;
	ValadateTestConfig* _tmp13_ = NULL;
	ValadateTestConfig* _tmp14_ = NULL;
	ValadateTestConfig* _tmp15_ = NULL;
	ValadateTestConfig* _tmp16_ = NULL;
	ValadateTestSuite* _tmp17_ = NULL;
	ValadateTestSuite* _tmp18_ = NULL;
	ValadateTest* _tmp19_ = NULL;
	ValadateTest* _tmp20_ = NULL;
	ValadateTest* _tmp21_ = NULL;
	ValadateTest* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	ValadateTestConfig* _tmp25_ = NULL;
	ValadateTestSuite* _tmp26_ = NULL;
	ValadateTestSuite* _tmp27_ = NULL;
	ValadateTest* _tmp28_ = NULL;
	ValadateTest* _tmp29_ = NULL;
	ValadateTest* _tmp30_ = NULL;
	ValadateTest* _tmp31_ = NULL;
	gint _tmp32_ = 0;
	gint _tmp33_ = 0;
	ValadateTestConfig* _tmp34_ = NULL;
	ValadateTestSuite* _tmp35_ = NULL;
	ValadateTestSuite* _tmp36_ = NULL;
	ValadateTest* _tmp37_ = NULL;
	ValadateTest* _tmp38_ = NULL;
	ValadateTest* _tmp39_ = NULL;
	ValadateTest* _tmp40_ = NULL;
	ValadateTest* _tmp41_ = NULL;
	ValadateTest* _tmp42_ = NULL;
	const gchar* _tmp43_ = NULL;
	const gchar* _tmp44_ = NULL;
	ValadateTestConfig* _tmp45_ = NULL;
	ValadateTestSuite* _tmp46_ = NULL;
	ValadateTestSuite* _tmp47_ = NULL;
	ValadateTest* _tmp48_ = NULL;
	ValadateTest* _tmp49_ = NULL;
	ValadateTest* _tmp50_ = NULL;
	ValadateTest* _tmp51_ = NULL;
	ValadateTest* _tmp52_ = NULL;
	ValadateTest* _tmp53_ = NULL;
	const gchar* _tmp54_ = NULL;
	const gchar* _tmp55_ = NULL;
	GError * _inner_error_ = NULL;
#line 93 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp0_ = g_getenv ("G_TEST_BUILDDIR");
#line 93 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 93 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	builddir = _tmp1_;
#line 95 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp2_ = g_build_filename (builddir, "..", "data", ".libs", "testexe-0", NULL);
#line 95 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp3_ = _tmp2_;
#line 95 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp4_ = g_file_new_for_path (_tmp3_);
#line 95 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp5_ = _tmp4_;
#line 95 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp3_);
#line 95 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	binary = _tmp5_;
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp6_ = g_file_get_path (binary);
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_ = g_new0 (gchar*, 1 + 1);
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_[0] = _tmp6_;
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = _tmp7_;
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8__length1 = 1;
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp9_ = valadate_test_options_new (_tmp8_, 1, &_inner_error_);
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_ = _tmp9_;
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	options = _tmp10_;
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_object_unref0 (binary);
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (builddir);
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_clear_error (&_inner_error_);
#line 98 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		return;
#line 923 "testplan.c"
	}
#line 100 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11_ = valadate_test_plan_new (options);
#line 100 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	tplan = _tmp11_;
#line 102 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp12_ = tplan;
#line 102 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp13_ = valadate_test_plan_get_config (_tmp12_);
#line 102 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp14_ = _tmp13_;
#line 102 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp15_ = _g_object_ref0 (_tmp14_);
#line 102 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	conf = _tmp15_;
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16_ = conf;
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp17_ = valadate_test_config_get_root (_tmp16_);
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp18_ = _tmp17_;
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp19_ = valadate_test_get ((ValadateTest*) _tmp18_, 0);
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp20_ = _tmp19_;
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp21_ = valadate_test_get (_tmp20_, 2);
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp22_ = _tmp21_;
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp23_ = valadate_test_get_name (_tmp22_);
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp24_ = _tmp23_;
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (g_strcmp0 (_tmp24_, "TestsTestExeTwo") == 0, "conf.root[0][2].name == \"TestsTestExeTwo\"");
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp22_);
#line 104 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp20_);
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp25_ = conf;
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp26_ = valadate_test_config_get_root (_tmp25_);
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp27_ = _tmp26_;
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp28_ = valadate_test_get ((ValadateTest*) _tmp27_, 0);
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp29_ = _tmp28_;
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp30_ = valadate_test_get (_tmp29_, 2);
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp31_ = _tmp30_;
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp32_ = valadate_test_get_count (_tmp31_);
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp33_ = _tmp32_;
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (_tmp33_ == 2, "conf.root[0][2].count == 2");
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp31_);
#line 105 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp29_);
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp34_ = conf;
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp35_ = valadate_test_config_get_root (_tmp34_);
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp36_ = _tmp35_;
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp37_ = valadate_test_get ((ValadateTest*) _tmp36_, 0);
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp38_ = _tmp37_;
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp39_ = valadate_test_get (_tmp38_, 2);
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp40_ = _tmp39_;
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp41_ = valadate_test_get (_tmp40_, 0);
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp42_ = _tmp41_;
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp43_ = valadate_test_get_label (_tmp42_);
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp44_ = _tmp43_;
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (g_strcmp0 (_tmp44_, "Test One") == 0, "conf.root[0][2][0].label == \"Test One\"");
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp42_);
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp40_);
#line 106 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp38_);
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp45_ = conf;
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp46_ = valadate_test_config_get_root (_tmp45_);
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp47_ = _tmp46_;
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp48_ = valadate_test_get ((ValadateTest*) _tmp47_, 0);
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp49_ = _tmp48_;
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp50_ = valadate_test_get (_tmp49_, 2);
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp51_ = _tmp50_;
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp52_ = valadate_test_get (_tmp51_, 1);
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp53_ = _tmp52_;
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp54_ = valadate_test_get_label (_tmp53_);
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp55_ = _tmp54_;
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (g_strcmp0 (_tmp55_, "Test Two") == 0, "conf.root[0][2][1].label == \"Test Two\"");
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp53_);
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp51_);
#line 107 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp49_);
#line 91 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (conf);
#line 91 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (tplan);
#line 91 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_valadate_test_options_unref0 (options);
#line 91 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (binary);
#line 91 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (builddir);
#line 1057 "testplan.c"
}


void valadate_tests_test_plan_run_single_test (void) {
	gchar* builddir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* binary = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	gchar* testpath = NULL;
	gchar* _tmp6_ = NULL;
	ValadateTestOptions* options = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar** _tmp10_ = NULL;
	gchar** _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	ValadateTestOptions* _tmp12_ = NULL;
	ValadateTestOptions* _tmp13_ = NULL;
	ValadateTestPlan* tplan = NULL;
	ValadateTestPlan* _tmp14_ = NULL;
	ValadateTestConfig* conf = NULL;
	ValadateTestPlan* _tmp15_ = NULL;
	ValadateTestConfig* _tmp16_ = NULL;
	ValadateTestConfig* _tmp17_ = NULL;
	ValadateTestConfig* _tmp18_ = NULL;
	ValadateTestConfig* _tmp19_ = NULL;
	ValadateTestSuite* _tmp20_ = NULL;
	ValadateTestSuite* _tmp21_ = NULL;
	ValadateTest* _tmp22_ = NULL;
	ValadateTest* _tmp23_ = NULL;
	ValadateTest* _tmp24_ = NULL;
	ValadateTest* _tmp25_ = NULL;
	gint _tmp26_ = 0;
	gint _tmp27_ = 0;
	ValadateTestConfig* _tmp28_ = NULL;
	ValadateTestSuite* _tmp29_ = NULL;
	ValadateTestSuite* _tmp30_ = NULL;
	ValadateTest* _tmp31_ = NULL;
	ValadateTest* _tmp32_ = NULL;
	ValadateTest* _tmp33_ = NULL;
	ValadateTest* _tmp34_ = NULL;
	gint _tmp35_ = 0;
	gint _tmp36_ = 0;
	GError * _inner_error_ = NULL;
#line 112 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp0_ = g_getenv ("G_TEST_BUILDDIR");
#line 112 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 112 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	builddir = _tmp1_;
#line 114 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp2_ = g_build_filename (builddir, "..", "data", ".libs", "testexe-0", NULL);
#line 114 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp3_ = _tmp2_;
#line 114 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp4_ = g_file_new_for_path (_tmp3_);
#line 114 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp5_ = _tmp4_;
#line 114 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (_tmp3_);
#line 114 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	binary = _tmp5_;
#line 117 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp6_ = g_strdup ("/testexe/TestsTestExe/test_simple");
#line 117 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	testpath = _tmp6_;
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp7_ = g_file_get_path (binary);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp8_ = g_strdup ("-r");
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp9_ = g_strdup (testpath);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_ = g_new0 (gchar*, 3 + 1);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_[0] = _tmp7_;
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_[1] = _tmp8_;
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp10_[2] = _tmp9_;
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11_ = _tmp10_;
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11__length1 = 3;
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp12_ = valadate_test_options_new (_tmp11_, 3, &_inner_error_);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp13_ = _tmp12_;
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp11_ = (_vala_array_free (_tmp11_, _tmp11__length1, (GDestroyNotify) g_free), NULL);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	options = _tmp13_;
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (testpath);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_object_unref0 (binary);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		_g_free0 (builddir);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		g_clear_error (&_inner_error_);
#line 119 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
		return;
#line 1169 "testplan.c"
	}
#line 121 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp14_ = valadate_test_plan_new (options);
#line 121 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	tplan = _tmp14_;
#line 123 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp15_ = tplan;
#line 123 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp16_ = valadate_test_plan_get_config (_tmp15_);
#line 123 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp17_ = _tmp16_;
#line 123 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp18_ = _g_object_ref0 (_tmp17_);
#line 123 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	conf = _tmp18_;
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp19_ = conf;
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp20_ = valadate_test_config_get_root (_tmp19_);
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp21_ = _tmp20_;
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp22_ = valadate_test_get ((ValadateTest*) _tmp21_, 0);
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp23_ = _tmp22_;
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp24_ = valadate_test_get (_tmp23_, 0);
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp25_ = _tmp24_;
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp26_ = valadate_test_get_count (_tmp25_);
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp27_ = _tmp26_;
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (_tmp27_ == 1, "conf.root[0][0].count == 1");
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp25_);
#line 125 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp23_);
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp28_ = conf;
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp29_ = valadate_test_config_get_root (_tmp28_);
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp30_ = _tmp29_;
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp31_ = valadate_test_get ((ValadateTest*) _tmp30_, 0);
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp32_ = _tmp31_;
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp33_ = valadate_test_get (_tmp32_, 1);
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp34_ = _tmp33_;
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp35_ = valadate_test_get_count (_tmp34_);
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_tmp36_ = _tmp35_;
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_vala_assert (_tmp36_ == 0, "conf.root[0][1].count == 0");
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp34_);
#line 126 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (_tmp32_);
#line 110 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (conf);
#line 110 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (tplan);
#line 110 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_valadate_test_options_unref0 (options);
#line 110 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (testpath);
#line 110 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_object_unref0 (binary);
#line 110 "/home/developer/valadate/tests/libvaladate/src/testplan.vala"
	_g_free0 (builddir);
#line 1245 "testplan.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



