/* tempdir.c generated by valac 0.30.0, the Vala compiler
 * generated from tempdir.vala, do not modify */

/*
 * Valadate - Unit testing library for GObject-based libraries.
 * Copyright (C) 2009  Jan Hudec <bulb@ucw.cz>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <sys/types.h>


#define VALADATE_TYPE_TEMP_DIR (valadate_temp_dir_get_type ())
#define VALADATE_TEMP_DIR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_TYPE_TEMP_DIR, ValadateTempDir))
#define VALADATE_TEMP_DIR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_TYPE_TEMP_DIR, ValadateTempDirClass))
#define VALADATE_IS_TEMP_DIR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_TYPE_TEMP_DIR))
#define VALADATE_IS_TEMP_DIR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_TYPE_TEMP_DIR))
#define VALADATE_TEMP_DIR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_TYPE_TEMP_DIR, ValadateTempDirClass))

typedef struct _ValadateTempDir ValadateTempDir;
typedef struct _ValadateTempDirClass ValadateTempDirClass;
typedef struct _ValadateTempDirPrivate ValadateTempDirPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_io_channel_unref0(var) ((var == NULL) ? NULL : (var = (g_io_channel_unref (var), NULL)))

struct _ValadateTempDir {
	GObject parent_instance;
	ValadateTempDirPrivate * priv;
};

struct _ValadateTempDirClass {
	GObjectClass parent_class;
};

struct _ValadateTempDirPrivate {
	GFile* _dir;
};


static gpointer valadate_temp_dir_parent_class = NULL;
static gchar* valadate_temp_dir_orig_dir;
static gchar* valadate_temp_dir_orig_dir = NULL;
static gchar* valadate_temp_dir_tmp_dir;
static gchar* valadate_temp_dir_tmp_dir = NULL;

GType valadate_temp_dir_get_type (void) G_GNUC_CONST;
#define VALADATE_TEMP_DIR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALADATE_TYPE_TEMP_DIR, ValadateTempDirPrivate))
enum  {
	VALADATE_TEMP_DIR_DUMMY_PROPERTY,
	VALADATE_TEMP_DIR_DIR,
	VALADATE_TEMP_DIR_SRC_DIR
};
void valadate_temp_dir_delete_recursive (GFile* file, GError** error);
GFile* valadate_temp_dir_get_dir (ValadateTempDir* self);
static GFile* valadate_temp_dir_make_tmp_dir (void);
gchar* valadate_temp_dir_get_orig_dir_name (ValadateTempDirClass* klass);
gchar* valadate_temp_dir_get_tmp_dir_name (ValadateTempDirClass* klass);
GFile* valadate_temp_dir_file (ValadateTempDir* self, const gchar* path);
gchar* valadate_temp_dir_contents (ValadateTempDir* self, const gchar* path);
ValadateTempDir* valadate_temp_dir_store (ValadateTempDir* self, const gchar* path, const gchar* content);
ValadateTempDir* valadate_temp_dir_copy (ValadateTempDir* self, const gchar* path, const gchar* src_path);
GFile* valadate_temp_dir_get_src_dir (ValadateTempDir* self);
static void valadate_temp_dir_do_copy (ValadateTempDir* self, GFile* dst, GFile* src, GError** error);
ValadateTempDir* valadate_temp_dir_shell (ValadateTempDir* self, const gchar* path, const gchar* code);
static gchar* valadate_temp_dir_get_random_name (void);
ValadateTempDir* valadate_temp_dir_new (void);
ValadateTempDir* valadate_temp_dir_construct (GType object_type);
static void valadate_temp_dir_finalize (GObject* obj);
static void _vala_valadate_temp_dir_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


/**
         * Returns name of the original working directory of the test
         * process.
         *
         * Or rather, name of working directory at time the type was
         * initialized.
         */
gchar* valadate_temp_dir_get_orig_dir_name (ValadateTempDirClass* klass) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 45 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = valadate_temp_dir_orig_dir;
#line 45 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 45 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp1_;
#line 45 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 115 "tempdir.c"
}


/**
         * Get name of system-wide temporary directory.
         *
         * This is just a cached value of Environment.get_tmp_dir.
         */
gchar* valadate_temp_dir_get_tmp_dir_name (ValadateTempDirClass* klass) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 54 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = valadate_temp_dir_tmp_dir;
#line 54 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 54 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp1_;
#line 54 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 136 "tempdir.c"
}


/**
         * File object for file or directory inside the test directory.
         */
GFile* valadate_temp_dir_file (ValadateTempDir* self, const gchar* path) {
	GFile* result = NULL;
	GFile* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
#line 80 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 80 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 81 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = valadate_temp_dir_get_dir (self);
#line 81 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = _tmp0_;
#line 81 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp2_ = path;
#line 81 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp3_ = g_file_resolve_relative_path (_tmp1_, _tmp2_);
#line 81 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp3_;
#line 81 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 165 "tempdir.c"
}


/**
         * Read whole content of specified file in test directory.
         *
         * Note, that it's a string, so it's nul-terminated. If the file
         * contains nul bytes, the content will be truncated there as far as
         * any string operations are concerned.
         *
         * If the file does not exist or cannot be read, aborts with fatal
         * error, failing the test it is in.
         *
         * @param path Path to be read, relative to dir.
         * @return Content of the file at path.
         */
gchar* valadate_temp_dir_contents (ValadateTempDir* self, const gchar* path) {
	gchar* result = NULL;
	gchar* str = NULL;
	GError * _inner_error_ = NULL;
#line 97 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 97 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 190 "tempdir.c"
	{
		GFileInputStream* _tmp0_ = NULL;
		const gchar* _tmp1_ = NULL;
		GFile* _tmp2_ = NULL;
		GFile* _tmp3_ = NULL;
		GFileInputStream* _tmp4_ = NULL;
		GFileInputStream* _tmp5_ = NULL;
		GDataInputStream* dins = NULL;
		GDataInputStream* _tmp6_ = NULL;
		GString* builder = NULL;
		GString* _tmp7_ = NULL;
		GString* _tmp15_ = NULL;
		const gchar* _tmp16_ = NULL;
		gchar* _tmp17_ = NULL;
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp1_ = path;
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp2_ = valadate_temp_dir_file (self, _tmp1_);
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp3_ = _tmp2_;
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp4_ = g_file_read (_tmp3_, NULL, &_inner_error_);
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp5_ = _tmp4_;
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (_tmp3_);
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp0_ = _tmp5_;
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 221 "tempdir.c"
			goto __catch1_g_error;
		}
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp6_ = g_data_input_stream_new ((GInputStream*) _tmp0_);
#line 100 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		dins = _tmp6_;
#line 101 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp7_ = g_string_new ("");
#line 101 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		builder = _tmp7_;
#line 232 "tempdir.c"
		{
			gboolean _tmp8_ = FALSE;
#line 102 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp8_ = TRUE;
#line 102 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			while (TRUE) {
#line 239 "tempdir.c"
				gchar* line = NULL;
				GDataInputStream* _tmp9_ = NULL;
				gchar* _tmp10_ = NULL;
				const gchar* _tmp11_ = NULL;
				GString* _tmp12_ = NULL;
				const gchar* _tmp13_ = NULL;
				GString* _tmp14_ = NULL;
#line 102 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				if (!_tmp8_) {
#line 249 "tempdir.c"
				}
#line 102 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_tmp8_ = FALSE;
#line 103 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_tmp9_ = dins;
#line 103 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_tmp10_ = g_data_input_stream_read_line_utf8 (_tmp9_, NULL, NULL, &_inner_error_);
#line 103 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				line = _tmp10_;
#line 103 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 103 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
					_g_string_free0 (builder);
#line 103 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
					_g_object_unref0 (dins);
#line 103 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
					_g_object_unref0 (_tmp0_);
#line 267 "tempdir.c"
					goto __catch1_g_error;
				}
#line 104 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_tmp11_ = line;
#line 104 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				if (_tmp11_ == NULL) {
#line 105 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
					_g_free0 (line);
#line 105 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
					break;
#line 278 "tempdir.c"
				}
#line 107 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_tmp12_ = builder;
#line 107 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_tmp13_ = line;
#line 107 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				g_string_append (_tmp12_, _tmp13_);
#line 108 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_tmp14_ = builder;
#line 108 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				g_string_append (_tmp14_, "\n");
#line 102 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_g_free0 (line);
#line 292 "tempdir.c"
			}
		}
#line 111 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp15_ = builder;
#line 111 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp16_ = _tmp15_->str;
#line 111 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp17_ = g_strdup (_tmp16_);
#line 111 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_free0 (str);
#line 111 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		str = _tmp17_;
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_string_free0 (builder);
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (dins);
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (_tmp0_);
#line 311 "tempdir.c"
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 113 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp18_ = path;
#line 113 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp19_ = e->message;
#line 113 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_error ("tempdir.vala:113: Failed to read content from \"%s\": %s", _tmp18_, _tmp19_);
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 331 "tempdir.c"
	}
	__finally1:
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_free0 (str);
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_clear_error (&_inner_error_);
#line 99 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return NULL;
#line 344 "tempdir.c"
	}
#line 117 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = str;
#line 117 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 350 "tempdir.c"
}


/**
         * Write content to a specified file in test directory.
         *
         * Replaces the file if it already exists. If the file cannot be
         * written, aborts with fatal error, failing the test it is in.
         *
         * @param path Path to be written, relative to dir.
         * @param content Data to write to path.
         */
static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
#line 1300 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1301 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	res = (guint8*) self;
#line 1301 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	res_length1 = -1;
#line 1301 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_res_size_ = res_length1;
#line 1302 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1302 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1302 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	res_length1 = (gint) _tmp1_;
#line 1302 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp2_ = res_length1;
#line 1303 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp3_ = res;
#line 1303 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp3__length1 = res_length1;
#line 1303 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp4_ = _tmp3_;
#line 1303 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	_tmp4__length1 = _tmp3__length1;
#line 1303 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	if (result_length1) {
#line 1303 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
		*result_length1 = _tmp4__length1;
#line 403 "tempdir.c"
	}
#line 1303 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	result = _tmp4_;
#line 1303 "/usr/share/vala-0.30/vapi/glib-2.0.vapi"
	return result;
#line 409 "tempdir.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 141 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return self ? g_object_ref (self) : NULL;
#line 416 "tempdir.c"
}


ValadateTempDir* valadate_temp_dir_store (ValadateTempDir* self, const gchar* path, const gchar* content) {
	ValadateTempDir* result = NULL;
	GFile* f = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	ValadateTempDir* _tmp11_ = NULL;
	GError * _inner_error_ = NULL;
#line 130 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 130 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 130 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (content != NULL, NULL);
#line 131 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = path;
#line 131 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = valadate_temp_dir_file (self, _tmp0_);
#line 131 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	f = _tmp1_;
#line 439 "tempdir.c"
	{
		GFile* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		guint8* _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		guint8* _tmp8_ = NULL;
		gint _tmp8__length1 = 0;
		{
			GFile* _tmp2_ = NULL;
			GFile* _tmp3_ = NULL;
			GFile* _tmp4_ = NULL;
#line 134 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp2_ = f;
#line 134 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp3_ = g_file_get_parent (_tmp2_);
#line 134 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp4_ = _tmp3_;
#line 134 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			g_file_make_directory_with_parents (_tmp4_, NULL, &_inner_error_);
#line 134 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (_tmp4_);
#line 134 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 134 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_EXISTS)) {
#line 465 "tempdir.c"
					goto __catch3_g_io_error_exists;
				}
				goto __finally3;
			}
		}
		goto __finally3;
		__catch3_g_io_error_exists:
		{
			GError* e = NULL;
#line 133 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			e = _inner_error_;
#line 133 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_inner_error_ = NULL;
#line 133 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_error_free0 (e);
#line 481 "tempdir.c"
		}
		__finally3:
#line 133 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 486 "tempdir.c"
			goto __catch2_g_error;
		}
#line 136 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp5_ = f;
#line 136 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp6_ = content;
#line 136 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp7_ = string_get_data (_tmp6_, &_tmp7__length1);
#line 136 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp8_ = _tmp7_;
#line 136 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp8__length1 = _tmp7__length1;
#line 136 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_file_replace_contents (_tmp5_, _tmp8_, (gsize) _tmp8__length1, NULL, FALSE, G_FILE_CREATE_REPLACE_DESTINATION, NULL, NULL, &_inner_error_);
#line 136 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 503 "tempdir.c"
			goto __catch2_g_error;
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
#line 132 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 132 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 139 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp9_ = path;
#line 139 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp10_ = e->message;
#line 139 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_error ("tempdir.vala:139: Failed to write to \"%s\": %s", _tmp9_, _tmp10_);
#line 132 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 525 "tempdir.c"
	}
	__finally2:
#line 132 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 132 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (f);
#line 132 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 132 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_clear_error (&_inner_error_);
#line 132 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return NULL;
#line 538 "tempdir.c"
	}
#line 141 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp11_ = _g_object_ref0 (self);
#line 141 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp11_;
#line 141 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_g_object_unref0 (f);
#line 141 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 548 "tempdir.c"
}


/**
         * Copy file or directory from original working dir to test dir.
         *
         * Copies recursively the tree at src_path to path. The content of
         * src_path is placed directly into path (i.e. no subdirectory is
         * created if path exists unlike cp command). If the file or tree
         * cannot be copied, aborts with fatal error, failing the test it is
         * in.
         *
         * @param path Destination path, relative to dir.
         * @param src_path Source path, relative to src_dir (or absolute).
         */
ValadateTempDir* valadate_temp_dir_copy (ValadateTempDir* self, const gchar* path, const gchar* src_path) {
	ValadateTempDir* result = NULL;
	GFile* dst = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	ValadateTempDir* _tmp16_ = NULL;
	GError * _inner_error_ = NULL;
#line 156 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 156 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 156 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (src_path != NULL, NULL);
#line 157 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = path;
#line 157 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = valadate_temp_dir_file (self, _tmp0_);
#line 157 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	dst = _tmp1_;
#line 583 "tempdir.c"
	{
		GFile* src = NULL;
		GFile* _tmp5_ = NULL;
		GFile* _tmp6_ = NULL;
		GFile* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		GFile* _tmp9_ = NULL;
		GFile* _tmp10_ = NULL;
		GFile* _tmp11_ = NULL;
		GFile* _tmp12_ = NULL;
		{
			GFile* _tmp2_ = NULL;
			GFile* _tmp3_ = NULL;
			GFile* _tmp4_ = NULL;
#line 160 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp2_ = dst;
#line 160 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp3_ = g_file_get_parent (_tmp2_);
#line 160 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp4_ = _tmp3_;
#line 160 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			g_file_make_directory_with_parents (_tmp4_, NULL, &_inner_error_);
#line 160 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (_tmp4_);
#line 160 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 160 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_EXISTS)) {
#line 612 "tempdir.c"
					goto __catch5_g_io_error_exists;
				}
				goto __finally5;
			}
		}
		goto __finally5;
		__catch5_g_io_error_exists:
		{
			GError* e = NULL;
#line 159 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			e = _inner_error_;
#line 159 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_inner_error_ = NULL;
#line 159 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_error_free0 (e);
#line 628 "tempdir.c"
		}
		__finally5:
#line 159 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 633 "tempdir.c"
			goto __catch4_g_error;
		}
#line 162 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp5_ = valadate_temp_dir_get_src_dir (self);
#line 162 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp6_ = _tmp5_;
#line 162 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp7_ = _tmp6_;
#line 162 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp8_ = src_path;
#line 162 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp9_ = g_file_resolve_relative_path (_tmp7_, _tmp8_);
#line 162 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp10_ = _tmp9_;
#line 162 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (_tmp7_);
#line 162 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		src = _tmp10_;
#line 163 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp11_ = dst;
#line 163 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp12_ = src;
#line 163 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		valadate_temp_dir_do_copy (self, _tmp11_, _tmp12_, &_inner_error_);
#line 163 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 163 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (src);
#line 662 "tempdir.c"
			goto __catch4_g_error;
		}
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (src);
#line 667 "tempdir.c"
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp13_ = NULL;
		const gchar* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 165 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp13_ = src_path;
#line 165 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp14_ = path;
#line 165 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp15_ = e->message;
#line 165 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_error ("tempdir.vala:165: Failed to copy \"%s\" to \"%s\": %s", _tmp13_, _tmp14_, _tmp15_);
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 690 "tempdir.c"
	}
	__finally4:
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (dst);
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_clear_error (&_inner_error_);
#line 158 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return NULL;
#line 703 "tempdir.c"
	}
#line 168 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp16_ = _g_object_ref0 (self);
#line 168 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp16_;
#line 168 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_g_object_unref0 (dst);
#line 168 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 713 "tempdir.c"
}


/**
         * Execute shell code in context of the test dir.
         *
         * Executes code, via {{{/bin/sh}}}, in a specified subdirectory of
         * the test directory. If shell cannot be executed or the script
         * exits with nonzero status, aborts with fatal error, failing the
         * test.
         *
         * @param path Working directory for the script, relative to dir. It
         *        is created if it did not exist.
         * @param code Shell code that will be piped to standard input of
         *        {{{/bin/sh}}}.
         */
ValadateTempDir* valadate_temp_dir_shell (ValadateTempDir* self, const gchar* path, const gchar* code) {
	ValadateTempDir* result = NULL;
	GFile* test_dir = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	ValadateTempDir* _tmp29_ = NULL;
	GError * _inner_error_ = NULL;
#line 184 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 184 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 184 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (code != NULL, NULL);
#line 185 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = path;
#line 185 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = valadate_temp_dir_file (self, _tmp0_);
#line 185 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	test_dir = _tmp1_;
#line 749 "tempdir.c"
	{
		GFile* _tmp2_ = NULL;
#line 187 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp2_ = test_dir;
#line 187 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_file_make_directory_with_parents (_tmp2_, NULL, &_inner_error_);
#line 187 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 758 "tempdir.c"
			goto __catch6_g_error;
		}
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
#line 186 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 186 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 186 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 772 "tempdir.c"
	}
	__finally6:
#line 186 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 186 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (test_dir);
#line 186 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 186 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_clear_error (&_inner_error_);
#line 186 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return NULL;
#line 785 "tempdir.c"
	}
	{
		GFile* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		GPid pid = 0;
		gint in_handle = 0;
		GFile* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar** _tmp13_ = NULL;
		gchar** _tmp14_ = NULL;
		gint _tmp14__length1 = 0;
		GPid _tmp15_ = 0;
		gint _tmp16_ = 0;
		GIOChannel* in_ch = NULL;
		gint _tmp17_ = 0;
		GIOChannel* _tmp18_ = NULL;
		GIOStatus status = 0;
		GIOChannel* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		GIOStatus _tmp21_ = 0;
		GIOStatus _tmp22_ = 0;
		GIOChannel* _tmp24_ = NULL;
		gint exitcode = 0;
		GPid _tmp25_ = 0;
		gint _tmp26_ = 0;
#line 190 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp3_ = test_dir;
#line 190 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp4_ = g_file_get_path (_tmp3_);
#line 190 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp5_ = _tmp4_;
#line 190 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_setenv ("testdir", _tmp5_, TRUE);
#line 190 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_free0 (_tmp5_);
#line 191 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp6_ = valadate_temp_dir_get_orig_dir_name (VALADATE_TEMP_DIR_CLASS (G_OBJECT_GET_CLASS (self)));
#line 191 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp7_ = _tmp6_;
#line 191 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_setenv ("srcdir", _tmp7_, TRUE);
#line 191 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_free0 (_tmp7_);
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp8_ = test_dir;
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp9_ = g_file_get_path (_tmp8_);
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp10_ = _tmp9_;
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp11_ = g_strdup ("/bin/sh");
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp12_ = g_strdup ("-");
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp13_ = g_new0 (gchar*, 2 + 1);
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp13_[0] = _tmp11_;
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp13_[1] = _tmp12_;
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp14_ = _tmp13_;
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp14__length1 = 2;
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_spawn_async_with_pipes (_tmp10_, _tmp14_, NULL, G_SPAWN_DO_NOT_REAP_CHILD, NULL, NULL, &_tmp15_, &_tmp16_, NULL, NULL, &_inner_error_);
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		pid = _tmp15_;
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		in_handle = _tmp16_;
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp14_ = (_vala_array_free (_tmp14_, _tmp14__length1, (GDestroyNotify) g_free), NULL);
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_free0 (_tmp10_);
#line 194 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 867 "tempdir.c"
			goto __catch7_g_error;
		}
#line 204 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp17_ = in_handle;
#line 204 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp18_ = g_io_channel_unix_new (_tmp17_);
#line 204 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		in_ch = _tmp18_;
#line 205 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp19_ = in_ch;
#line 205 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp20_ = code;
#line 205 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp21_ = g_io_channel_write_chars (_tmp19_, (gchar*) _tmp20_, -1, NULL, &_inner_error_);
#line 205 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		status = _tmp21_;
#line 205 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 205 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_io_channel_unref0 (in_ch);
#line 888 "tempdir.c"
			goto __catch7_g_error;
		}
#line 206 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp22_ = status;
#line 206 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (_tmp22_ != G_IO_STATUS_NORMAL) {
#line 895 "tempdir.c"
			GIOStatus _tmp23_ = 0;
#line 207 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp23_ = status;
#line 207 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			g_error ("tempdir.vala:207: Sending data to shell failed, status: %i", (gint) _tmp23_);
#line 901 "tempdir.c"
		}
#line 209 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp24_ = in_ch;
#line 209 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_io_channel_shutdown (_tmp24_, TRUE, &_inner_error_);
#line 209 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 209 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_io_channel_unref0 (in_ch);
#line 911 "tempdir.c"
			goto __catch7_g_error;
		}
#line 211 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp25_ = pid;
#line 211 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		waitpid ((pid_t) _tmp25_, &_tmp26_, 0);
#line 211 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		exitcode = _tmp26_;
#line 212 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (exitcode != 0) {
#line 213 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			g_error ("tempdir.vala:213: Shell script failed with status: %i", exitcode);
#line 924 "tempdir.c"
		}
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_io_channel_unref0 (in_ch);
#line 928 "tempdir.c"
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp27_ = NULL;
		const gchar* _tmp28_ = NULL;
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 215 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp27_ = path;
#line 215 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp28_ = e->message;
#line 215 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_error ("tempdir.vala:215: Error while trying to run shell snippet in %s: %s", _tmp27_, _tmp28_);
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 948 "tempdir.c"
	}
	__finally7:
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (test_dir);
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_clear_error (&_inner_error_);
#line 189 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return NULL;
#line 961 "tempdir.c"
	}
#line 218 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp29_ = _g_object_ref0 (self);
#line 218 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp29_;
#line 218 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_g_object_unref0 (test_dir);
#line 218 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 971 "tempdir.c"
}


/**
         * Deletes a file or directory, recursively.
         *
         * This is used to clean up the test directory after the test
         * completes.
         */
void valadate_temp_dir_delete_recursive (GFile* file, GError** error) {
	GFile* _tmp13_ = NULL;
	GError * _inner_error_ = NULL;
#line 228 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_if_fail (file != NULL);
#line 986 "tempdir.c"
	{
		GFileEnumerator* i = NULL;
		GFile* _tmp0_ = NULL;
		GFileEnumerator* _tmp1_ = NULL;
		GFileInfo* e = NULL;
		GFileEnumerator* _tmp12_ = NULL;
#line 230 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp0_ = file;
#line 230 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp1_ = g_file_enumerate_children (_tmp0_, "standard::name", G_FILE_QUERY_INFO_NOFOLLOW_SYMLINKS, NULL, &_inner_error_);
#line 230 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		i = _tmp1_;
#line 230 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 230 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_NOT_DIRECTORY)) {
#line 1003 "tempdir.c"
				goto __catch8_g_io_error_not_directory;
			}
			goto __finally8;
		}
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		while (TRUE) {
#line 1010 "tempdir.c"
			GFileInfo* _tmp2_ = NULL;
			GFileEnumerator* _tmp3_ = NULL;
			GFileInfo* _tmp4_ = NULL;
			GFileInfo* _tmp5_ = NULL;
			GFileInfo* _tmp6_ = NULL;
			GFile* _tmp7_ = NULL;
			GFileInfo* _tmp8_ = NULL;
			const gchar* _tmp9_ = NULL;
			GFile* _tmp10_ = NULL;
			GFile* _tmp11_ = NULL;
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp3_ = i;
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp4_ = g_file_enumerator_next_file (_tmp3_, NULL, &_inner_error_);
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp2_ = _tmp4_;
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_g_object_unref0 (e);
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_g_object_unref0 (i);
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_NOT_DIRECTORY)) {
#line 1035 "tempdir.c"
					goto __catch8_g_io_error_not_directory;
				}
				goto __finally8;
			}
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp5_ = _tmp2_;
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp2_ = NULL;
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (e);
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			e = _tmp5_;
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp6_ = e;
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (!(_tmp6_ != NULL)) {
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_g_object_unref0 (_tmp2_);
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				break;
#line 1056 "tempdir.c"
			}
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp7_ = file;
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp8_ = e;
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp9_ = g_file_info_get_name (_tmp8_);
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp10_ = g_file_get_child (_tmp7_, _tmp9_);
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp11_ = _tmp10_;
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			valadate_temp_dir_delete_recursive (_tmp11_, &_inner_error_);
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (_tmp11_);
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_g_object_unref0 (_tmp2_);
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_g_object_unref0 (e);
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				_g_object_unref0 (i);
#line 235 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_NOT_DIRECTORY)) {
#line 1082 "tempdir.c"
					goto __catch8_g_io_error_not_directory;
				}
				goto __finally8;
			}
#line 234 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (_tmp2_);
#line 1089 "tempdir.c"
		}
#line 237 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp12_ = i;
#line 237 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_file_enumerator_close (_tmp12_, NULL, &_inner_error_);
#line 237 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 237 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (e);
#line 237 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (i);
#line 237 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_NOT_DIRECTORY)) {
#line 1103 "tempdir.c"
				goto __catch8_g_io_error_not_directory;
			}
			goto __finally8;
		}
#line 229 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (e);
#line 229 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (i);
#line 1112 "tempdir.c"
	}
	goto __finally8;
	__catch8_g_io_error_not_directory:
	{
		GError* e = NULL;
#line 229 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 229 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 229 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 1124 "tempdir.c"
	}
	__finally8:
#line 229 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 229 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_propagate_error (error, _inner_error_);
#line 229 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return;
#line 1133 "tempdir.c"
	}
#line 239 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp13_ = file;
#line 239 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_file_delete (_tmp13_, NULL, &_inner_error_);
#line 239 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 239 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_propagate_error (error, _inner_error_);
#line 239 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return;
#line 1145 "tempdir.c"
	}
}


static gchar* valadate_temp_dir_get_random_name (void) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	guint32 _tmp1_ = 0U;
	gchar* _tmp2_ = NULL;
#line 252 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = valadate_temp_dir_tmp_dir;
#line 252 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = g_random_int ();
#line 252 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp2_ = g_strdup_printf ("%s%cvaladate-%08X", _tmp0_, (gint) G_DIR_SEPARATOR, (guint) _tmp1_);
#line 252 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp2_;
#line 252 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 1165 "tempdir.c"
}


static GFile* valadate_temp_dir_make_tmp_dir (void) {
	GFile* result = NULL;
	GFile* dir = NULL;
	GError * _inner_error_ = NULL;
#line 260 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	while (TRUE) {
#line 1175 "tempdir.c"
		{
			gchar* _tmp0_ = NULL;
			gchar* _tmp1_ = NULL;
			GFile* _tmp2_ = NULL;
			GFile* _tmp3_ = NULL;
#line 262 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp0_ = valadate_temp_dir_get_random_name ();
#line 262 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp1_ = _tmp0_;
#line 262 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp2_ = g_file_new_for_path (_tmp1_);
#line 262 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (dir);
#line 262 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			dir = _tmp2_;
#line 262 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_free0 (_tmp1_);
#line 263 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp3_ = dir;
#line 263 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			g_file_make_directory (_tmp3_, NULL, &_inner_error_);
#line 263 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 263 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
				if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_EXISTS)) {
#line 1201 "tempdir.c"
					goto __catch9_g_io_error_exists;
				}
				goto __catch9_g_error;
			}
#line 264 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			result = dir;
#line 264 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			return result;
#line 1210 "tempdir.c"
		}
		goto __finally9;
		__catch9_g_io_error_exists:
		{
			GError* e = NULL;
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			e = _inner_error_;
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_inner_error_ = NULL;
#line 266 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_error_free0 (e);
#line 266 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			continue;
#line 1224 "tempdir.c"
		}
		goto __finally9;
		__catch9_g_error:
		{
			GError* e = NULL;
			const gchar* _tmp4_ = NULL;
			const gchar* _tmp5_ = NULL;
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			e = _inner_error_;
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_inner_error_ = NULL;
#line 268 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp4_ = valadate_temp_dir_tmp_dir;
#line 268 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_tmp5_ = e->message;
#line 268 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			g_error ("tempdir.vala:268: Cannot create temporary directory in %s: %s", _tmp4_, _tmp5_);
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_error_free0 (e);
#line 1244 "tempdir.c"
		}
		__finally9:
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (dir);
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_clear_error (&_inner_error_);
#line 261 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return NULL;
#line 1255 "tempdir.c"
	}
#line 258 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_g_object_unref0 (dir);
#line 1259 "tempdir.c"
}


static void valadate_temp_dir_do_copy (ValadateTempDir* self, GFile* dst, GFile* src, GError** error) {
	GFileEnumerator* i = NULL;
	GFileInfo* e = NULL;
	GFileEnumerator* _tmp22_ = NULL;
	GError * _inner_error_ = NULL;
#line 274 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_if_fail (self != NULL);
#line 274 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_if_fail (dst != NULL);
#line 274 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_if_fail (src != NULL);
#line 275 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	i = NULL;
#line 1276 "tempdir.c"
	{
		GFileEnumerator* _tmp0_ = NULL;
		GFile* _tmp1_ = NULL;
		GFileEnumerator* _tmp2_ = NULL;
		GFileEnumerator* _tmp3_ = NULL;
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp1_ = src;
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp2_ = g_file_enumerate_children (_tmp1_, "standard::name", G_FILE_QUERY_INFO_NOFOLLOW_SYMLINKS, NULL, &_inner_error_);
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp0_ = _tmp2_;
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_NOT_DIRECTORY)) {
#line 1292 "tempdir.c"
				goto __catch10_g_io_error_not_directory;
			}
			goto __finally10;
		}
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp3_ = _tmp0_;
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp0_ = NULL;
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (i);
#line 277 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		i = _tmp3_;
#line 276 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (_tmp0_);
#line 1307 "tempdir.c"
	}
	goto __finally10;
	__catch10_g_io_error_not_directory:
	{
		GError* e = NULL;
		GFile* _tmp4_ = NULL;
		GFile* _tmp5_ = NULL;
#line 276 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 276 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 281 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp4_ = src;
#line 281 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp5_ = dst;
#line 281 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_file_copy (_tmp4_, _tmp5_, G_FILE_COPY_OVERWRITE, NULL, NULL, NULL, &_inner_error_);
#line 281 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 281 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_error_free0 (e);
#line 1329 "tempdir.c"
			goto __finally10;
		}
#line 282 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 282 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (i);
#line 282 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return;
#line 1338 "tempdir.c"
	}
	__finally10:
#line 276 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 276 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_propagate_error (error, _inner_error_);
#line 276 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (i);
#line 276 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return;
#line 1349 "tempdir.c"
	}
	{
		GFile* _tmp6_ = NULL;
#line 286 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp6_ = dst;
#line 286 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_file_make_directory (_tmp6_, NULL, &_inner_error_);
#line 286 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 286 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			if (g_error_matches (_inner_error_, G_IO_ERROR, G_IO_ERROR_EXISTS)) {
#line 1361 "tempdir.c"
				goto __catch11_g_io_error_exists;
			}
			goto __finally11;
		}
	}
	goto __finally11;
	__catch11_g_io_error_exists:
	{
		GError* e = NULL;
#line 285 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 285 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 285 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 1377 "tempdir.c"
	}
	__finally11:
#line 285 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 285 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_propagate_error (error, _inner_error_);
#line 285 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (i);
#line 285 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return;
#line 1388 "tempdir.c"
	}
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	while (TRUE) {
#line 1392 "tempdir.c"
		GFileInfo* _tmp7_ = NULL;
		GFileEnumerator* _tmp8_ = NULL;
		GFileInfo* _tmp9_ = NULL;
		GFileInfo* _tmp10_ = NULL;
		GFileInfo* _tmp11_ = NULL;
		GFile* _tmp12_ = NULL;
		GFileInfo* _tmp13_ = NULL;
		const gchar* _tmp14_ = NULL;
		GFile* _tmp15_ = NULL;
		GFile* _tmp16_ = NULL;
		GFile* _tmp17_ = NULL;
		GFileInfo* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		GFile* _tmp20_ = NULL;
		GFile* _tmp21_ = NULL;
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp8_ = i;
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp9_ = g_file_enumerator_next_file (_tmp8_, NULL, &_inner_error_);
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp7_ = _tmp9_;
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			g_propagate_error (error, _inner_error_);
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (e);
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (i);
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			return;
#line 1424 "tempdir.c"
		}
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp10_ = _tmp7_;
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp7_ = NULL;
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (e);
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _tmp10_;
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp11_ = e;
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (!(_tmp11_ != NULL)) {
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (_tmp7_);
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			break;
#line 1442 "tempdir.c"
		}
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp12_ = dst;
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp13_ = e;
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp14_ = g_file_info_get_name (_tmp13_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp15_ = g_file_get_child (_tmp12_, _tmp14_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp16_ = _tmp15_;
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp17_ = src;
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp18_ = e;
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp19_ = g_file_info_get_name (_tmp18_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp20_ = g_file_get_child (_tmp17_, _tmp19_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp21_ = _tmp20_;
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		valadate_temp_dir_do_copy (self, _tmp16_, _tmp21_, &_inner_error_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (_tmp21_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (_tmp16_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			g_propagate_error (error, _inner_error_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (_tmp7_);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (e);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			_g_object_unref0 (i);
#line 290 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
			return;
#line 1482 "tempdir.c"
		}
#line 289 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (_tmp7_);
#line 1486 "tempdir.c"
	}
#line 293 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp22_ = i;
#line 293 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_file_enumerator_close (_tmp22_, NULL, &_inner_error_);
#line 293 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 293 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_propagate_error (error, _inner_error_);
#line 293 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (e);
#line 293 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_object_unref0 (i);
#line 293 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		return;
#line 1502 "tempdir.c"
	}
#line 274 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_g_object_unref0 (e);
#line 274 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_g_object_unref0 (i);
#line 1508 "tempdir.c"
}


ValadateTempDir* valadate_temp_dir_construct (GType object_type) {
	ValadateTempDir * self = NULL;
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	self = (ValadateTempDir*) g_object_new (object_type, NULL);
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return self;
#line 1518 "tempdir.c"
}


ValadateTempDir* valadate_temp_dir_new (void) {
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return valadate_temp_dir_construct (VALADATE_TYPE_TEMP_DIR);
#line 1525 "tempdir.c"
}


GFile* valadate_temp_dir_get_dir (ValadateTempDir* self) {
	GFile* result;
	GFile* _tmp0_ = NULL;
#line 65 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 65 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = self->priv->_dir;
#line 65 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp0_;
#line 65 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 1540 "tempdir.c"
}


GFile* valadate_temp_dir_get_src_dir (ValadateTempDir* self) {
	GFile* result;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
#line 74 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 74 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = valadate_temp_dir_orig_dir;
#line 74 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = g_file_new_for_path (_tmp0_);
#line 74 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	result = _tmp1_;
#line 74 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	return result;
#line 1558 "tempdir.c"
}


static void valadate_temp_dir_class_init (ValadateTempDirClass * klass) {
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	valadate_temp_dir_parent_class = g_type_class_peek_parent (klass);
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_type_class_add_private (klass, sizeof (ValadateTempDirPrivate));
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_valadate_temp_dir_get_property;
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	G_OBJECT_CLASS (klass)->finalize = valadate_temp_dir_finalize;
#line 1574 "tempdir.c"
	/**
	         * The test directory.
	         *
	         * A GLib.File object representing the test directory.
	         */
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALADATE_TEMP_DIR_DIR, g_param_spec_object ("dir", "dir", "dir", G_TYPE_FILE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 1582 "tempdir.c"
	/**
	         * The original working directory.
	         *
	         * The working directory in which the tests were started (again,
	         * obtained when the type is initialized, so it might get changed
	         * before that).
	         */
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALADATE_TEMP_DIR_SRC_DIR, g_param_spec_object ("src-dir", "src-dir", "src-dir", G_TYPE_FILE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 34 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = g_get_current_dir ();
#line 34 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	valadate_temp_dir_orig_dir = _tmp0_;
#line 35 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp1_ = g_get_tmp_dir ();
#line 35 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 35 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	valadate_temp_dir_tmp_dir = _tmp2_;
#line 1602 "tempdir.c"
}


static void valadate_temp_dir_instance_init (ValadateTempDir * self) {
	GFile* _tmp0_ = NULL;
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	self->priv = VALADATE_TEMP_DIR_GET_PRIVATE (self);
#line 58 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_tmp0_ = valadate_temp_dir_make_tmp_dir ();
#line 58 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	self->priv->_dir = _tmp0_;
#line 1614 "tempdir.c"
}


static void valadate_temp_dir_finalize (GObject* obj) {
	ValadateTempDir * self;
	GError * _inner_error_ = NULL;
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALADATE_TYPE_TEMP_DIR, ValadateTempDir);
#line 1623 "tempdir.c"
	{
		GFile* _tmp0_ = NULL;
		GFile* _tmp1_ = NULL;
#line 244 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp0_ = valadate_temp_dir_get_dir (self);
#line 244 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp1_ = _tmp0_;
#line 244 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		valadate_temp_dir_delete_recursive (_tmp1_, &_inner_error_);
#line 244 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1635 "tempdir.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GFile* _tmp2_ = NULL;
		GFile* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
#line 243 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		e = _inner_error_;
#line 243 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_inner_error_ = NULL;
#line 246 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp2_ = valadate_temp_dir_get_dir (self);
#line 246 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp3_ = _tmp2_;
#line 246 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp4_ = g_file_get_path (_tmp3_);
#line 246 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp5_ = _tmp4_;
#line 246 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp6_ = e;
#line 246 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_tmp7_ = _tmp6_->message;
#line 246 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_critical ("tempdir.vala:246: Could not remove temp dir %s: %s", _tmp5_, _tmp7_);
#line 246 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_free0 (_tmp5_);
#line 243 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		_g_error_free0 (e);
#line 1671 "tempdir.c"
	}
	__finally0:
#line 243 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 243 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 243 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_clear_error (&_inner_error_);
#line 1680 "tempdir.c"
	}
#line 58 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	_g_object_unref0 (self->priv->_dir);
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	G_OBJECT_CLASS (valadate_temp_dir_parent_class)->finalize (obj);
#line 1686 "tempdir.c"
}


/**
     * Class to provide a temporary test directory to unit tests.
     *
     * To use, instantiate this class either inside your test method or as
     * a member of your test fixture. I will automatically create a test
     * directory upon instantiation and remove it again upon destruction.
     *
     * With the current GLib.Test-based runner, the destruction will not run
     * if the test fails, so the directory is not deleted if the test fails.
     * (it is not currently printed anywhere though).
     */
GType valadate_temp_dir_get_type (void) {
	static volatile gsize valadate_temp_dir_type_id__volatile = 0;
	if (g_once_init_enter (&valadate_temp_dir_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValadateTempDirClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valadate_temp_dir_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValadateTempDir), 0, (GInstanceInitFunc) valadate_temp_dir_instance_init, NULL };
		GType valadate_temp_dir_type_id;
		valadate_temp_dir_type_id = g_type_register_static (G_TYPE_OBJECT, "ValadateTempDir", &g_define_type_info, 0);
		g_once_init_leave (&valadate_temp_dir_type_id__volatile, valadate_temp_dir_type_id);
	}
	return valadate_temp_dir_type_id__volatile;
}


static void _vala_valadate_temp_dir_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ValadateTempDir * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALADATE_TYPE_TEMP_DIR, ValadateTempDir);
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
	switch (property_id) {
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		case VALADATE_TEMP_DIR_DIR:
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_value_set_object (value, valadate_temp_dir_get_dir (self));
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		break;
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		case VALADATE_TEMP_DIR_SRC_DIR:
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		g_value_take_object (value, valadate_temp_dir_get_src_dir (self));
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		break;
#line 1730 "tempdir.c"
		default:
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 32 "/home/bizarro/Documents/projects/valadate/lib/tempdir.vala"
		break;
#line 1736 "tempdir.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



