def build(bld):
    bld.shlib(source=bld.path.ant_glob('*.vala'),
              target='valadate-%(API_VER)s' % bld.env,
              gir='Valadate-%(API_VER)s' % bld.env,
              packages='glib-2.0 gobject-2.0 gio-2.0 posix',
              uselib='glib-2.0 gobject-2.0 gio-2.0',
              cflags=['-ggdb'],
              vnum=bld.env.SO_VER)

