def build(bld):
    lib = bld.new_task_gen(
            features='cc cshlib',
            target='valadate-0.0',
            gir='Valadate-0.0',
            packages='glib-2.0 gio-2.0',
            uselib='glib-2.0 gio-2.0',
            ccflags=['-ggdb'],
            vnum='0.0')
    lib.find_sources_in_dirs('.')
# vim: set ft=python sw=4 sts=4 et:
