# The base dockerfile can be found in the valadate/jenkins-server repository
FROM jenkins/ubuntu:15.04
MAINTAINER Chris Daley <chebizarro@gmail.com>

RUN apt-get install -y gobject-introspection libvala-0.30-dev libgirepository1.0-dev
