Document: valadate
Title: Debian valadate Manual
Author: <insert document author here>
Abstract: This manual describes what valadate is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/valadate/valadate.sgml.gz

Format: postscript
Files: /usr/share/doc/valadate/valadate.ps.gz

Format: text
Files: /usr/share/doc/valadate/valadate.text.gz

Format: HTML
Index: /usr/share/doc/valadate/html/index.html
Files: /usr/share/doc/valadate/html/*.html
