/* Tests.vapi generated by valac 0.34.7, do not modify. */

[CCode (gir_namespace = "Valadate", gir_version = "1.0")]
namespace Valadate {
	namespace Tests {
		[CCode (cheader_filename = "testexe.h")]
		public abstract class TestAbstractClass : Valadate.TestCase {
			public TestAbstractClass ();
			public abstract void test_abstract_method ();
			public void test_method ();
			public virtual void test_virtual_method ();
			public virtual void test_virtual_method_two ();
		}
		[CCode (cheader_filename = "testexe.h")]
		public class TestExe : Valadate.TestCase {
			public TestExe ();
			public void _test_simple_skip ();
			[Test (name = "Annotated Test With Name")]
			public void annotated_test_with_name ();
			[Test (skip = "yes")]
			public void skip_test ();
			[Test (name = "Asynchronous Test", timeout = 1000)]
			public async void test_async () throws GLib.ThreadError;
			public void test_simple ();
			public void test_throws_error () throws GLib.Error;
		}
		[CCode (cheader_filename = "testexe.h")]
		public class TestExeAbstractImpl : Valadate.Tests.TestAbstractClass {
			public TestExeAbstractImpl ();
			public override void test_abstract_method ();
			public override void test_virtual_method_two ();
		}
		[CCode (cheader_filename = "testexe.h")]
		[Test (name = "Annotated Test Class With Name")]
		public class TestExeSubClass : Valadate.Tests.TestExe {
			public TestExeSubClass ();
			public void test_method ();
		}
		[CCode (cheader_filename = "testexe.h")]
		public class TestExeTwo : Valadate.TestCase {
			public TestExeTwo ();
			[Test (name = "Test Async with Timeout", timeout = "200")]
			public async void test_async_with_timeout () throws GLib.Error, Valadate.AssertError;
			[Test (name = "Test One")]
			public void test_one ();
			[Test (name = "Test Two")]
			public void test_two ();
		}
	}
}
