/* girreader.c generated by valac 0.30.0, the Vala compiler
 * generated from girreader.vala, do not modify */

/*
 * Valadate - Unit testing library for GObject-based libraries.
 * Copyright (C) 2009  Jan Hudec <bulb@ucw.cz>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <girepository-fixes.h>
#include <stdio.h>
#include <sys/stat.h>
#include <errno.h>


#define VALADATE_RUNNER_TYPE_READER (valadate_runner_reader_get_type ())
#define VALADATE_RUNNER_READER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_READER, ValadateRunnerReader))
#define VALADATE_RUNNER_IS_READER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_READER))
#define VALADATE_RUNNER_READER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), VALADATE_RUNNER_TYPE_READER, ValadateRunnerReaderIface))

typedef struct _ValadateRunnerReader ValadateRunnerReader;
typedef struct _ValadateRunnerReaderIface ValadateRunnerReaderIface;

#define VALADATE_RUNNER_TYPE_GIR_READER (valadate_runner_gir_reader_get_type ())
#define VALADATE_RUNNER_GIR_READER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_GIR_READER, ValadateRunnerGirReader))
#define VALADATE_RUNNER_GIR_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_GIR_READER, ValadateRunnerGirReaderClass))
#define VALADATE_RUNNER_IS_GIR_READER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_GIR_READER))
#define VALADATE_RUNNER_IS_GIR_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_GIR_READER))
#define VALADATE_RUNNER_GIR_READER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_GIR_READER, ValadateRunnerGirReaderClass))

typedef struct _ValadateRunnerGirReader ValadateRunnerGirReader;
typedef struct _ValadateRunnerGirReaderClass ValadateRunnerGirReaderClass;
typedef struct _ValadateRunnerGirReaderPrivate ValadateRunnerGirReaderPrivate;

#define VALADATE_RUNNER_TYPE_SUITE_INFO (valadate_runner_suite_info_get_type ())
#define VALADATE_RUNNER_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfo))
#define VALADATE_RUNNER_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoClass))
#define VALADATE_RUNNER_IS_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO))
#define VALADATE_RUNNER_IS_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_SUITE_INFO))
#define VALADATE_RUNNER_SUITE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoClass))

typedef struct _ValadateRunnerSuiteInfo ValadateRunnerSuiteInfo;
typedef struct _ValadateRunnerSuiteInfoClass ValadateRunnerSuiteInfoClass;

#define VALADATE_RUNNER_TYPE_GIR_SUITE_INFO (valadate_runner_gir_suite_info_get_type ())
#define VALADATE_RUNNER_GIR_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, ValadateRunnerGirSuiteInfo))
#define VALADATE_RUNNER_GIR_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, ValadateRunnerGirSuiteInfoClass))
#define VALADATE_RUNNER_IS_GIR_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO))
#define VALADATE_RUNNER_IS_GIR_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO))
#define VALADATE_RUNNER_GIR_SUITE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, ValadateRunnerGirSuiteInfoClass))

typedef struct _ValadateRunnerGirSuiteInfo ValadateRunnerGirSuiteInfo;
typedef struct _ValadateRunnerGirSuiteInfoClass ValadateRunnerGirSuiteInfoClass;
#define __g_slist_free__g_typelib_free0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__g_typelib_free0_ (var), NULL)))
#define __g_slist_free__valadate_runner_suite_info_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__valadate_runner_suite_info_unref0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_mapped_file_unref0(var) ((var == NULL) ? NULL : (var = (g_mapped_file_unref (var), NULL)))
#define _g_typelib_free0(var) ((var == NULL) ? NULL : (var = (g_typelib_free (var), NULL)))
#define _g_base_info_unref0(var) ((var == NULL) ? NULL : (var = (g_base_info_unref (var), NULL)))
#define _valadate_runner_suite_info_unref0(var) ((var == NULL) ? NULL : (var = (valadate_runner_suite_info_unref (var), NULL)))

struct _ValadateRunnerReaderIface {
	GTypeInterface parent_iface;
	gboolean (*process_file) (ValadateRunnerReader* self, const gchar* file, GError** error);
	void (*gather_tests) (ValadateRunnerReader* self, GError** error);
};

struct _ValadateRunnerGirReader {
	GObject parent_instance;
	ValadateRunnerGirReaderPrivate * priv;
};

struct _ValadateRunnerGirReaderClass {
	GObjectClass parent_class;
};

struct _ValadateRunnerGirReaderPrivate {
	GSList* typelibs;
	GSList* suites;
};

typedef enum  {
	VALADATE_RUNNER_RUNNER_ERROR_UNRECOGNIZED_FILE,
	VALADATE_RUNNER_RUNNER_ERROR_CANNOT_READ,
	VALADATE_RUNNER_RUNNER_ERROR_COMPILATION_FAILED,
	VALADATE_RUNNER_RUNNER_ERROR_TYPE_NOT_LOADED,
	VALADATE_RUNNER_RUNNER_ERROR_NOT_FOUND,
	VALADATE_RUNNER_RUNNER_ERROR_VAPI_ERROR
} ValadateRunnerRunnerError;
#define VALADATE_RUNNER_RUNNER_ERROR valadate_runner_runner_error_quark ()

static gpointer valadate_runner_gir_reader_parent_class = NULL;
extern gchar** valadate_runner_path;
extern gboolean valadate_runner_verbose;
extern gchar** valadate_runner_libs;
extern gint valadate_runner_nextlib;
static ValadateRunnerReaderIface* valadate_runner_gir_reader_valadate_runner_reader_parent_iface = NULL;

GType valadate_runner_reader_get_type (void) G_GNUC_CONST;
GType valadate_runner_gir_reader_get_type (void) G_GNUC_CONST;
gpointer valadate_runner_suite_info_ref (gpointer instance);
void valadate_runner_suite_info_unref (gpointer instance);
GParamSpec* valadate_runner_param_spec_suite_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void valadate_runner_value_set_suite_info (GValue* value, gpointer v_object);
void valadate_runner_value_take_suite_info (GValue* value, gpointer v_object);
gpointer valadate_runner_value_get_suite_info (const GValue* value);
GType valadate_runner_suite_info_get_type (void) G_GNUC_CONST;
GType valadate_runner_gir_suite_info_get_type (void) G_GNUC_CONST;
#define VALADATE_RUNNER_GIR_READER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALADATE_RUNNER_TYPE_GIR_READER, ValadateRunnerGirReaderPrivate))
enum  {
	VALADATE_RUNNER_GIR_READER_DUMMY_PROPERTY
};
static void _g_typelib_free0_ (gpointer var);
static void _g_slist_free__g_typelib_free0_ (GSList* self);
static void _valadate_runner_suite_info_unref0_ (gpointer var);
static void _g_slist_free__valadate_runner_suite_info_unref0_ (GSList* self);
ValadateRunnerGirReader* valadate_runner_gir_reader_new (void);
ValadateRunnerGirReader* valadate_runner_gir_reader_construct (GType object_type);
static gboolean valadate_runner_gir_reader_real_process_file (ValadateRunnerReader* base, const gchar* file, GError** error);
GQuark valadate_runner_runner_error_quark (void);
static gchar* valadate_runner_gir_reader_compile_typelib (ValadateRunnerGirReader* self, const gchar* gir_file, GError** error);
static void valadate_runner_gir_reader_real_gather_tests (ValadateRunnerReader* base, GError** error);
static gboolean valadate_runner_gir_reader_is_fixture (ValadateRunnerGirReader* self, GIObjectInfo* oi);
static void valadate_runner_gir_reader_gather_test_cases (ValadateRunnerGirReader* self, GTestSuite* ns_suite, GIObjectInfo* type_info, GError** error);
static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add2 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add3 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add4 (gchar*** array, int* length, int* size, gchar* value);
static void _vala_array_add5 (gchar*** array, int* length, int* size, gchar* value);
ValadateRunnerGirSuiteInfo* valadate_runner_gir_suite_info_new (GIObjectInfo* fx_info, GError** error);
ValadateRunnerGirSuiteInfo* valadate_runner_gir_suite_info_construct (GType object_type, GIObjectInfo* fx_info, GError** error);
void valadate_runner_gir_suite_info_create_tests (ValadateRunnerGirSuiteInfo* self, GTestSuite* suite, GError** error);
static void valadate_runner_gir_reader_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _g_typelib_free0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_typelib_free (var), NULL));
}


static void _g_slist_free__g_typelib_free0_ (GSList* self) {
	g_slist_foreach (self, (GFunc) _g_typelib_free0_, NULL);
	g_slist_free (self);
}


static void _valadate_runner_suite_info_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (valadate_runner_suite_info_unref (var), NULL));
}


static void _g_slist_free__valadate_runner_suite_info_unref0_ (GSList* self) {
	g_slist_foreach (self, (GFunc) _valadate_runner_suite_info_unref0_, NULL);
	g_slist_free (self);
}


ValadateRunnerGirReader* valadate_runner_gir_reader_construct (GType object_type) {
	ValadateRunnerGirReader * self = NULL;
	self = (ValadateRunnerGirReader*) g_object_new (object_type, NULL);
	{
		gint i = 0;
		gchar** _tmp0_ = NULL;
		gint _tmp0__length1 = 0;
		_tmp0_ = valadate_runner_path;
		_tmp0__length1 = _vala_array_length (valadate_runner_path);
		i = _tmp0__length1 - 1;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint _tmp3_ = 0;
				gchar** _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint _tmp5_ = 0;
				const gchar* _tmp6_ = NULL;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ - 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = i;
				if (!(_tmp3_ >= 0)) {
					break;
				}
				_tmp4_ = valadate_runner_path;
				_tmp4__length1 = _vala_array_length (valadate_runner_path);
				_tmp5_ = i;
				_tmp6_ = _tmp4_[_tmp5_];
				g_irepository_prepend_search_path (_tmp6_);
			}
		}
	}
	return self;
}


ValadateRunnerGirReader* valadate_runner_gir_reader_new (void) {
	return valadate_runner_gir_reader_construct (VALADATE_RUNNER_TYPE_GIR_READER);
}


static gboolean valadate_runner_gir_reader_real_process_file (ValadateRunnerReader* base, const gchar* file, GError** error) {
	ValadateRunnerGirReader * self;
	gboolean result = FALSE;
	gchar* tlfile = NULL;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	GIRepository* r = NULL;
	GIRepository* _tmp10_ = NULL;
	GMappedFile* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	GMappedFile* _tmp13_ = NULL;
	GITypelib* tl = NULL;
	GMappedFile* _tmp14_ = NULL;
	GITypelib* _tmp15_ = NULL;
	GIRepository* _tmp16_ = NULL;
	GITypelib* _tmp17_ = NULL;
	GITypelib* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
	self = (ValadateRunnerGirReader*) base;
	g_return_val_if_fail (file != NULL, FALSE);
	_tmp0_ = file;
	_tmp1_ = g_str_has_suffix (_tmp0_, ".gir");
	if (_tmp1_) {
		gchar* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		_tmp3_ = file;
		_tmp4_ = valadate_runner_gir_reader_compile_typelib (self, _tmp3_, &_inner_error_);
		_tmp2_ = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			g_propagate_error (error, _inner_error_);
			_g_free0 (tlfile);
			return FALSE;
		}
		_tmp5_ = _tmp2_;
		_tmp2_ = NULL;
		_g_free0 (tlfile);
		tlfile = _tmp5_;
		_g_free0 (_tmp2_);
	} else {
		const gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		_tmp6_ = file;
		_tmp7_ = g_strdup (_tmp6_);
		_g_free0 (tlfile);
		tlfile = _tmp7_;
	}
	_tmp8_ = tlfile;
	_tmp9_ = g_str_has_suffix (_tmp8_, ".typelib");
	if (!_tmp9_) {
		result = FALSE;
		_g_free0 (tlfile);
		return result;
	}
	_tmp10_ = g_irepository_get_default ();
	r = _tmp10_;
	_tmp12_ = tlfile;
	_tmp13_ = g_mapped_file_new (_tmp12_, FALSE, &_inner_error_);
	_tmp11_ = _tmp13_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_propagate_error (error, _inner_error_);
		_g_free0 (tlfile);
		return FALSE;
	}
	_tmp14_ = _tmp11_;
	_tmp11_ = NULL;
	_tmp15_ = g_typelib_new_from_mapped_file (_tmp14_, &_inner_error_);
	tl = _tmp15_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_propagate_error (error, _inner_error_);
		_g_mapped_file_unref0 (_tmp11_);
		_g_free0 (tlfile);
		return FALSE;
	}
	_tmp16_ = r;
	_tmp17_ = tl;
	g_irepository_load_typelib (_tmp16_, _tmp17_, 0, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_propagate_error (error, _inner_error_);
		_g_typelib_free0 (tl);
		_g_mapped_file_unref0 (_tmp11_);
		_g_free0 (tlfile);
		return FALSE;
	}
	_tmp18_ = tl;
	tl = NULL;
	self->priv->typelibs = g_slist_prepend (self->priv->typelibs, _tmp18_);
	result = TRUE;
	_g_typelib_free0 (tl);
	_g_mapped_file_unref0 (_tmp11_);
	_g_free0 (tlfile);
	return result;
}


static void valadate_runner_gir_reader_real_gather_tests (ValadateRunnerReader* base, GError** error) {
	ValadateRunnerGirReader * self;
	GIRepository* r = NULL;
	GIRepository* _tmp0_ = NULL;
	gchar** namespaces = NULL;
	GIRepository* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gint namespaces_length1 = 0;
	gint _namespaces_size_ = 0;
	GTestSuite* root = NULL;
	GTestSuite* _tmp4_ = NULL;
	gchar** _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	GError * _inner_error_ = NULL;
	self = (ValadateRunnerGirReader*) base;
	_tmp0_ = g_irepository_get_default ();
	r = _tmp0_;
	_tmp1_ = r;
	_tmp3_ = _tmp2_ = g_irepository_get_loaded_namespaces (_tmp1_);
	namespaces = _tmp3_;
	namespaces_length1 = _vala_array_length (_tmp2_);
	_namespaces_size_ = namespaces_length1;
	_tmp4_ = g_test_get_root ();
	root = _tmp4_;
	_tmp5_ = namespaces;
	_tmp5__length1 = namespaces_length1;
	{
		gchar** ns_collection = NULL;
		gint ns_collection_length1 = 0;
		gint _ns_collection_size_ = 0;
		gint ns_it = 0;
		ns_collection = _tmp5_;
		ns_collection_length1 = _tmp5__length1;
		for (ns_it = 0; ns_it < _tmp5__length1; ns_it = ns_it + 1) {
			gchar* _tmp6_ = NULL;
			gchar* ns = NULL;
			_tmp6_ = g_strdup (ns_collection[ns_it]);
			ns = _tmp6_;
			{
				GTestSuite* ns_suite = NULL;
				gint n_infos = 0;
				GIRepository* _tmp7_ = NULL;
				const gchar* _tmp8_ = NULL;
				gint _tmp9_ = 0;
				GTestSuite* _tmp33_ = NULL;
				ns_suite = NULL;
				_tmp7_ = r;
				_tmp8_ = ns;
				_tmp9_ = g_irepository_get_n_infos (_tmp7_, _tmp8_);
				n_infos = _tmp9_;
				{
					gint i = 0;
					i = 0;
					{
						gboolean _tmp10_ = FALSE;
						_tmp10_ = TRUE;
						while (TRUE) {
							gint _tmp12_ = 0;
							gint _tmp13_ = 0;
							GIBaseInfo* info = NULL;
							GIRepository* _tmp14_ = NULL;
							const gchar* _tmp15_ = NULL;
							gint _tmp16_ = 0;
							GIBaseInfo* _tmp17_ = NULL;
							gboolean _tmp18_ = FALSE;
							GIBaseInfo* _tmp24_ = NULL;
							GIInfoType _tmp25_ = 0;
							GIBaseInfo* _tmp26_ = NULL;
							gboolean _tmp27_ = FALSE;
							GTestSuite* _tmp28_ = NULL;
							GTestSuite* _tmp31_ = NULL;
							GIBaseInfo* _tmp32_ = NULL;
							if (!_tmp10_) {
								gint _tmp11_ = 0;
								_tmp11_ = i;
								i = _tmp11_ + 1;
							}
							_tmp10_ = FALSE;
							_tmp12_ = i;
							_tmp13_ = n_infos;
							if (!(_tmp12_ < _tmp13_)) {
								break;
							}
							_tmp14_ = r;
							_tmp15_ = ns;
							_tmp16_ = i;
							_tmp17_ = g_irepository_get_info (_tmp14_, _tmp15_, _tmp16_);
							info = _tmp17_;
							_tmp18_ = valadate_runner_verbose;
							if (_tmp18_) {
								FILE* _tmp19_ = NULL;
								GIBaseInfo* _tmp20_ = NULL;
								const gchar* _tmp21_ = NULL;
								GIBaseInfo* _tmp22_ = NULL;
								GIInfoType _tmp23_ = 0;
								_tmp19_ = stdout;
								_tmp20_ = info;
								_tmp21_ = g_base_info_get_name (_tmp20_);
								_tmp22_ = info;
								_tmp23_ = g_base_info_get_type (_tmp22_);
								fprintf (_tmp19_, "Found info %s of type %i\n", _tmp21_, (gint) _tmp23_);
							}
							_tmp24_ = info;
							_tmp25_ = g_base_info_get_type (_tmp24_);
							if (_tmp25_ != GI_INFO_TYPE_OBJECT) {
								_g_base_info_unref0 (info);
								continue;
							}
							_tmp26_ = info;
							_tmp27_ = valadate_runner_gir_reader_is_fixture (self, (GIObjectInfo*) _tmp26_);
							if (!_tmp27_) {
								_g_base_info_unref0 (info);
								continue;
							}
							_tmp28_ = ns_suite;
							if (_tmp28_ == NULL) {
								const gchar* _tmp29_ = NULL;
								GTestSuite* _tmp30_ = NULL;
								_tmp29_ = ns;
								_tmp30_ = g_test_create_suite (_tmp29_);
								ns_suite = _tmp30_;
							}
							_tmp31_ = ns_suite;
							_tmp32_ = info;
							valadate_runner_gir_reader_gather_test_cases (self, _tmp31_, (GIObjectInfo*) _tmp32_, &_inner_error_);
							if (G_UNLIKELY (_inner_error_ != NULL)) {
								g_propagate_error (error, _inner_error_);
								_g_base_info_unref0 (info);
								_g_free0 (ns);
								namespaces = (_vala_array_free (namespaces, namespaces_length1, (GDestroyNotify) g_free), NULL);
								return;
							}
							_g_base_info_unref0 (info);
						}
					}
				}
				_tmp33_ = ns_suite;
				if (_tmp33_ != NULL) {
					GTestSuite* _tmp34_ = NULL;
					GTestSuite* _tmp35_ = NULL;
					_tmp34_ = root;
					_tmp35_ = ns_suite;
					g_test_suite_add_suite (_tmp34_, _tmp35_);
				}
				_g_free0 (ns);
			}
		}
	}
	namespaces = (_vala_array_free (namespaces, namespaces_length1, (GDestroyNotify) g_free), NULL);
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add2 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add3 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add4 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add5 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static gchar* valadate_runner_gir_reader_compile_typelib (ValadateRunnerGirReader* self, const gchar* gir_file, GError** error) {
	gchar* result = NULL;
	gchar* typelib_file = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	struct stat gir_stat = {0};
	struct stat typelib_stat = {0};
	const gchar* _tmp7_ = NULL;
	struct stat _tmp8_ = {0};
	gint _tmp9_ = 0;
	const gchar* _tmp14_ = NULL;
	struct stat _tmp15_ = {0};
	gint _tmp16_ = 0;
	gchar** args = NULL;
	gchar* _tmp21_ = NULL;
	gchar** _tmp22_ = NULL;
	gint args_length1 = 0;
	gint _args_size_ = 0;
	gchar** _tmp23_ = NULL;
	gint _tmp23__length1 = 0;
	gchar** _tmp24_ = NULL;
	gint _tmp24__length1 = 0;
	gint _tmp25_ = 0;
	const gchar* _tmp26_ = NULL;
	gchar** _tmp34_ = NULL;
	gint _tmp34__length1 = 0;
	gchar* _tmp35_ = NULL;
	gchar** _tmp36_ = NULL;
	gint _tmp36__length1 = 0;
	const gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	gchar** _tmp39_ = NULL;
	gint _tmp39__length1 = 0;
	const gchar* _tmp40_ = NULL;
	gchar* _tmp41_ = NULL;
	gint status = 0;
	gchar** _tmp42_ = NULL;
	gint _tmp42__length1 = 0;
	gint _tmp43_ = 0;
	gint _tmp44_ = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (gir_file != NULL, NULL);
	_tmp0_ = gir_file;
	_tmp1_ = gir_file;
	_tmp2_ = strlen (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = string_substring (_tmp0_, (glong) 0, (glong) (_tmp3_ - 3));
	typelib_file = _tmp4_;
	_tmp5_ = typelib_file;
	_tmp6_ = g_strconcat (_tmp5_, "typelib", NULL);
	_g_free0 (typelib_file);
	typelib_file = _tmp6_;
	_tmp7_ = gir_file;
	_tmp9_ = stat (_tmp7_, &_tmp8_);
	gir_stat = _tmp8_;
	if (_tmp9_ != 0) {
		const gchar* _tmp10_ = NULL;
		gint _tmp11_ = 0;
		const gchar* _tmp12_ = NULL;
		GError* _tmp13_ = NULL;
		_tmp10_ = gir_file;
		_tmp11_ = errno;
		_tmp12_ = strerror (_tmp11_);
		_tmp13_ = g_error_new (VALADATE_RUNNER_RUNNER_ERROR, VALADATE_RUNNER_RUNNER_ERROR_CANNOT_READ, "Cannot read %s: %s", _tmp10_, _tmp12_);
		_inner_error_ = _tmp13_;
		if ((_inner_error_->domain == G_SPAWN_ERROR) || (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR)) {
			g_propagate_error (error, _inner_error_);
			_g_free0 (typelib_file);
			return NULL;
		} else {
			_g_free0 (typelib_file);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp14_ = typelib_file;
	_tmp16_ = stat (_tmp14_, &_tmp15_);
	typelib_stat = _tmp15_;
	if (_tmp16_ == 0) {
		struct stat _tmp17_ = {0};
		time_t _tmp18_ = 0;
		struct stat _tmp19_ = {0};
		time_t _tmp20_ = 0;
		_tmp17_ = typelib_stat;
		_tmp18_ = _tmp17_.st_mtime;
		_tmp19_ = gir_stat;
		_tmp20_ = _tmp19_.st_mtime;
		if (_tmp18_ > _tmp20_) {
			result = typelib_file;
			return result;
		}
	}
	_tmp21_ = g_strdup ("g-ir-compiler");
	_tmp22_ = g_new0 (gchar*, 1 + 1);
	_tmp22_[0] = _tmp21_;
	args = _tmp22_;
	args_length1 = 1;
	_args_size_ = args_length1;
	_tmp23_ = valadate_runner_libs;
	_tmp23__length1 = _vala_array_length (valadate_runner_libs);
	_tmp24_ = valadate_runner_libs;
	_tmp24__length1 = _vala_array_length (valadate_runner_libs);
	_tmp25_ = valadate_runner_nextlib;
	_tmp26_ = _tmp24_[_tmp25_];
	if ((_tmp23_ != NULL) & (_tmp26_ != NULL)) {
		gchar** _tmp27_ = NULL;
		gint _tmp27__length1 = 0;
		gchar* _tmp28_ = NULL;
		gchar** _tmp29_ = NULL;
		gint _tmp29__length1 = 0;
		gchar** _tmp30_ = NULL;
		gint _tmp30__length1 = 0;
		gint _tmp31_ = 0;
		const gchar* _tmp32_ = NULL;
		gchar* _tmp33_ = NULL;
		_tmp27_ = args;
		_tmp27__length1 = args_length1;
		_tmp28_ = g_strdup ("-l");
		_vala_array_add1 (&args, &args_length1, &_args_size_, _tmp28_);
		_tmp29_ = args;
		_tmp29__length1 = args_length1;
		_tmp30_ = valadate_runner_libs;
		_tmp30__length1 = _vala_array_length (valadate_runner_libs);
		_tmp31_ = valadate_runner_nextlib;
		_tmp32_ = _tmp30_[_tmp31_];
		_tmp33_ = g_strdup (_tmp32_);
		_vala_array_add2 (&args, &args_length1, &_args_size_, _tmp33_);
	}
	_tmp34_ = args;
	_tmp34__length1 = args_length1;
	_tmp35_ = g_strdup ("-o");
	_vala_array_add3 (&args, &args_length1, &_args_size_, _tmp35_);
	_tmp36_ = args;
	_tmp36__length1 = args_length1;
	_tmp37_ = typelib_file;
	_tmp38_ = g_strdup (_tmp37_);
	_vala_array_add4 (&args, &args_length1, &_args_size_, _tmp38_);
	_tmp39_ = args;
	_tmp39__length1 = args_length1;
	_tmp40_ = gir_file;
	_tmp41_ = g_strdup (_tmp40_);
	_vala_array_add5 (&args, &args_length1, &_args_size_, _tmp41_);
	_tmp42_ = args;
	_tmp42__length1 = args_length1;
	g_spawn_sync (NULL, _tmp42_, NULL, G_SPAWN_SEARCH_PATH, NULL, NULL, NULL, NULL, &_tmp43_, &_inner_error_);
	status = _tmp43_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if ((_inner_error_->domain == G_SPAWN_ERROR) || (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR)) {
			g_propagate_error (error, _inner_error_);
			args = (_vala_array_free (args, args_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (typelib_file);
			return NULL;
		} else {
			args = (_vala_array_free (args, args_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (typelib_file);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp44_ = status;
	if (_tmp44_ != 0) {
		const gchar* _tmp45_ = NULL;
		const gchar* _tmp46_ = NULL;
		gint _tmp47_ = 0;
		GError* _tmp48_ = NULL;
		_tmp45_ = typelib_file;
		_tmp46_ = gir_file;
		_tmp47_ = status;
		_tmp48_ = g_error_new (VALADATE_RUNNER_RUNNER_ERROR, VALADATE_RUNNER_RUNNER_ERROR_COMPILATION_FAILED, "g-ir-compiler -o %s %s failed with status %i", _tmp45_, _tmp46_, _tmp47_);
		_inner_error_ = _tmp48_;
		if ((_inner_error_->domain == G_SPAWN_ERROR) || (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR)) {
			g_propagate_error (error, _inner_error_);
			args = (_vala_array_free (args, args_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (typelib_file);
			return NULL;
		} else {
			args = (_vala_array_free (args, args_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (typelib_file);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	result = typelib_file;
	args = (_vala_array_free (args, args_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


static gboolean valadate_runner_gir_reader_is_fixture (ValadateRunnerGirReader* self, GIObjectInfo* oi) {
	gboolean result = FALSE;
	gint n_ifs = 0;
	GIObjectInfo* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (oi != NULL, FALSE);
	_tmp0_ = oi;
	_tmp1_ = g_object_info_get_n_interfaces (_tmp0_);
	n_ifs = _tmp1_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gint _tmp4_ = 0;
				gint _tmp5_ = 0;
				GIInterfaceInfo* ii = NULL;
				GIObjectInfo* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				GIInterfaceInfo* _tmp8_ = NULL;
				gboolean _tmp9_ = FALSE;
				gboolean _tmp15_ = FALSE;
				GIInterfaceInfo* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = n_ifs;
				if (!(_tmp4_ < _tmp5_)) {
					break;
				}
				_tmp6_ = oi;
				_tmp7_ = i;
				_tmp8_ = g_object_info_get_interface (_tmp6_, _tmp7_);
				ii = _tmp8_;
				_tmp9_ = valadate_runner_verbose;
				if (_tmp9_) {
					FILE* _tmp10_ = NULL;
					GIInterfaceInfo* _tmp11_ = NULL;
					const gchar* _tmp12_ = NULL;
					GIInterfaceInfo* _tmp13_ = NULL;
					const gchar* _tmp14_ = NULL;
					_tmp10_ = stdout;
					_tmp11_ = ii;
					_tmp12_ = g_base_info_get_namespace ((GIBaseInfo*) _tmp11_);
					_tmp13_ = ii;
					_tmp14_ = g_base_info_get_name ((GIBaseInfo*) _tmp13_);
					fprintf (_tmp10_, "Found interface %s.%s...\n", _tmp12_, _tmp14_);
				}
				_tmp16_ = ii;
				_tmp17_ = g_base_info_get_namespace ((GIBaseInfo*) _tmp16_);
				if (g_strcmp0 (_tmp17_, "Valadate") == 0) {
					GIInterfaceInfo* _tmp18_ = NULL;
					const gchar* _tmp19_ = NULL;
					_tmp18_ = ii;
					_tmp19_ = g_base_info_get_name ((GIBaseInfo*) _tmp18_);
					_tmp15_ = g_strcmp0 (_tmp19_, "Fixture") == 0;
				} else {
					_tmp15_ = FALSE;
				}
				if (_tmp15_) {
					result = TRUE;
					_g_base_info_unref0 (ii);
					return result;
				}
				_g_base_info_unref0 (ii);
			}
		}
	}
	result = FALSE;
	return result;
}


static void valadate_runner_gir_reader_gather_test_cases (ValadateRunnerGirReader* self, GTestSuite* ns_suite, GIObjectInfo* type_info, GError** error) {
	gboolean _tmp0_ = FALSE;
	GTestSuite* suite = NULL;
	GIObjectInfo* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GTestSuite* _tmp6_ = NULL;
	GTestSuite* _tmp7_ = NULL;
	GTestSuite* _tmp8_ = NULL;
	ValadateRunnerGirSuiteInfo* sinfo = NULL;
	GIObjectInfo* _tmp9_ = NULL;
	ValadateRunnerGirSuiteInfo* _tmp10_ = NULL;
	ValadateRunnerGirSuiteInfo* _tmp11_ = NULL;
	GTestSuite* _tmp12_ = NULL;
	ValadateRunnerGirSuiteInfo* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (ns_suite != NULL);
	g_return_if_fail (type_info != NULL);
	_tmp0_ = valadate_runner_verbose;
	if (_tmp0_) {
		FILE* _tmp1_ = NULL;
		GIObjectInfo* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		_tmp1_ = stdout;
		_tmp2_ = type_info;
		_tmp3_ = g_base_info_get_name ((GIBaseInfo*) _tmp2_);
		fprintf (_tmp1_, "    searching for tests in %s\n", _tmp3_);
	}
	_tmp4_ = type_info;
	_tmp5_ = g_base_info_get_name ((GIBaseInfo*) _tmp4_);
	_tmp6_ = g_test_create_suite (_tmp5_);
	suite = _tmp6_;
	_tmp7_ = ns_suite;
	_tmp8_ = suite;
	g_test_suite_add_suite (_tmp7_, _tmp8_);
	_tmp9_ = type_info;
	_tmp10_ = valadate_runner_gir_suite_info_new (_tmp9_, &_inner_error_);
	sinfo = _tmp10_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if ((_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) || (_inner_error_->domain == G_IINVOKE_ERROR)) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_tmp11_ = sinfo;
	_tmp12_ = suite;
	valadate_runner_gir_suite_info_create_tests (_tmp11_, _tmp12_, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if ((_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) || (_inner_error_->domain == G_IINVOKE_ERROR)) {
			g_propagate_error (error, _inner_error_);
			_valadate_runner_suite_info_unref0 (sinfo);
			return;
		} else {
			_valadate_runner_suite_info_unref0 (sinfo);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_tmp13_ = sinfo;
	sinfo = NULL;
	self->priv->suites = g_slist_prepend (self->priv->suites, _tmp13_);
	_tmp14_ = valadate_runner_verbose;
	if (_tmp14_) {
		FILE* _tmp15_ = NULL;
		GIObjectInfo* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		_tmp15_ = stdout;
		_tmp16_ = type_info;
		_tmp17_ = g_base_info_get_name ((GIBaseInfo*) _tmp16_);
		fprintf (_tmp15_, "    search complete in %s\n", _tmp17_);
	}
	_valadate_runner_suite_info_unref0 (sinfo);
}


static void valadate_runner_gir_reader_class_init (ValadateRunnerGirReaderClass * klass) {
	valadate_runner_gir_reader_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ValadateRunnerGirReaderPrivate));
	G_OBJECT_CLASS (klass)->finalize = valadate_runner_gir_reader_finalize;
}


static void valadate_runner_gir_reader_valadate_runner_reader_interface_init (ValadateRunnerReaderIface * iface) {
	valadate_runner_gir_reader_valadate_runner_reader_parent_iface = g_type_interface_peek_parent (iface);
	iface->process_file = (gboolean (*)(ValadateRunnerReader*, const gchar*, GError**)) valadate_runner_gir_reader_real_process_file;
	iface->gather_tests = (void (*)(ValadateRunnerReader*, GError**)) valadate_runner_gir_reader_real_gather_tests;
}


static void valadate_runner_gir_reader_instance_init (ValadateRunnerGirReader * self) {
	self->priv = VALADATE_RUNNER_GIR_READER_GET_PRIVATE (self);
	self->priv->typelibs = NULL;
	self->priv->suites = NULL;
}


static void valadate_runner_gir_reader_finalize (GObject* obj) {
	ValadateRunnerGirReader * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALADATE_RUNNER_TYPE_GIR_READER, ValadateRunnerGirReader);
	__g_slist_free__g_typelib_free0_0 (self->priv->typelibs);
	__g_slist_free__valadate_runner_suite_info_unref0_0 (self->priv->suites);
	G_OBJECT_CLASS (valadate_runner_gir_reader_parent_class)->finalize (obj);
}


GType valadate_runner_gir_reader_get_type (void) {
	static volatile gsize valadate_runner_gir_reader_type_id__volatile = 0;
	if (g_once_init_enter (&valadate_runner_gir_reader_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValadateRunnerGirReaderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valadate_runner_gir_reader_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValadateRunnerGirReader), 0, (GInstanceInitFunc) valadate_runner_gir_reader_instance_init, NULL };
		static const GInterfaceInfo valadate_runner_reader_info = { (GInterfaceInitFunc) valadate_runner_gir_reader_valadate_runner_reader_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType valadate_runner_gir_reader_type_id;
		valadate_runner_gir_reader_type_id = g_type_register_static (G_TYPE_OBJECT, "ValadateRunnerGirReader", &g_define_type_info, 0);
		g_type_add_interface_static (valadate_runner_gir_reader_type_id, VALADATE_RUNNER_TYPE_READER, &valadate_runner_reader_info);
		g_once_init_leave (&valadate_runner_gir_reader_type_id__volatile, valadate_runner_gir_reader_type_id);
	}
	return valadate_runner_gir_reader_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



