/* girsuiteinfo.c generated by valac 0.30.0, the Vala compiler
 * generated from girsuiteinfo.vala, do not modify */

/*
 * Valadate - Unit testing library for GObject-based libraries.
 * Copyright (C) 2009  Jan Hudec <bulb@ucw.cz>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <girepository-fixes.h>
#include <valagee.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "libvaladate.h"
#include <gmodule.h>


#define VALADATE_RUNNER_TYPE_SUITE_INFO (valadate_runner_suite_info_get_type ())
#define VALADATE_RUNNER_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfo))
#define VALADATE_RUNNER_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoClass))
#define VALADATE_RUNNER_IS_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO))
#define VALADATE_RUNNER_IS_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_SUITE_INFO))
#define VALADATE_RUNNER_SUITE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoClass))

typedef struct _ValadateRunnerSuiteInfo ValadateRunnerSuiteInfo;
typedef struct _ValadateRunnerSuiteInfoClass ValadateRunnerSuiteInfoClass;
typedef struct _ValadateRunnerSuiteInfoPrivate ValadateRunnerSuiteInfoPrivate;

#define VALADATE_RUNNER_TYPE_GIR_SUITE_INFO (valadate_runner_gir_suite_info_get_type ())
#define VALADATE_RUNNER_GIR_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, ValadateRunnerGirSuiteInfo))
#define VALADATE_RUNNER_GIR_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, ValadateRunnerGirSuiteInfoClass))
#define VALADATE_RUNNER_IS_GIR_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO))
#define VALADATE_RUNNER_IS_GIR_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO))
#define VALADATE_RUNNER_GIR_SUITE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, ValadateRunnerGirSuiteInfoClass))

typedef struct _ValadateRunnerGirSuiteInfo ValadateRunnerGirSuiteInfo;
typedef struct _ValadateRunnerGirSuiteInfoClass ValadateRunnerGirSuiteInfoClass;
typedef struct _ValadateRunnerGirSuiteInfoPrivate ValadateRunnerGirSuiteInfoPrivate;

#define VALADATE_RUNNER_GIR_SUITE_INFO_TYPE_TEST_TYPE (valadate_runner_gir_suite_info_test_type_get_type ())
#define _g_base_info_unref0(var) ((var == NULL) ? NULL : (var = (g_base_info_unref (var), NULL)))
#define _valadate_runner_suite_info_unref0(var) ((var == NULL) ? NULL : (var = (valadate_runner_suite_info_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ValadateRunnerSuiteInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValadateRunnerSuiteInfoPrivate * priv;
};

struct _ValadateRunnerSuiteInfoClass {
	GTypeClass parent_class;
	void (*finalize) (ValadateRunnerSuiteInfo *self);
};

struct _ValadateRunnerGirSuiteInfo {
	ValadateRunnerSuiteInfo parent_instance;
	ValadateRunnerGirSuiteInfoPrivate * priv;
};

struct _ValadateRunnerGirSuiteInfoClass {
	ValadateRunnerSuiteInfoClass parent_class;
};

struct _ValadateRunnerGirSuiteInfoPrivate {
	GIObjectInfo* fx_info;
};

typedef enum  {
	VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_NONE,
	VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_SYNC,
	VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_ASYNC,
	VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_CANCELLABLE
} ValadateRunnerGirSuiteInfoTestType;

typedef enum  {
	VALADATE_RUNNER_RUNNER_ERROR_UNRECOGNIZED_FILE,
	VALADATE_RUNNER_RUNNER_ERROR_CANNOT_READ,
	VALADATE_RUNNER_RUNNER_ERROR_COMPILATION_FAILED,
	VALADATE_RUNNER_RUNNER_ERROR_TYPE_NOT_LOADED,
	VALADATE_RUNNER_RUNNER_ERROR_NOT_FOUND,
	VALADATE_RUNNER_RUNNER_ERROR_VAPI_ERROR
} ValadateRunnerRunnerError;
#define VALADATE_RUNNER_RUNNER_ERROR valadate_runner_runner_error_quark ()
typedef GValueArray* (*ValadateRunnerGenerator) (void* user_data);
typedef void (*ValadateRunnerTestMarshaller) (ValadateFixture* fixture, void* arg1, void* arg2, void* user_data);

static gpointer valadate_runner_gir_suite_info_parent_class = NULL;
extern gboolean valadate_runner_verbose;

gpointer valadate_runner_suite_info_ref (gpointer instance);
void valadate_runner_suite_info_unref (gpointer instance);
GParamSpec* valadate_runner_param_spec_suite_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void valadate_runner_value_set_suite_info (GValue* value, gpointer v_object);
void valadate_runner_value_take_suite_info (GValue* value, gpointer v_object);
gpointer valadate_runner_value_get_suite_info (const GValue* value);
GType valadate_runner_suite_info_get_type (void) G_GNUC_CONST;
GType valadate_runner_gir_suite_info_get_type (void) G_GNUC_CONST;
#define VALADATE_RUNNER_GIR_SUITE_INFO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, ValadateRunnerGirSuiteInfoPrivate))
enum  {
	VALADATE_RUNNER_GIR_SUITE_INFO_DUMMY_PROPERTY
};
static GType valadate_runner_gir_suite_info_test_type_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
GQuark valadate_runner_runner_error_quark (void);
ValadateRunnerGirSuiteInfo* valadate_runner_gir_suite_info_new (GIObjectInfo* fx_info, GError** error);
ValadateRunnerGirSuiteInfo* valadate_runner_gir_suite_info_construct (GType object_type, GIObjectInfo* fx_info, GError** error);
ValadateRunnerSuiteInfo* valadate_runner_suite_info_new (GType type, GError** error);
ValadateRunnerSuiteInfo* valadate_runner_suite_info_construct (GType object_type, GType type, GError** error);
void valadate_runner_gir_suite_info_create_tests (ValadateRunnerGirSuiteInfo* self, GTestSuite* suite, GError** error);
static void valadate_runner_gir_suite_info_gather_methods (ValadateRunnerGirSuiteInfo* self, GIObjectInfo* fx_info, ValaArrayList** fn_infos);
static gboolean valadate_runner_gir_suite_info_is_generator (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* fn);
static void* valadate_runner_gir_suite_info_get_fn_pointer (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* fn_info, GError** error);
void valadate_runner_suite_info_add_generator (ValadateRunnerSuiteInfo* self, const gchar* prop, ValadateRunnerGenerator gen, void* gen_target);
static gboolean valadate_runner_gir_suite_info_is_test (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* method);
static ValadateRunnerGirSuiteInfoTestType valadate_runner_gir_suite_info_test_type (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* method);
void valadate_runner_suite_info_add_test (ValadateRunnerSuiteInfo* self, GTestSuite* suite, const gchar* name, ValadateRunnerTestMarshaller marshaller, void* marshaller_target, void* arg1, void* arg2);
void valadate_runner_test_marshal_synchronous (ValadateFixture* it, void* arg1, void* arg2);
static void _valadate_runner_test_marshal_synchronous_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self);
static GIFunctionInfo* valadate_runner_gir_suite_info_get_finish (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* begin_info);
void valadate_runner_test_marshal_asynchronous (ValadateFixture* it, void* arg1, void* arg2);
static void _valadate_runner_test_marshal_asynchronous_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self);
void valadate_runner_test_marshal_cancellable (ValadateFixture* it, void* arg1, void* arg2);
static void _valadate_runner_test_marshal_cancellable_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self);
static void valadate_runner_gir_suite_info_finalize (ValadateRunnerSuiteInfo* obj);


static GType valadate_runner_gir_suite_info_test_type_get_type (void) {
	static volatile gsize valadate_runner_gir_suite_info_test_type_type_id__volatile = 0;
	if (g_once_init_enter (&valadate_runner_gir_suite_info_test_type_type_id__volatile)) {
		static const GEnumValue values[] = {{VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_NONE, "VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_NONE", "none"}, {VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_SYNC, "VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_SYNC", "sync"}, {VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_ASYNC, "VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_ASYNC", "async"}, {VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_CANCELLABLE, "VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_CANCELLABLE", "cancellable"}, {0, NULL, NULL}};
		GType valadate_runner_gir_suite_info_test_type_type_id;
		valadate_runner_gir_suite_info_test_type_type_id = g_enum_register_static ("ValadateRunnerGirSuiteInfoTestType", values);
		g_once_init_leave (&valadate_runner_gir_suite_info_test_type_type_id__volatile, valadate_runner_gir_suite_info_test_type_type_id);
	}
	return valadate_runner_gir_suite_info_test_type_type_id__volatile;
}


static gpointer _g_base_info_ref0 (gpointer self) {
	return self ? g_base_info_ref (self) : NULL;
}


ValadateRunnerGirSuiteInfo* valadate_runner_gir_suite_info_construct (GType object_type, GIObjectInfo* fx_info, GError** error) {
	ValadateRunnerGirSuiteInfo* self = NULL;
	GIObjectInfo* _tmp0_ = NULL;
	GType _tmp1_ = 0UL;
	GIObjectInfo* _tmp2_ = NULL;
	GIObjectInfo* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (fx_info != NULL, NULL);
	_tmp0_ = fx_info;
	_tmp1_ = g_registered_type_info_get_g_type ((GIRegisteredTypeInfo*) _tmp0_);
	self = (ValadateRunnerGirSuiteInfo*) valadate_runner_suite_info_construct (object_type, _tmp1_, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if ((_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) || (_inner_error_->domain == G_IINVOKE_ERROR)) {
			g_propagate_error (error, _inner_error_);
			_valadate_runner_suite_info_unref0 (self);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp2_ = fx_info;
	_tmp3_ = _g_base_info_ref0 (_tmp2_);
	_g_base_info_unref0 (self->priv->fx_info);
	self->priv->fx_info = _tmp3_;
	return self;
}


ValadateRunnerGirSuiteInfo* valadate_runner_gir_suite_info_new (GIObjectInfo* fx_info, GError** error) {
	return valadate_runner_gir_suite_info_construct (VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, fx_info, error);
}


static gpointer _vala_iterable_ref0 (gpointer self) {
	return self ? vala_iterable_ref (self) : NULL;
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


static gchar* string_delimit (const gchar* self, const gchar* delimiters, gchar new_delimiter) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar _tmp3_ = '\0';
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (delimiters != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	_tmp2_ = delimiters;
	_tmp3_ = new_delimiter;
	g_strdelimit (_tmp1_, _tmp2_, _tmp3_);
	result = _result_;
	return result;
}


static void _valadate_runner_test_marshal_synchronous_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self) {
	valadate_runner_test_marshal_synchronous (fixture, arg1, arg2);
}


static void _valadate_runner_test_marshal_asynchronous_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self) {
	valadate_runner_test_marshal_asynchronous (fixture, arg1, arg2);
}


static void _valadate_runner_test_marshal_cancellable_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self) {
	valadate_runner_test_marshal_cancellable (fixture, arg1, arg2);
}


void valadate_runner_gir_suite_info_create_tests (ValadateRunnerGirSuiteInfo* self, GTestSuite* suite, GError** error) {
	ValaArrayList* fn_infos = NULL;
	GEqualFunc _tmp0_ = NULL;
	ValaArrayList* _tmp1_ = NULL;
	GIObjectInfo* _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (suite != NULL);
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (G_TYPE_POINTER, (GBoxedCopyFunc) g_base_info_ref, g_base_info_unref, _tmp0_);
	fn_infos = _tmp1_;
	_tmp2_ = self->priv->fx_info;
	valadate_runner_gir_suite_info_gather_methods (self, _tmp2_, &fn_infos);
	{
		ValaArrayList* _fn_info_list = NULL;
		ValaArrayList* _tmp3_ = NULL;
		ValaArrayList* _tmp4_ = NULL;
		gint _fn_info_size = 0;
		ValaArrayList* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gint _fn_info_index = 0;
		_tmp3_ = fn_infos;
		_tmp4_ = _vala_iterable_ref0 (_tmp3_);
		_fn_info_list = _tmp4_;
		_tmp5_ = _fn_info_list;
		_tmp6_ = vala_collection_get_size ((ValaCollection*) _tmp5_);
		_tmp7_ = _tmp6_;
		_fn_info_size = _tmp7_;
		_fn_info_index = -1;
		while (TRUE) {
			gint _tmp8_ = 0;
			gint _tmp9_ = 0;
			gint _tmp10_ = 0;
			GIFunctionInfo* fn_info = NULL;
			ValaArrayList* _tmp11_ = NULL;
			gint _tmp12_ = 0;
			gpointer _tmp13_ = NULL;
			GIFunctionInfo* _tmp14_ = NULL;
			gboolean _tmp15_ = FALSE;
			gboolean _tmp16_ = FALSE;
			void* _tmp20_ = NULL;
			GIFunctionInfo* _tmp21_ = NULL;
			void* _tmp22_ = NULL;
			GIFunctionInfo* _tmp23_ = NULL;
			const gchar* _tmp24_ = NULL;
			gchar* _tmp25_ = NULL;
			gchar* _tmp26_ = NULL;
			gchar* _tmp27_ = NULL;
			gchar* _tmp28_ = NULL;
			_tmp8_ = _fn_info_index;
			_fn_info_index = _tmp8_ + 1;
			_tmp9_ = _fn_info_index;
			_tmp10_ = _fn_info_size;
			if (!(_tmp9_ < _tmp10_)) {
				break;
			}
			_tmp11_ = _fn_info_list;
			_tmp12_ = _fn_info_index;
			_tmp13_ = vala_list_get ((ValaList*) _tmp11_, _tmp12_);
			fn_info = (GIFunctionInfo*) _tmp13_;
			_tmp14_ = fn_info;
			_tmp15_ = valadate_runner_gir_suite_info_is_generator (self, _tmp14_);
			if (!_tmp15_) {
				_g_base_info_unref0 (fn_info);
				continue;
			}
			_tmp16_ = valadate_runner_verbose;
			if (_tmp16_) {
				FILE* _tmp17_ = NULL;
				GIFunctionInfo* _tmp18_ = NULL;
				const gchar* _tmp19_ = NULL;
				_tmp17_ = stdout;
				_tmp18_ = fn_info;
				_tmp19_ = g_base_info_get_name ((GIBaseInfo*) _tmp18_);
				fprintf (_tmp17_, "        found generator %s\n", _tmp19_);
			}
			_tmp21_ = fn_info;
			_tmp22_ = valadate_runner_gir_suite_info_get_fn_pointer (self, _tmp21_, &_inner_error_);
			_tmp20_ = _tmp22_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				if (_inner_error_->domain == G_IINVOKE_ERROR) {
					g_propagate_error (error, _inner_error_);
					_g_base_info_unref0 (fn_info);
					_vala_iterable_unref0 (_fn_info_list);
					_vala_iterable_unref0 (fn_infos);
					return;
				} else {
					_g_base_info_unref0 (fn_info);
					_vala_iterable_unref0 (_fn_info_list);
					_vala_iterable_unref0 (fn_infos);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
			}
			_tmp23_ = fn_info;
			_tmp24_ = g_base_info_get_name ((GIBaseInfo*) _tmp23_);
			_tmp25_ = string_substring (_tmp24_, (glong) 9, (glong) -1);
			_tmp26_ = _tmp25_;
			_tmp27_ = string_delimit (_tmp26_, "_", '-');
			_tmp28_ = _tmp27_;
			valadate_runner_suite_info_add_generator ((ValadateRunnerSuiteInfo*) self, _tmp28_, (ValadateRunnerGenerator) _tmp20_, NULL);
			_g_free0 (_tmp28_);
			_g_free0 (_tmp26_);
			_g_base_info_unref0 (fn_info);
		}
		_vala_iterable_unref0 (_fn_info_list);
	}
	{
		ValaArrayList* _fn_info_list = NULL;
		ValaArrayList* _tmp29_ = NULL;
		ValaArrayList* _tmp30_ = NULL;
		gint _fn_info_size = 0;
		ValaArrayList* _tmp31_ = NULL;
		gint _tmp32_ = 0;
		gint _tmp33_ = 0;
		gint _fn_info_index = 0;
		_tmp29_ = fn_infos;
		_tmp30_ = _vala_iterable_ref0 (_tmp29_);
		_fn_info_list = _tmp30_;
		_tmp31_ = _fn_info_list;
		_tmp32_ = vala_collection_get_size ((ValaCollection*) _tmp31_);
		_tmp33_ = _tmp32_;
		_fn_info_size = _tmp33_;
		_fn_info_index = -1;
		while (TRUE) {
			gint _tmp34_ = 0;
			gint _tmp35_ = 0;
			gint _tmp36_ = 0;
			GIFunctionInfo* fn_info = NULL;
			ValaArrayList* _tmp37_ = NULL;
			gint _tmp38_ = 0;
			gpointer _tmp39_ = NULL;
			GIFunctionInfo* _tmp40_ = NULL;
			gboolean _tmp41_ = FALSE;
			GIFunctionInfo* _tmp42_ = NULL;
			ValadateRunnerGirSuiteInfoTestType _tmp43_ = 0;
			_tmp34_ = _fn_info_index;
			_fn_info_index = _tmp34_ + 1;
			_tmp35_ = _fn_info_index;
			_tmp36_ = _fn_info_size;
			if (!(_tmp35_ < _tmp36_)) {
				break;
			}
			_tmp37_ = _fn_info_list;
			_tmp38_ = _fn_info_index;
			_tmp39_ = vala_list_get ((ValaList*) _tmp37_, _tmp38_);
			fn_info = (GIFunctionInfo*) _tmp39_;
			_tmp40_ = fn_info;
			_tmp41_ = valadate_runner_gir_suite_info_is_test (self, _tmp40_);
			if (!_tmp41_) {
				_g_base_info_unref0 (fn_info);
				continue;
			}
			_tmp42_ = fn_info;
			_tmp43_ = valadate_runner_gir_suite_info_test_type (self, _tmp42_);
			switch (_tmp43_) {
				case VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_SYNC:
				{
					gboolean _tmp44_ = FALSE;
					void* _tmp48_ = NULL;
					GIFunctionInfo* _tmp49_ = NULL;
					void* _tmp50_ = NULL;
					GTestSuite* _tmp51_ = NULL;
					GIFunctionInfo* _tmp52_ = NULL;
					const gchar* _tmp53_ = NULL;
					gchar* _tmp54_ = NULL;
					gchar* _tmp55_ = NULL;
					_tmp44_ = valadate_runner_verbose;
					if (_tmp44_) {
						FILE* _tmp45_ = NULL;
						GIFunctionInfo* _tmp46_ = NULL;
						const gchar* _tmp47_ = NULL;
						_tmp45_ = stdout;
						_tmp46_ = fn_info;
						_tmp47_ = g_base_info_get_name ((GIBaseInfo*) _tmp46_);
						fprintf (_tmp45_, "        found test %s\n", _tmp47_);
					}
					_tmp49_ = fn_info;
					_tmp50_ = valadate_runner_gir_suite_info_get_fn_pointer (self, _tmp49_, &_inner_error_);
					_tmp48_ = _tmp50_;
					if (G_UNLIKELY (_inner_error_ != NULL)) {
						if (_inner_error_->domain == G_IINVOKE_ERROR) {
							g_propagate_error (error, _inner_error_);
							_g_base_info_unref0 (fn_info);
							_vala_iterable_unref0 (_fn_info_list);
							_vala_iterable_unref0 (fn_infos);
							return;
						} else {
							_g_base_info_unref0 (fn_info);
							_vala_iterable_unref0 (_fn_info_list);
							_vala_iterable_unref0 (fn_infos);
							g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
							g_clear_error (&_inner_error_);
							return;
						}
					}
					_tmp51_ = suite;
					_tmp52_ = fn_info;
					_tmp53_ = g_base_info_get_name ((GIBaseInfo*) _tmp52_);
					_tmp54_ = string_substring (_tmp53_, (glong) 5, (glong) -1);
					_tmp55_ = _tmp54_;
					valadate_runner_suite_info_add_test ((ValadateRunnerSuiteInfo*) self, _tmp51_, _tmp55_, _valadate_runner_test_marshal_synchronous_valadate_runner_test_marshaller, NULL, _tmp48_, NULL);
					_g_free0 (_tmp55_);
					break;
				}
				case VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_ASYNC:
				{
					GIFunctionInfo* finish_info = NULL;
					GIFunctionInfo* _tmp56_ = NULL;
					GIFunctionInfo* _tmp57_ = NULL;
					GIFunctionInfo* _tmp58_ = NULL;
					_tmp56_ = fn_info;
					_tmp57_ = valadate_runner_gir_suite_info_get_finish (self, _tmp56_);
					finish_info = _tmp57_;
					_tmp58_ = finish_info;
					if (_tmp58_ != NULL) {
						void* _tmp59_ = NULL;
						GIFunctionInfo* _tmp60_ = NULL;
						void* _tmp61_ = NULL;
						void* _tmp62_ = NULL;
						GIFunctionInfo* _tmp63_ = NULL;
						void* _tmp64_ = NULL;
						GTestSuite* _tmp65_ = NULL;
						GIFunctionInfo* _tmp66_ = NULL;
						const gchar* _tmp67_ = NULL;
						gchar* _tmp68_ = NULL;
						gchar* _tmp69_ = NULL;
						_tmp60_ = fn_info;
						_tmp61_ = valadate_runner_gir_suite_info_get_fn_pointer (self, _tmp60_, &_inner_error_);
						_tmp59_ = _tmp61_;
						if (G_UNLIKELY (_inner_error_ != NULL)) {
							if (_inner_error_->domain == G_IINVOKE_ERROR) {
								g_propagate_error (error, _inner_error_);
								_g_base_info_unref0 (finish_info);
								_g_base_info_unref0 (fn_info);
								_vala_iterable_unref0 (_fn_info_list);
								_vala_iterable_unref0 (fn_infos);
								return;
							} else {
								_g_base_info_unref0 (finish_info);
								_g_base_info_unref0 (fn_info);
								_vala_iterable_unref0 (_fn_info_list);
								_vala_iterable_unref0 (fn_infos);
								g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
								g_clear_error (&_inner_error_);
								return;
							}
						}
						_tmp63_ = finish_info;
						_tmp64_ = valadate_runner_gir_suite_info_get_fn_pointer (self, _tmp63_, &_inner_error_);
						_tmp62_ = _tmp64_;
						if (G_UNLIKELY (_inner_error_ != NULL)) {
							if (_inner_error_->domain == G_IINVOKE_ERROR) {
								g_propagate_error (error, _inner_error_);
								_g_base_info_unref0 (finish_info);
								_g_base_info_unref0 (fn_info);
								_vala_iterable_unref0 (_fn_info_list);
								_vala_iterable_unref0 (fn_infos);
								return;
							} else {
								_g_base_info_unref0 (finish_info);
								_g_base_info_unref0 (fn_info);
								_vala_iterable_unref0 (_fn_info_list);
								_vala_iterable_unref0 (fn_infos);
								g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
								g_clear_error (&_inner_error_);
								return;
							}
						}
						_tmp65_ = suite;
						_tmp66_ = fn_info;
						_tmp67_ = g_base_info_get_name ((GIBaseInfo*) _tmp66_);
						_tmp68_ = string_substring (_tmp67_, (glong) 5, (glong) -1);
						_tmp69_ = _tmp68_;
						valadate_runner_suite_info_add_test ((ValadateRunnerSuiteInfo*) self, _tmp65_, _tmp69_, _valadate_runner_test_marshal_asynchronous_valadate_runner_test_marshaller, NULL, _tmp59_, _tmp62_);
						_g_free0 (_tmp69_);
					} else {
						GIObjectInfo* _tmp70_ = NULL;
						const gchar* _tmp71_ = NULL;
						GIObjectInfo* _tmp72_ = NULL;
						const gchar* _tmp73_ = NULL;
						GIFunctionInfo* _tmp74_ = NULL;
						const gchar* _tmp75_ = NULL;
						_tmp70_ = self->priv->fx_info;
						_tmp71_ = g_base_info_get_namespace ((GIBaseInfo*) _tmp70_);
						_tmp72_ = self->priv->fx_info;
						_tmp73_ = g_base_info_get_name ((GIBaseInfo*) _tmp72_);
						_tmp74_ = fn_info;
						_tmp75_ = g_base_info_get_name ((GIBaseInfo*) _tmp74_);
						g_warning ("girsuiteinfo.vala:66: %s.%s.%s looks like an async test, but matching " \
"finish method was not found.", _tmp71_, _tmp73_, _tmp75_);
					}
					_g_base_info_unref0 (finish_info);
					break;
				}
				case VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_CANCELLABLE:
				{
					GIFunctionInfo* finish_info = NULL;
					GIFunctionInfo* _tmp76_ = NULL;
					GIFunctionInfo* _tmp77_ = NULL;
					GIFunctionInfo* _tmp78_ = NULL;
					_tmp76_ = fn_info;
					_tmp77_ = valadate_runner_gir_suite_info_get_finish (self, _tmp76_);
					finish_info = _tmp77_;
					_tmp78_ = finish_info;
					if (_tmp78_ != NULL) {
						void* _tmp79_ = NULL;
						GIFunctionInfo* _tmp80_ = NULL;
						void* _tmp81_ = NULL;
						void* _tmp82_ = NULL;
						GIFunctionInfo* _tmp83_ = NULL;
						void* _tmp84_ = NULL;
						GTestSuite* _tmp85_ = NULL;
						GIFunctionInfo* _tmp86_ = NULL;
						const gchar* _tmp87_ = NULL;
						gchar* _tmp88_ = NULL;
						gchar* _tmp89_ = NULL;
						_tmp80_ = fn_info;
						_tmp81_ = valadate_runner_gir_suite_info_get_fn_pointer (self, _tmp80_, &_inner_error_);
						_tmp79_ = _tmp81_;
						if (G_UNLIKELY (_inner_error_ != NULL)) {
							if (_inner_error_->domain == G_IINVOKE_ERROR) {
								g_propagate_error (error, _inner_error_);
								_g_base_info_unref0 (finish_info);
								_g_base_info_unref0 (fn_info);
								_vala_iterable_unref0 (_fn_info_list);
								_vala_iterable_unref0 (fn_infos);
								return;
							} else {
								_g_base_info_unref0 (finish_info);
								_g_base_info_unref0 (fn_info);
								_vala_iterable_unref0 (_fn_info_list);
								_vala_iterable_unref0 (fn_infos);
								g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
								g_clear_error (&_inner_error_);
								return;
							}
						}
						_tmp83_ = finish_info;
						_tmp84_ = valadate_runner_gir_suite_info_get_fn_pointer (self, _tmp83_, &_inner_error_);
						_tmp82_ = _tmp84_;
						if (G_UNLIKELY (_inner_error_ != NULL)) {
							if (_inner_error_->domain == G_IINVOKE_ERROR) {
								g_propagate_error (error, _inner_error_);
								_g_base_info_unref0 (finish_info);
								_g_base_info_unref0 (fn_info);
								_vala_iterable_unref0 (_fn_info_list);
								_vala_iterable_unref0 (fn_infos);
								return;
							} else {
								_g_base_info_unref0 (finish_info);
								_g_base_info_unref0 (fn_info);
								_vala_iterable_unref0 (_fn_info_list);
								_vala_iterable_unref0 (fn_infos);
								g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
								g_clear_error (&_inner_error_);
								return;
							}
						}
						_tmp85_ = suite;
						_tmp86_ = fn_info;
						_tmp87_ = g_base_info_get_name ((GIBaseInfo*) _tmp86_);
						_tmp88_ = string_substring (_tmp87_, (glong) 5, (glong) -1);
						_tmp89_ = _tmp88_;
						valadate_runner_suite_info_add_test ((ValadateRunnerSuiteInfo*) self, _tmp85_, _tmp89_, _valadate_runner_test_marshal_cancellable_valadate_runner_test_marshaller, NULL, _tmp79_, _tmp82_);
						_g_free0 (_tmp89_);
					} else {
						GIObjectInfo* _tmp90_ = NULL;
						const gchar* _tmp91_ = NULL;
						GIObjectInfo* _tmp92_ = NULL;
						const gchar* _tmp93_ = NULL;
						GIFunctionInfo* _tmp94_ = NULL;
						const gchar* _tmp95_ = NULL;
						_tmp90_ = self->priv->fx_info;
						_tmp91_ = g_base_info_get_namespace ((GIBaseInfo*) _tmp90_);
						_tmp92_ = self->priv->fx_info;
						_tmp93_ = g_base_info_get_name ((GIBaseInfo*) _tmp92_);
						_tmp94_ = fn_info;
						_tmp95_ = g_base_info_get_name ((GIBaseInfo*) _tmp94_);
						g_warning ("girsuiteinfo.vala:79: %s.%s.%s looks like a cancellable async test, bu" \
"t matching finish method was not found.", _tmp91_, _tmp93_, _tmp95_);
					}
					_g_base_info_unref0 (finish_info);
					break;
				}
				default:
				{
					GIObjectInfo* _tmp96_ = NULL;
					const gchar* _tmp97_ = NULL;
					GIObjectInfo* _tmp98_ = NULL;
					const gchar* _tmp99_ = NULL;
					GIFunctionInfo* _tmp100_ = NULL;
					const gchar* _tmp101_ = NULL;
					_tmp96_ = self->priv->fx_info;
					_tmp97_ = g_base_info_get_namespace ((GIBaseInfo*) _tmp96_);
					_tmp98_ = self->priv->fx_info;
					_tmp99_ = g_base_info_get_name ((GIBaseInfo*) _tmp98_);
					_tmp100_ = fn_info;
					_tmp101_ = g_base_info_get_name ((GIBaseInfo*) _tmp100_);
					g_warning ("girsuiteinfo.vala:85: %s.%s.%s is named like a test, but it's signatur" \
"e is not of any supported type", _tmp97_, _tmp99_, _tmp101_);
					break;
				}
			}
			_g_base_info_unref0 (fn_info);
		}
		_vala_iterable_unref0 (_fn_info_list);
	}
	_vala_iterable_unref0 (fn_infos);
}


static void valadate_runner_gir_suite_info_gather_methods (ValadateRunnerGirSuiteInfo* self, GIObjectInfo* fx_info, ValaArrayList** fn_infos) {
	gboolean _tmp0_ = FALSE;
	gint n_funcs = 0;
	GIObjectInfo* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	GIObjectInfo* base_info = NULL;
	GIObjectInfo* _tmp22_ = NULL;
	GIObjectInfo* _tmp23_ = NULL;
	gboolean _tmp24_ = FALSE;
	GIObjectInfo* _tmp25_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (fx_info != NULL);
	g_return_if_fail (*fn_infos != NULL);
	_tmp0_ = valadate_runner_verbose;
	if (_tmp0_) {
		FILE* _tmp1_ = NULL;
		GIObjectInfo* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		_tmp1_ = stdout;
		_tmp2_ = fx_info;
		_tmp3_ = g_base_info_get_name ((GIBaseInfo*) _tmp2_);
		fprintf (_tmp1_, "        gathering methods in %s\n", _tmp3_);
	}
	_tmp4_ = fx_info;
	_tmp5_ = g_object_info_get_n_methods (_tmp4_);
	n_funcs = _tmp5_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp6_ = FALSE;
			_tmp6_ = TRUE;
			while (TRUE) {
				gint _tmp8_ = 0;
				gint _tmp9_ = 0;
				ValaArrayList* _tmp10_ = NULL;
				GIObjectInfo* _tmp11_ = NULL;
				gint _tmp12_ = 0;
				GIFunctionInfo* _tmp13_ = NULL;
				GIFunctionInfo* _tmp14_ = NULL;
				gboolean _tmp15_ = FALSE;
				if (!_tmp6_) {
					gint _tmp7_ = 0;
					_tmp7_ = i;
					i = _tmp7_ + 1;
				}
				_tmp6_ = FALSE;
				_tmp8_ = i;
				_tmp9_ = n_funcs;
				if (!(_tmp8_ < _tmp9_)) {
					break;
				}
				_tmp10_ = *fn_infos;
				_tmp11_ = fx_info;
				_tmp12_ = i;
				_tmp13_ = g_object_info_get_method (_tmp11_, _tmp12_);
				_tmp14_ = _tmp13_;
				vala_collection_add ((ValaCollection*) _tmp10_, _tmp14_);
				_g_base_info_unref0 (_tmp14_);
				_tmp15_ = valadate_runner_verbose;
				if (_tmp15_) {
					FILE* _tmp16_ = NULL;
					GIObjectInfo* _tmp17_ = NULL;
					gint _tmp18_ = 0;
					GIFunctionInfo* _tmp19_ = NULL;
					GIFunctionInfo* _tmp20_ = NULL;
					const gchar* _tmp21_ = NULL;
					_tmp16_ = stdout;
					_tmp17_ = fx_info;
					_tmp18_ = i;
					_tmp19_ = g_object_info_get_method (_tmp17_, _tmp18_);
					_tmp20_ = _tmp19_;
					_tmp21_ = g_base_info_get_name ((GIBaseInfo*) _tmp20_);
					fprintf (_tmp16_, "            found %s\n", _tmp21_);
					_g_base_info_unref0 (_tmp20_);
				}
			}
		}
	}
	_tmp22_ = fx_info;
	_tmp23_ = g_object_info_get_parent (_tmp22_);
	base_info = _tmp23_;
	_tmp25_ = base_info;
	if (_tmp25_ != NULL) {
		GIObjectInfo* _tmp26_ = NULL;
		GIInfoType _tmp27_ = 0;
		_tmp26_ = base_info;
		_tmp27_ = g_base_info_get_type ((GIBaseInfo*) _tmp26_);
		_tmp24_ = _tmp27_ == GI_INFO_TYPE_OBJECT;
	} else {
		_tmp24_ = FALSE;
	}
	if (_tmp24_) {
		GIObjectInfo* _tmp28_ = NULL;
		_tmp28_ = base_info;
		valadate_runner_gir_suite_info_gather_methods (self, _tmp28_, fn_infos);
	}
	_g_base_info_unref0 (base_info);
}


static gboolean valadate_runner_gir_suite_info_is_generator (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* fn) {
	gboolean result = FALSE;
	GIFunctionInfo* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	GIFunctionInfo* _tmp3_ = NULL;
	GIFunctionInfo* _tmp4_ = NULL;
	GIInfoType _tmp5_ = 0;
	GIFunctionInfo* _tmp6_ = NULL;
	GIFunctionInfoFlags _tmp7_ = 0;
	GITypeInfo* return_type = NULL;
	GIFunctionInfo* _tmp8_ = NULL;
	GITypeInfo* _tmp9_ = NULL;
	GITypeInfo* _tmp10_ = NULL;
	GITypeTag _tmp11_ = 0;
	GIBaseInfo* return_iface = NULL;
	GITypeInfo* _tmp12_ = NULL;
	GIBaseInfo* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	gboolean _tmp15_ = FALSE;
	GIBaseInfo* _tmp16_ = NULL;
	GIFunctionInfo* _tmp21_ = NULL;
	gint _tmp22_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = fn;
	_tmp1_ = g_base_info_get_name ((GIBaseInfo*) _tmp0_);
	_tmp2_ = g_str_has_prefix (_tmp1_, "generate_");
	if (!_tmp2_) {
		result = FALSE;
		return result;
	}
	_tmp3_ = fn;
	g_return_val_if_fail (_tmp3_ != NULL, FALSE);
	_tmp4_ = fn;
	_tmp5_ = g_base_info_get_type ((GIBaseInfo*) _tmp4_);
	g_return_val_if_fail (_tmp5_ == GI_INFO_TYPE_FUNCTION, FALSE);
	_tmp6_ = fn;
	_tmp7_ = g_function_info_get_flags (_tmp6_);
	g_return_val_if_fail (_tmp7_ == 0, FALSE);
	_tmp8_ = fn;
	_tmp9_ = g_callable_info_get_return_type ((GICallableInfo*) _tmp8_);
	return_type = _tmp9_;
	_tmp10_ = return_type;
	_tmp11_ = g_type_info_get_tag (_tmp10_);
	g_return_val_if_fail (_tmp11_ == GI_TYPE_TAG_INTERFACE, FALSE);
	_tmp12_ = return_type;
	_tmp13_ = g_type_info_get_interface (_tmp12_);
	return_iface = _tmp13_;
	_tmp16_ = return_iface;
	if (_tmp16_ != NULL) {
		GIBaseInfo* _tmp17_ = NULL;
		const gchar* _tmp18_ = NULL;
		_tmp17_ = return_iface;
		_tmp18_ = g_base_info_get_name (_tmp17_);
		_tmp15_ = g_strcmp0 (_tmp18_, "ValueArray") == 0;
	} else {
		_tmp15_ = FALSE;
	}
	if (_tmp15_) {
		GIBaseInfo* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		_tmp19_ = return_iface;
		_tmp20_ = g_base_info_get_namespace (_tmp19_);
		_tmp14_ = g_strcmp0 (_tmp20_, "GLib") == 0;
	} else {
		_tmp14_ = FALSE;
	}
	g_return_val_if_fail (_tmp14_, FALSE);
	_tmp21_ = fn;
	_tmp22_ = g_callable_info_get_n_args ((GICallableInfo*) _tmp21_);
	g_return_val_if_fail (_tmp22_ == 0, FALSE);
	result = TRUE;
	_g_base_info_unref0 (return_iface);
	_g_base_info_unref0 (return_type);
	return result;
}


static gboolean valadate_runner_gir_suite_info_is_test (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* method) {
	gboolean result = FALSE;
	GIFunctionInfo* _tmp0_ = NULL;
	GIFunctionInfoFlags _tmp1_ = 0;
	GIFunctionInfo* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	GIFunctionInfo* _tmp5_ = NULL;
	GITypeInfo* _tmp6_ = NULL;
	GITypeInfo* _tmp7_ = NULL;
	GITypeTag _tmp8_ = 0;
	gboolean _tmp9_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (method != NULL, FALSE);
	_tmp0_ = method;
	_tmp1_ = g_function_info_get_flags (_tmp0_);
	if ((_tmp1_ & GI_FUNCTION_IS_METHOD) == 0) {
		result = FALSE;
		return result;
	}
	_tmp2_ = method;
	_tmp3_ = g_base_info_get_name ((GIBaseInfo*) _tmp2_);
	_tmp4_ = g_str_has_prefix (_tmp3_, "test_");
	if (!_tmp4_) {
		result = FALSE;
		return result;
	}
	_tmp5_ = method;
	_tmp6_ = g_callable_info_get_return_type ((GICallableInfo*) _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_type_info_get_tag (_tmp7_);
	_tmp9_ = _tmp8_ != GI_TYPE_TAG_VOID;
	_g_base_info_unref0 (_tmp7_);
	if (_tmp9_) {
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


static ValadateRunnerGirSuiteInfoTestType valadate_runner_gir_suite_info_test_type (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* method) {
	ValadateRunnerGirSuiteInfoTestType result = 0;
	GIFunctionInfo* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GIFunctionInfo* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GIFunctionInfo* _tmp27_ = NULL;
	gint _tmp28_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (method != NULL, 0);
	_tmp0_ = method;
	_tmp1_ = g_callable_info_get_n_args ((GICallableInfo*) _tmp0_);
	if (_tmp1_ == 0) {
		result = VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_SYNC;
		return result;
	}
	_tmp2_ = method;
	_tmp3_ = g_callable_info_get_n_args ((GICallableInfo*) _tmp2_);
	if (_tmp3_ == 2) {
		GITypeInfo* arg0 = NULL;
		GIFunctionInfo* _tmp4_ = NULL;
		GIArgInfo* _tmp5_ = NULL;
		GIArgInfo* _tmp6_ = NULL;
		GITypeInfo* _tmp7_ = NULL;
		GITypeInfo* _tmp8_ = NULL;
		GITypeInfo* arg1 = NULL;
		GIFunctionInfo* _tmp9_ = NULL;
		GIArgInfo* _tmp10_ = NULL;
		GIArgInfo* _tmp11_ = NULL;
		GITypeInfo* _tmp12_ = NULL;
		GITypeInfo* _tmp13_ = NULL;
		gboolean _tmp14_ = FALSE;
		gboolean _tmp15_ = FALSE;
		gboolean _tmp16_ = FALSE;
		GITypeInfo* _tmp17_ = NULL;
		GITypeTag _tmp18_ = 0;
		_tmp4_ = method;
		_tmp5_ = g_callable_info_get_arg ((GICallableInfo*) _tmp4_, 0);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_arg_info_get_type (_tmp6_);
		_tmp8_ = _tmp7_;
		_g_base_info_unref0 (_tmp6_);
		arg0 = _tmp8_;
		_tmp9_ = method;
		_tmp10_ = g_callable_info_get_arg ((GICallableInfo*) _tmp9_, 1);
		_tmp11_ = _tmp10_;
		_tmp12_ = g_arg_info_get_type (_tmp11_);
		_tmp13_ = _tmp12_;
		_g_base_info_unref0 (_tmp11_);
		arg1 = _tmp13_;
		_tmp17_ = arg0;
		_tmp18_ = g_type_info_get_tag (_tmp17_);
		if (_tmp18_ != GI_TYPE_TAG_INTERFACE) {
			_tmp16_ = TRUE;
		} else {
			GITypeInfo* _tmp19_ = NULL;
			GIBaseInfo* _tmp20_ = NULL;
			GIBaseInfo* _tmp21_ = NULL;
			const gchar* _tmp22_ = NULL;
			_tmp19_ = arg0;
			_tmp20_ = g_type_info_get_interface (_tmp19_);
			_tmp21_ = _tmp20_;
			_tmp22_ = g_base_info_get_name (_tmp21_);
			_tmp16_ = g_strcmp0 (_tmp22_, "AsyncReadyCallback") != 0;
			_g_base_info_unref0 (_tmp21_);
		}
		if (_tmp16_) {
			_tmp15_ = TRUE;
		} else {
			GITypeInfo* _tmp23_ = NULL;
			GITypeTag _tmp24_ = 0;
			_tmp23_ = arg1;
			_tmp24_ = g_type_info_get_tag (_tmp23_);
			_tmp15_ = _tmp24_ != GI_TYPE_TAG_VOID;
		}
		if (_tmp15_) {
			_tmp14_ = TRUE;
		} else {
			GITypeInfo* _tmp25_ = NULL;
			gboolean _tmp26_ = FALSE;
			_tmp25_ = arg1;
			_tmp26_ = g_type_info_is_pointer (_tmp25_);
			_tmp14_ = !_tmp26_;
		}
		if (_tmp14_) {
			result = VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_NONE;
			_g_base_info_unref0 (arg1);
			_g_base_info_unref0 (arg0);
			return result;
		}
		result = VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_ASYNC;
		_g_base_info_unref0 (arg1);
		_g_base_info_unref0 (arg0);
		return result;
	}
	_tmp27_ = method;
	_tmp28_ = g_callable_info_get_n_args ((GICallableInfo*) _tmp27_);
	if (_tmp28_ == 3) {
		GITypeInfo* arg0 = NULL;
		GIFunctionInfo* _tmp29_ = NULL;
		GIArgInfo* _tmp30_ = NULL;
		GIArgInfo* _tmp31_ = NULL;
		GITypeInfo* _tmp32_ = NULL;
		GITypeInfo* _tmp33_ = NULL;
		GITypeInfo* arg1 = NULL;
		GIFunctionInfo* _tmp34_ = NULL;
		GIArgInfo* _tmp35_ = NULL;
		GIArgInfo* _tmp36_ = NULL;
		GITypeInfo* _tmp37_ = NULL;
		GITypeInfo* _tmp38_ = NULL;
		GITypeInfo* arg2 = NULL;
		GIFunctionInfo* _tmp39_ = NULL;
		GIArgInfo* _tmp40_ = NULL;
		GIArgInfo* _tmp41_ = NULL;
		GITypeInfo* _tmp42_ = NULL;
		GITypeInfo* _tmp43_ = NULL;
		gboolean _tmp44_ = FALSE;
		gboolean _tmp45_ = FALSE;
		gboolean _tmp46_ = FALSE;
		gboolean _tmp47_ = FALSE;
		gboolean _tmp48_ = FALSE;
		GITypeInfo* _tmp49_ = NULL;
		GITypeTag _tmp50_ = 0;
		_tmp29_ = method;
		_tmp30_ = g_callable_info_get_arg ((GICallableInfo*) _tmp29_, 0);
		_tmp31_ = _tmp30_;
		_tmp32_ = g_arg_info_get_type (_tmp31_);
		_tmp33_ = _tmp32_;
		_g_base_info_unref0 (_tmp31_);
		arg0 = _tmp33_;
		_tmp34_ = method;
		_tmp35_ = g_callable_info_get_arg ((GICallableInfo*) _tmp34_, 1);
		_tmp36_ = _tmp35_;
		_tmp37_ = g_arg_info_get_type (_tmp36_);
		_tmp38_ = _tmp37_;
		_g_base_info_unref0 (_tmp36_);
		arg1 = _tmp38_;
		_tmp39_ = method;
		_tmp40_ = g_callable_info_get_arg ((GICallableInfo*) _tmp39_, 2);
		_tmp41_ = _tmp40_;
		_tmp42_ = g_arg_info_get_type (_tmp41_);
		_tmp43_ = _tmp42_;
		_g_base_info_unref0 (_tmp41_);
		arg2 = _tmp43_;
		_tmp49_ = arg0;
		_tmp50_ = g_type_info_get_tag (_tmp49_);
		if (_tmp50_ != GI_TYPE_TAG_INTERFACE) {
			_tmp48_ = TRUE;
		} else {
			GITypeInfo* _tmp51_ = NULL;
			GIBaseInfo* _tmp52_ = NULL;
			GIBaseInfo* _tmp53_ = NULL;
			const gchar* _tmp54_ = NULL;
			_tmp51_ = arg0;
			_tmp52_ = g_type_info_get_interface (_tmp51_);
			_tmp53_ = _tmp52_;
			_tmp54_ = g_base_info_get_name (_tmp53_);
			_tmp48_ = g_strcmp0 (_tmp54_, "Cancellable") != 0;
			_g_base_info_unref0 (_tmp53_);
		}
		if (_tmp48_) {
			_tmp47_ = TRUE;
		} else {
			GITypeInfo* _tmp55_ = NULL;
			GITypeTag _tmp56_ = 0;
			_tmp55_ = arg1;
			_tmp56_ = g_type_info_get_tag (_tmp55_);
			_tmp47_ = _tmp56_ != GI_TYPE_TAG_INTERFACE;
		}
		if (_tmp47_) {
			_tmp46_ = TRUE;
		} else {
			GITypeInfo* _tmp57_ = NULL;
			GIBaseInfo* _tmp58_ = NULL;
			GIBaseInfo* _tmp59_ = NULL;
			const gchar* _tmp60_ = NULL;
			_tmp57_ = arg1;
			_tmp58_ = g_type_info_get_interface (_tmp57_);
			_tmp59_ = _tmp58_;
			_tmp60_ = g_base_info_get_name (_tmp59_);
			_tmp46_ = g_strcmp0 (_tmp60_, "AsyncReadyCallback") != 0;
			_g_base_info_unref0 (_tmp59_);
		}
		if (_tmp46_) {
			_tmp45_ = TRUE;
		} else {
			GITypeInfo* _tmp61_ = NULL;
			GITypeTag _tmp62_ = 0;
			_tmp61_ = arg2;
			_tmp62_ = g_type_info_get_tag (_tmp61_);
			_tmp45_ = _tmp62_ != GI_TYPE_TAG_VOID;
		}
		if (_tmp45_) {
			_tmp44_ = TRUE;
		} else {
			GITypeInfo* _tmp63_ = NULL;
			gboolean _tmp64_ = FALSE;
			_tmp63_ = arg2;
			_tmp64_ = g_type_info_is_pointer (_tmp63_);
			_tmp44_ = !_tmp64_;
		}
		if (_tmp44_) {
			result = VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_NONE;
			_g_base_info_unref0 (arg2);
			_g_base_info_unref0 (arg1);
			_g_base_info_unref0 (arg0);
			return result;
		}
		result = VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_CANCELLABLE;
		_g_base_info_unref0 (arg2);
		_g_base_info_unref0 (arg1);
		_g_base_info_unref0 (arg0);
		return result;
	}
	result = VALADATE_RUNNER_GIR_SUITE_INFO_TEST_TYPE_NONE;
	return result;
}


static GIFunctionInfo* valadate_runner_gir_suite_info_get_finish (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* begin_info) {
	GIFunctionInfo* result = NULL;
	gchar* name = NULL;
	GIFunctionInfo* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	GIFunctionInfo* finish_info = NULL;
	GIObjectInfo* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	GIFunctionInfo* _tmp14_ = NULL;
	GIFunctionInfo* _tmp15_ = NULL;
	GIFunctionInfo* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	GITypeInfo* arg = NULL;
	GIFunctionInfo* _tmp18_ = NULL;
	GIArgInfo* _tmp19_ = NULL;
	GIArgInfo* _tmp20_ = NULL;
	GITypeInfo* _tmp21_ = NULL;
	GITypeInfo* _tmp22_ = NULL;
	GITypeInfo* _tmp23_ = NULL;
	GITypeTag _tmp24_ = 0;
	GITypeInfo* _tmp25_ = NULL;
	GIBaseInfo* _tmp26_ = NULL;
	GIBaseInfo* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	gboolean _tmp29_ = FALSE;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (begin_info != NULL, NULL);
	_tmp0_ = begin_info;
	_tmp1_ = g_base_info_get_name ((GIBaseInfo*) _tmp0_);
	_tmp2_ = g_strdup (_tmp1_);
	name = _tmp2_;
	_tmp3_ = name;
	_tmp4_ = g_str_has_suffix (_tmp3_, "_async");
	if (_tmp4_) {
		const gchar* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gchar* _tmp9_ = NULL;
		_tmp5_ = name;
		_tmp6_ = name;
		_tmp7_ = strlen (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = string_substring (_tmp5_, (glong) 0, (glong) (_tmp8_ - 5));
		_g_free0 (name);
		name = _tmp9_;
	}
	_tmp10_ = name;
	_tmp11_ = g_strconcat (_tmp10_, "_finish", NULL);
	_g_free0 (name);
	name = _tmp11_;
	_tmp12_ = self->priv->fx_info;
	_tmp13_ = name;
	_tmp14_ = g_object_info_find_method (_tmp12_, _tmp13_);
	finish_info = _tmp14_;
	_tmp15_ = finish_info;
	if (_tmp15_ == NULL) {
		result = NULL;
		_g_base_info_unref0 (finish_info);
		_g_free0 (name);
		return result;
	}
	_tmp16_ = finish_info;
	_tmp17_ = g_callable_info_get_n_args ((GICallableInfo*) _tmp16_);
	if (_tmp17_ != 1) {
		result = NULL;
		_g_base_info_unref0 (finish_info);
		_g_free0 (name);
		return result;
	}
	_tmp18_ = finish_info;
	_tmp19_ = g_callable_info_get_arg ((GICallableInfo*) _tmp18_, 0);
	_tmp20_ = _tmp19_;
	_tmp21_ = g_arg_info_get_type (_tmp20_);
	_tmp22_ = _tmp21_;
	_g_base_info_unref0 (_tmp20_);
	arg = _tmp22_;
	_tmp23_ = arg;
	_tmp24_ = g_type_info_get_tag (_tmp23_);
	if (_tmp24_ != GI_TYPE_TAG_INTERFACE) {
		result = NULL;
		_g_base_info_unref0 (arg);
		_g_base_info_unref0 (finish_info);
		_g_free0 (name);
		return result;
	}
	_tmp25_ = arg;
	_tmp26_ = g_type_info_get_interface (_tmp25_);
	_tmp27_ = _tmp26_;
	_tmp28_ = g_base_info_get_name (_tmp27_);
	_tmp29_ = g_strcmp0 (_tmp28_, "AsyncResult") != 0;
	_g_base_info_unref0 (_tmp27_);
	if (_tmp29_) {
		result = NULL;
		_g_base_info_unref0 (arg);
		_g_base_info_unref0 (finish_info);
		_g_free0 (name);
		return result;
	}
	result = finish_info;
	_g_base_info_unref0 (arg);
	_g_free0 (name);
	return result;
}


static void* valadate_runner_gir_suite_info_get_fn_pointer (ValadateRunnerGirSuiteInfo* self, GIFunctionInfo* fn_info, GError** error) {
	void* result = NULL;
	gchar* symname = NULL;
	GIFunctionInfo* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	void* symbol = NULL;
	GIFunctionInfo* _tmp3_ = NULL;
	GITypelib* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	void* _tmp11_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (fn_info != NULL, NULL);
	_tmp0_ = fn_info;
	_tmp1_ = g_function_info_get_symbol (_tmp0_);
	_tmp2_ = g_strdup (_tmp1_);
	symname = _tmp2_;
	_tmp3_ = fn_info;
	_tmp4_ = g_base_info_get_typelib ((GIBaseInfo*) _tmp3_);
	_tmp5_ = symname;
	_tmp7_ = g_typelib_symbol (_tmp4_, _tmp5_, &_tmp6_);
	symbol = _tmp6_;
	if (!_tmp7_) {
		const gchar* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		GError* _tmp10_ = NULL;
		_tmp8_ = symname;
		_tmp9_ = g_module_error ();
		_tmp10_ = g_error_new (G_IINVOKE_ERROR, G_INVOKE_ERROR_SYMBOL_NOT_FOUND, "Could not find %s: %s\n", _tmp8_, _tmp9_);
		_inner_error_ = _tmp10_;
		if (_inner_error_->domain == G_IINVOKE_ERROR) {
			g_propagate_error (error, _inner_error_);
			_g_free0 (symname);
			return NULL;
		} else {
			_g_free0 (symname);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp11_ = symbol;
	result = _tmp11_;
	_g_free0 (symname);
	return result;
}


static void valadate_runner_gir_suite_info_class_init (ValadateRunnerGirSuiteInfoClass * klass) {
	valadate_runner_gir_suite_info_parent_class = g_type_class_peek_parent (klass);
	((ValadateRunnerSuiteInfoClass *) klass)->finalize = valadate_runner_gir_suite_info_finalize;
	g_type_class_add_private (klass, sizeof (ValadateRunnerGirSuiteInfoPrivate));
}


static void valadate_runner_gir_suite_info_instance_init (ValadateRunnerGirSuiteInfo * self) {
	self->priv = VALADATE_RUNNER_GIR_SUITE_INFO_GET_PRIVATE (self);
}


static void valadate_runner_gir_suite_info_finalize (ValadateRunnerSuiteInfo* obj) {
	ValadateRunnerGirSuiteInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALADATE_RUNNER_TYPE_GIR_SUITE_INFO, ValadateRunnerGirSuiteInfo);
	_g_base_info_unref0 (self->priv->fx_info);
	VALADATE_RUNNER_SUITE_INFO_CLASS (valadate_runner_gir_suite_info_parent_class)->finalize (obj);
}


GType valadate_runner_gir_suite_info_get_type (void) {
	static volatile gsize valadate_runner_gir_suite_info_type_id__volatile = 0;
	if (g_once_init_enter (&valadate_runner_gir_suite_info_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValadateRunnerGirSuiteInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valadate_runner_gir_suite_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValadateRunnerGirSuiteInfo), 0, (GInstanceInitFunc) valadate_runner_gir_suite_info_instance_init, NULL };
		GType valadate_runner_gir_suite_info_type_id;
		valadate_runner_gir_suite_info_type_id = g_type_register_static (VALADATE_RUNNER_TYPE_SUITE_INFO, "ValadateRunnerGirSuiteInfo", &g_define_type_info, 0);
		g_once_init_leave (&valadate_runner_gir_suite_info_type_id__volatile, valadate_runner_gir_suite_info_type_id);
	}
	return valadate_runner_gir_suite_info_type_id__volatile;
}



