/* suiteinfo.c generated by valac 0.30.0, the Vala compiler
 * generated from suiteinfo.vala, do not modify */

/*
 * Valadate - Unit testing library for GObject-based libraries.
 * Copyright (C) 2009  Jan Hudec <bulb@ucw.cz>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "libvaladate.h"
#include <gobject/gvaluecollector.h>


#define VALADATE_RUNNER_TYPE_PARAM_INFO (valadate_runner_param_info_get_type ())
#define VALADATE_RUNNER_PARAM_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_PARAM_INFO, ValadateRunnerParamInfo))
#define VALADATE_RUNNER_PARAM_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_PARAM_INFO, ValadateRunnerParamInfoClass))
#define VALADATE_RUNNER_IS_PARAM_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_PARAM_INFO))
#define VALADATE_RUNNER_IS_PARAM_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_PARAM_INFO))
#define VALADATE_RUNNER_PARAM_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_PARAM_INFO, ValadateRunnerParamInfoClass))

typedef struct _ValadateRunnerParamInfo ValadateRunnerParamInfo;
typedef struct _ValadateRunnerParamInfoClass ValadateRunnerParamInfoClass;
typedef struct _ValadateRunnerParamInfoPrivate ValadateRunnerParamInfoPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_value_array_free0(var) ((var == NULL) ? NULL : (var = (g_value_array_free (var), NULL)))
typedef struct _ValadateRunnerParamSpecParamInfo ValadateRunnerParamSpecParamInfo;

#define VALADATE_RUNNER_TYPE_SUITE_INFO (valadate_runner_suite_info_get_type ())
#define VALADATE_RUNNER_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfo))
#define VALADATE_RUNNER_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoClass))
#define VALADATE_RUNNER_IS_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO))
#define VALADATE_RUNNER_IS_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_SUITE_INFO))
#define VALADATE_RUNNER_SUITE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoClass))

typedef struct _ValadateRunnerSuiteInfo ValadateRunnerSuiteInfo;
typedef struct _ValadateRunnerSuiteInfoClass ValadateRunnerSuiteInfoClass;
typedef struct _ValadateRunnerSuiteInfoPrivate ValadateRunnerSuiteInfoPrivate;

#define VALADATE_RUNNER_TYPE_TEST_INFO (valadate_runner_test_info_get_type ())
#define VALADATE_RUNNER_TEST_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_TEST_INFO, ValadateRunnerTestInfo))
#define VALADATE_RUNNER_TEST_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_TEST_INFO, ValadateRunnerTestInfoClass))
#define VALADATE_RUNNER_IS_TEST_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_TEST_INFO))
#define VALADATE_RUNNER_IS_TEST_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_TEST_INFO))
#define VALADATE_RUNNER_TEST_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_TEST_INFO, ValadateRunnerTestInfoClass))

typedef struct _ValadateRunnerTestInfo ValadateRunnerTestInfo;
typedef struct _ValadateRunnerTestInfoClass ValadateRunnerTestInfoClass;
#define _g_type_class_unref0(var) ((var == NULL) ? NULL : (var = (g_type_class_unref (var), NULL)))
#define __g_slist_free__valadate_runner_param_info_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__valadate_runner_param_info_unref0_ (var), NULL)))
#define __g_slist_free__valadate_runner_test_info_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__valadate_runner_test_info_unref0_ (var), NULL)))
#define _valadate_runner_suite_info_unref0(var) ((var == NULL) ? NULL : (var = (valadate_runner_suite_info_unref (var), NULL)))
#define _valadate_runner_test_info_unref0(var) ((var == NULL) ? NULL : (var = (valadate_runner_test_info_unref (var), NULL)))
#define _valadate_runner_param_info_unref0(var) ((var == NULL) ? NULL : (var = (valadate_runner_param_info_unref (var), NULL)))
typedef struct _ValadateRunnerParamSpecSuiteInfo ValadateRunnerParamSpecSuiteInfo;

typedef GValueArray* (*ValadateRunnerGenerator) (void* user_data);
struct _ValadateRunnerParamInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValadateRunnerParamInfoPrivate * priv;
	gchar* name;
	GValueArray* values;
};

struct _ValadateRunnerParamInfoClass {
	GTypeClass parent_class;
	void (*finalize) (ValadateRunnerParamInfo *self);
};

struct _ValadateRunnerParamSpecParamInfo {
	GParamSpec parent_instance;
};

struct _ValadateRunnerSuiteInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValadateRunnerSuiteInfoPrivate * priv;
};

struct _ValadateRunnerSuiteInfoClass {
	GTypeClass parent_class;
	void (*finalize) (ValadateRunnerSuiteInfo *self);
};

struct _ValadateRunnerSuiteInfoPrivate {
	GType type;
	GObjectClass* klass;
	GSList* parameters;
	GSList* tests;
};

typedef enum  {
	VALADATE_RUNNER_RUNNER_ERROR_UNRECOGNIZED_FILE,
	VALADATE_RUNNER_RUNNER_ERROR_CANNOT_READ,
	VALADATE_RUNNER_RUNNER_ERROR_COMPILATION_FAILED,
	VALADATE_RUNNER_RUNNER_ERROR_TYPE_NOT_LOADED,
	VALADATE_RUNNER_RUNNER_ERROR_NOT_FOUND,
	VALADATE_RUNNER_RUNNER_ERROR_VAPI_ERROR
} ValadateRunnerRunnerError;
#define VALADATE_RUNNER_RUNNER_ERROR valadate_runner_runner_error_quark ()
typedef void (*ValadateRunnerTestMarshaller) (ValadateFixture* fixture, void* arg1, void* arg2, void* user_data);
struct _ValadateRunnerParamSpecSuiteInfo {
	GParamSpec parent_instance;
};


static gpointer valadate_runner_param_info_parent_class = NULL;
static gpointer valadate_runner_suite_info_parent_class = NULL;
extern gboolean valadate_runner_verbose;

gpointer valadate_runner_param_info_ref (gpointer instance);
void valadate_runner_param_info_unref (gpointer instance);
GParamSpec* valadate_runner_param_spec_param_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void valadate_runner_value_set_param_info (GValue* value, gpointer v_object);
void valadate_runner_value_take_param_info (GValue* value, gpointer v_object);
gpointer valadate_runner_value_get_param_info (const GValue* value);
GType valadate_runner_param_info_get_type (void) G_GNUC_CONST;
enum  {
	VALADATE_RUNNER_PARAM_INFO_DUMMY_PROPERTY
};
ValadateRunnerParamInfo* valadate_runner_param_info_new (const gchar* name, ValadateRunnerGenerator gen, void* gen_target);
ValadateRunnerParamInfo* valadate_runner_param_info_construct (GType object_type, const gchar* name, ValadateRunnerGenerator gen, void* gen_target);
void valadate_runner_param_info_to_parameter (ValadateRunnerParamInfo* self, gint i, GParameter* result);
static void g_parameter_destroy (GParameter* self);
gchar* valadate_runner_param_info_to_name (ValadateRunnerParamInfo* self, gint i);
static void valadate_runner_param_info_finalize (ValadateRunnerParamInfo* obj);
gpointer valadate_runner_suite_info_ref (gpointer instance);
void valadate_runner_suite_info_unref (gpointer instance);
GParamSpec* valadate_runner_param_spec_suite_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void valadate_runner_value_set_suite_info (GValue* value, gpointer v_object);
void valadate_runner_value_take_suite_info (GValue* value, gpointer v_object);
gpointer valadate_runner_value_get_suite_info (const GValue* value);
GType valadate_runner_suite_info_get_type (void) G_GNUC_CONST;
gpointer valadate_runner_test_info_ref (gpointer instance);
void valadate_runner_test_info_unref (gpointer instance);
GParamSpec* valadate_runner_param_spec_test_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void valadate_runner_value_set_test_info (GValue* value, gpointer v_object);
void valadate_runner_value_take_test_info (GValue* value, gpointer v_object);
gpointer valadate_runner_value_get_test_info (const GValue* value);
GType valadate_runner_test_info_get_type (void) G_GNUC_CONST;
#define VALADATE_RUNNER_SUITE_INFO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoPrivate))
enum  {
	VALADATE_RUNNER_SUITE_INFO_DUMMY_PROPERTY
};
static void _valadate_runner_param_info_unref0_ (gpointer var);
static void _g_slist_free__valadate_runner_param_info_unref0_ (GSList* self);
static void _valadate_runner_test_info_unref0_ (gpointer var);
static void _g_slist_free__valadate_runner_test_info_unref0_ (GSList* self);
GQuark valadate_runner_runner_error_quark (void);
ValadateRunnerSuiteInfo* valadate_runner_suite_info_new (GType type, GError** error);
ValadateRunnerSuiteInfo* valadate_runner_suite_info_construct (GType object_type, GType type, GError** error);
void valadate_runner_suite_info_add_generator (ValadateRunnerSuiteInfo* self, const gchar* prop, ValadateRunnerGenerator gen, void* gen_target);
void valadate_runner_suite_info_add_test (ValadateRunnerSuiteInfo* self, GTestSuite* suite, const gchar* name, ValadateRunnerTestMarshaller marshaller, void* marshaller_target, void* arg1, void* arg2);
static void valadate_runner_suite_info_parametrize_test (ValadateRunnerSuiteInfo* self, GTestSuite* suite, ValadateRunnerTestMarshaller marshaller, void* marshaller_target, void* arg1, void* arg2, GSList* next_param, GParameter* prefix, int prefix_length1, const gchar* name);
static void g_parameter_copy (const GParameter* self, GParameter* dest);
static GParameter* _vala_array_dup1 (GParameter* self, int length);
ValadateRunnerTestInfo* valadate_runner_test_info_new (GType type, ValadateRunnerTestMarshaller marshaller, void* marshaller_target, void* arg1, void* arg2, GParameter* parameters, int parameters_length1);
ValadateRunnerTestInfo* valadate_runner_test_info_construct (GType object_type, GType type, ValadateRunnerTestMarshaller marshaller, void* marshaller_target, void* arg1, void* arg2, GParameter* parameters, int parameters_length1);
GTestCase* valadate_runner_test_info_make_case (ValadateRunnerTestInfo* self, const gchar* name);
static GParameter* _vala_array_dup2 (GParameter* self, int length);
static void _vala_array_add6 (GParameter** array, int* length, int* size, const GParameter* value);
static void _vala_GParameter_array_free (GParameter* array, gint array_length);
static void valadate_runner_suite_info_finalize (ValadateRunnerSuiteInfo* obj);


ValadateRunnerParamInfo* valadate_runner_param_info_construct (GType object_type, const gchar* name, ValadateRunnerGenerator gen, void* gen_target) {
	ValadateRunnerParamInfo* self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	ValadateRunnerGenerator _tmp2_ = NULL;
	void* _tmp2__target = NULL;
	GValueArray* _tmp3_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	self = (ValadateRunnerParamInfo*) g_type_create_instance (object_type);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->name);
	self->name = _tmp1_;
	_tmp2_ = gen;
	_tmp2__target = gen_target;
	_tmp3_ = _tmp2_ (_tmp2__target);
	_g_value_array_free0 (self->values);
	self->values = _tmp3_;
	return self;
}


ValadateRunnerParamInfo* valadate_runner_param_info_new (const gchar* name, ValadateRunnerGenerator gen, void* gen_target) {
	return valadate_runner_param_info_construct (VALADATE_RUNNER_TYPE_PARAM_INFO, name, gen, gen_target);
}


static void g_parameter_destroy (GParameter* self) {
	G_IS_VALUE (&(*self).value) ? (g_value_unset (&(*self).value), NULL) : NULL;
}


void valadate_runner_param_info_to_parameter (ValadateRunnerParamInfo* self, gint i, GParameter* result) {
	GParameter rv = {0};
	const gchar* _tmp0_ = NULL;
	GValueArray* _tmp1_ = NULL;
	GValue* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	gint _tmp3_ = 0;
	GValue _tmp4_ = {0};
	GValue _tmp5_ = {0};
	g_return_if_fail (self != NULL);
	memset (&rv, 0, sizeof (GParameter));
	_tmp0_ = self->name;
	rv.name = _tmp0_;
	_tmp1_ = self->values;
	_tmp2_ = _tmp1_->values;
	_tmp2__length1 = (gint) _tmp1_->n_values;
	_tmp3_ = i;
	_tmp4_ = _tmp2_[_tmp3_];
	if (G_IS_VALUE (&_tmp4_)) {
		g_value_init (&_tmp5_, G_VALUE_TYPE (&_tmp4_));
		g_value_copy (&_tmp4_, &_tmp5_);
	} else {
		_tmp5_ = _tmp4_;
	}
	G_IS_VALUE (&rv.value) ? (g_value_unset (&rv.value), NULL) : NULL;
	rv.value = _tmp5_;
	*result = rv;
	return;
}


gchar* valadate_runner_param_info_to_name (ValadateRunnerParamInfo* self, gint i) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->name;
	_tmp1_ = i;
	_tmp2_ = g_strdup_printf (",%s=%i", _tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


static void valadate_runner_value_param_info_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void valadate_runner_value_param_info_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		valadate_runner_param_info_unref (value->data[0].v_pointer);
	}
}


static void valadate_runner_value_param_info_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = valadate_runner_param_info_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer valadate_runner_value_param_info_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* valadate_runner_value_param_info_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ValadateRunnerParamInfo* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = valadate_runner_param_info_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* valadate_runner_value_param_info_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ValadateRunnerParamInfo** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = valadate_runner_param_info_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* valadate_runner_param_spec_param_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ValadateRunnerParamSpecParamInfo* spec;
	g_return_val_if_fail (g_type_is_a (object_type, VALADATE_RUNNER_TYPE_PARAM_INFO), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer valadate_runner_value_get_param_info (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALADATE_RUNNER_TYPE_PARAM_INFO), NULL);
	return value->data[0].v_pointer;
}


void valadate_runner_value_set_param_info (GValue* value, gpointer v_object) {
	ValadateRunnerParamInfo* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALADATE_RUNNER_TYPE_PARAM_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALADATE_RUNNER_TYPE_PARAM_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		valadate_runner_param_info_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		valadate_runner_param_info_unref (old);
	}
}


void valadate_runner_value_take_param_info (GValue* value, gpointer v_object) {
	ValadateRunnerParamInfo* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALADATE_RUNNER_TYPE_PARAM_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALADATE_RUNNER_TYPE_PARAM_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		valadate_runner_param_info_unref (old);
	}
}


static void valadate_runner_param_info_class_init (ValadateRunnerParamInfoClass * klass) {
	valadate_runner_param_info_parent_class = g_type_class_peek_parent (klass);
	((ValadateRunnerParamInfoClass *) klass)->finalize = valadate_runner_param_info_finalize;
}


static void valadate_runner_param_info_instance_init (ValadateRunnerParamInfo * self) {
	self->ref_count = 1;
}


static void valadate_runner_param_info_finalize (ValadateRunnerParamInfo* obj) {
	ValadateRunnerParamInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALADATE_RUNNER_TYPE_PARAM_INFO, ValadateRunnerParamInfo);
	g_signal_handlers_destroy (self);
	_g_free0 (self->name);
	_g_value_array_free0 (self->values);
}


GType valadate_runner_param_info_get_type (void) {
	static volatile gsize valadate_runner_param_info_type_id__volatile = 0;
	if (g_once_init_enter (&valadate_runner_param_info_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { valadate_runner_value_param_info_init, valadate_runner_value_param_info_free_value, valadate_runner_value_param_info_copy_value, valadate_runner_value_param_info_peek_pointer, "p", valadate_runner_value_param_info_collect_value, "p", valadate_runner_value_param_info_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ValadateRunnerParamInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valadate_runner_param_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValadateRunnerParamInfo), 0, (GInstanceInitFunc) valadate_runner_param_info_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType valadate_runner_param_info_type_id;
		valadate_runner_param_info_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ValadateRunnerParamInfo", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&valadate_runner_param_info_type_id__volatile, valadate_runner_param_info_type_id);
	}
	return valadate_runner_param_info_type_id__volatile;
}


gpointer valadate_runner_param_info_ref (gpointer instance) {
	ValadateRunnerParamInfo* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void valadate_runner_param_info_unref (gpointer instance) {
	ValadateRunnerParamInfo* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		VALADATE_RUNNER_PARAM_INFO_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _valadate_runner_param_info_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (valadate_runner_param_info_unref (var), NULL));
}


static void _g_slist_free__valadate_runner_param_info_unref0_ (GSList* self) {
	g_slist_foreach (self, (GFunc) _valadate_runner_param_info_unref0_, NULL);
	g_slist_free (self);
}


static void _valadate_runner_test_info_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (valadate_runner_test_info_unref (var), NULL));
}


static void _g_slist_free__valadate_runner_test_info_unref0_ (GSList* self) {
	g_slist_foreach (self, (GFunc) _valadate_runner_test_info_unref0_, NULL);
	g_slist_free (self);
}


ValadateRunnerSuiteInfo* valadate_runner_suite_info_construct (GType object_type, GType type, GError** error) {
	ValadateRunnerSuiteInfo* self = NULL;
	GType _tmp0_ = 0UL;
	gboolean _tmp1_ = FALSE;
	GType _tmp5_ = 0UL;
	GType _tmp6_ = 0UL;
	GTypeClass* _tmp7_ = NULL;
	GError * _inner_error_ = NULL;
	self = (ValadateRunnerSuiteInfo*) g_type_create_instance (object_type);
	_tmp0_ = type;
	_tmp1_ = g_type_is_a (_tmp0_, G_TYPE_OBJECT);
	if (!_tmp1_) {
		GType _tmp2_ = 0UL;
		const gchar* _tmp3_ = NULL;
		GError* _tmp4_ = NULL;
		_tmp2_ = type;
		_tmp3_ = g_type_name (_tmp2_);
		_tmp4_ = g_error_new (VALADATE_RUNNER_RUNNER_ERROR, VALADATE_RUNNER_RUNNER_ERROR_TYPE_NOT_LOADED, "Type %s is not an Object", _tmp3_);
		_inner_error_ = _tmp4_;
		if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
			g_propagate_error (error, _inner_error_);
			_valadate_runner_suite_info_unref0 (self);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp5_ = type;
	self->priv->type = _tmp5_;
	_tmp6_ = type;
	_tmp7_ = g_type_class_ref (_tmp6_);
	_g_type_class_unref0 (self->priv->klass);
	self->priv->klass = (GObjectClass*) _tmp7_;
	return self;
}


ValadateRunnerSuiteInfo* valadate_runner_suite_info_new (GType type, GError** error) {
	return valadate_runner_suite_info_construct (VALADATE_RUNNER_TYPE_SUITE_INFO, type, error);
}


void valadate_runner_suite_info_add_generator (ValadateRunnerSuiteInfo* self, const gchar* prop, ValadateRunnerGenerator gen, void* gen_target) {
	GParamSpec* pspec = NULL;
	GObjectClass* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GParamSpec* _tmp2_ = NULL;
	GParamSpec* _tmp3_ = NULL;
	const gchar* _tmp23_ = NULL;
	ValadateRunnerGenerator _tmp24_ = NULL;
	void* _tmp24__target = NULL;
	ValadateRunnerParamInfo* _tmp25_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (prop != NULL);
	_tmp0_ = self->priv->klass;
	_tmp1_ = prop;
	_tmp2_ = g_object_class_find_property (_tmp0_, _tmp1_);
	pspec = _tmp2_;
	_tmp3_ = pspec;
	if (_tmp3_ == NULL) {
		gboolean _tmp4_ = FALSE;
		_tmp4_ = valadate_runner_verbose;
		if (_tmp4_) {
			FILE* _tmp5_ = NULL;
			const gchar* _tmp6_ = NULL;
			GType _tmp7_ = 0UL;
			const gchar* _tmp8_ = NULL;
			_tmp5_ = stdout;
			_tmp6_ = prop;
			_tmp7_ = self->priv->type;
			_tmp8_ = g_type_name (_tmp7_);
			fprintf (_tmp5_, "No property found for generator generate_%s in type %s\n", _tmp6_, _tmp8_);
		}
		return;
	}
	{
		GSList* i = NULL;
		GSList* _tmp9_ = NULL;
		_tmp9_ = self->priv->parameters;
		i = _tmp9_;
		{
			gboolean _tmp10_ = FALSE;
			_tmp10_ = TRUE;
			while (TRUE) {
				GSList* _tmp13_ = NULL;
				GSList* _tmp14_ = NULL;
				gconstpointer _tmp15_ = NULL;
				const gchar* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				if (!_tmp10_) {
					GSList* _tmp11_ = NULL;
					GSList* _tmp12_ = NULL;
					_tmp11_ = i;
					_tmp12_ = _tmp11_->next;
					i = _tmp12_;
				}
				_tmp10_ = FALSE;
				_tmp13_ = i;
				if (!(_tmp13_ != NULL)) {
					break;
				}
				_tmp14_ = i;
				_tmp15_ = _tmp14_->data;
				_tmp16_ = ((ValadateRunnerParamInfo*) _tmp15_)->name;
				_tmp17_ = prop;
				if (g_strcmp0 (_tmp16_, _tmp17_) == 0) {
					gboolean _tmp18_ = FALSE;
					_tmp18_ = valadate_runner_verbose;
					if (_tmp18_) {
						FILE* _tmp19_ = NULL;
						const gchar* _tmp20_ = NULL;
						GType _tmp21_ = 0UL;
						const gchar* _tmp22_ = NULL;
						_tmp19_ = stdout;
						_tmp20_ = prop;
						_tmp21_ = self->priv->type;
						_tmp22_ = g_type_name (_tmp21_);
						fprintf (_tmp19_, "Multiple generators generate_%s in type %s\n", _tmp20_, _tmp22_);
					}
					return;
				}
			}
		}
	}
	_tmp23_ = prop;
	_tmp24_ = gen;
	_tmp24__target = gen_target;
	_tmp25_ = valadate_runner_param_info_new (_tmp23_, _tmp24_, _tmp24__target);
	self->priv->parameters = g_slist_prepend (self->priv->parameters, _tmp25_);
}


void valadate_runner_suite_info_add_test (ValadateRunnerSuiteInfo* self, GTestSuite* suite, const gchar* name, ValadateRunnerTestMarshaller marshaller, void* marshaller_target, void* arg1, void* arg2) {
	GTestSuite* _tmp0_ = NULL;
	ValadateRunnerTestMarshaller _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	void* _tmp2_ = NULL;
	void* _tmp3_ = NULL;
	GSList* _tmp4_ = NULL;
	GParameter* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (suite != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = suite;
	_tmp1_ = marshaller;
	_tmp1__target = marshaller_target;
	_tmp2_ = arg1;
	_tmp3_ = arg2;
	_tmp4_ = self->priv->parameters;
	_tmp5_ = g_new0 (GParameter, 0);
	_tmp6_ = name;
	valadate_runner_suite_info_parametrize_test (self, _tmp0_, _tmp1_, _tmp1__target, _tmp2_, _tmp3_, _tmp4_, _tmp5_, 0, _tmp6_);
}


static void g_parameter_copy (const GParameter* self, GParameter* dest) {
	const gchar* _tmp0_ = NULL;
	GValue _tmp1_ = {0};
	GValue _tmp2_ = {0};
	_tmp0_ = (*self).name;
	(*dest).name = _tmp0_;
	_tmp1_ = (*self).value;
	if (G_IS_VALUE (&_tmp1_)) {
		g_value_init (&_tmp2_, G_VALUE_TYPE (&_tmp1_));
		g_value_copy (&_tmp1_, &_tmp2_);
	} else {
		_tmp2_ = _tmp1_;
	}
	G_IS_VALUE (&(*dest).value) ? (g_value_unset (&(*dest).value), NULL) : NULL;
	(*dest).value = _tmp2_;
}


static GParameter* _vala_array_dup1 (GParameter* self, int length) {
	GParameter* result;
	int i;
	result = g_new0 (GParameter, length);
	for (i = 0; i < length; i++) {
		GParameter _tmp0_ = {0};
		g_parameter_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


static gpointer _valadate_runner_param_info_ref0 (gpointer self) {
	return self ? valadate_runner_param_info_ref (self) : NULL;
}


static GParameter* _vala_array_dup2 (GParameter* self, int length) {
	GParameter* result;
	int i;
	result = g_new0 (GParameter, length);
	for (i = 0; i < length; i++) {
		GParameter _tmp0_ = {0};
		g_parameter_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


static void _vala_array_add6 (GParameter** array, int* length, int* size, const GParameter* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GParameter, *array, *size);
	}
	(*array)[(*length)++] = *value;
}


static void _vala_GParameter_array_free (GParameter* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			g_parameter_destroy (&array[i]);
		}
	}
	g_free (array);
}


static void valadate_runner_suite_info_parametrize_test (ValadateRunnerSuiteInfo* self, GTestSuite* suite, ValadateRunnerTestMarshaller marshaller, void* marshaller_target, void* arg1, void* arg2, GSList* next_param, GParameter* prefix, int prefix_length1, const gchar* name) {
	GSList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (suite != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = next_param;
	if (_tmp0_ == NULL) {
		gboolean _tmp1_ = FALSE;
		ValadateRunnerTestInfo* test = NULL;
		GType _tmp4_ = 0UL;
		ValadateRunnerTestMarshaller _tmp5_ = NULL;
		void* _tmp5__target = NULL;
		void* _tmp6_ = NULL;
		void* _tmp7_ = NULL;
		GParameter* _tmp8_ = NULL;
		gint _tmp8__length1 = 0;
		GParameter* _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		ValadateRunnerTestInfo* _tmp10_ = NULL;
		GTestSuite* _tmp11_ = NULL;
		ValadateRunnerTestInfo* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		GTestCase* _tmp14_ = NULL;
		ValadateRunnerTestInfo* _tmp15_ = NULL;
		_tmp1_ = valadate_runner_verbose;
		if (_tmp1_) {
			FILE* _tmp2_ = NULL;
			const gchar* _tmp3_ = NULL;
			_tmp2_ = stdout;
			_tmp3_ = name;
			fprintf (_tmp2_, "             creating test case %s\n", _tmp3_);
		}
		_tmp4_ = self->priv->type;
		_tmp5_ = marshaller;
		_tmp5__target = marshaller_target;
		_tmp6_ = arg1;
		_tmp7_ = arg2;
		_tmp8_ = prefix;
		_tmp8__length1 = prefix_length1;
		_tmp9_ = (_tmp8_ != NULL) ? _vala_array_dup1 (_tmp8_, _tmp8__length1) : ((gpointer) _tmp8_);
		_tmp9__length1 = _tmp8__length1;
		_tmp10_ = valadate_runner_test_info_new (_tmp4_, _tmp5_, _tmp5__target, _tmp6_, _tmp7_, _tmp9_, _tmp9__length1);
		test = _tmp10_;
		_tmp11_ = suite;
		_tmp12_ = test;
		_tmp13_ = name;
		_tmp14_ = valadate_runner_test_info_make_case (_tmp12_, _tmp13_);
		g_test_suite_add (_tmp11_, _tmp14_);
		_tmp15_ = test;
		test = NULL;
		self->priv->tests = g_slist_prepend (self->priv->tests, _tmp15_);
		_valadate_runner_test_info_unref0 (test);
	} else {
		ValadateRunnerParamInfo* p = NULL;
		GSList* _tmp16_ = NULL;
		gconstpointer _tmp17_ = NULL;
		ValadateRunnerParamInfo* _tmp18_ = NULL;
		guint n_values = 0U;
		ValadateRunnerParamInfo* _tmp19_ = NULL;
		GValueArray* _tmp20_ = NULL;
		guint _tmp21_ = 0U;
		_tmp16_ = next_param;
		_tmp17_ = _tmp16_->data;
		_tmp18_ = _valadate_runner_param_info_ref0 ((ValadateRunnerParamInfo*) _tmp17_);
		p = _tmp18_;
		_tmp19_ = p;
		_tmp20_ = _tmp19_->values;
		_tmp21_ = _tmp20_->n_values;
		n_values = _tmp21_;
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp22_ = FALSE;
				_tmp22_ = TRUE;
				while (TRUE) {
					gint _tmp24_ = 0;
					guint _tmp25_ = 0U;
					GParameter* new_params = NULL;
					GParameter* _tmp26_ = NULL;
					gint _tmp26__length1 = 0;
					GParameter* _tmp27_ = NULL;
					gint _tmp27__length1 = 0;
					gint new_params_length1 = 0;
					gint _new_params_size_ = 0;
					GParameter* _tmp28_ = NULL;
					gint _tmp28__length1 = 0;
					ValadateRunnerParamInfo* _tmp29_ = NULL;
					gint _tmp30_ = 0;
					GParameter _tmp31_ = {0};
					GTestSuite* _tmp32_ = NULL;
					ValadateRunnerTestMarshaller _tmp33_ = NULL;
					void* _tmp33__target = NULL;
					void* _tmp34_ = NULL;
					void* _tmp35_ = NULL;
					GSList* _tmp36_ = NULL;
					GSList* _tmp37_ = NULL;
					GParameter* _tmp38_ = NULL;
					gint _tmp38__length1 = 0;
					const gchar* _tmp39_ = NULL;
					ValadateRunnerParamInfo* _tmp40_ = NULL;
					gint _tmp41_ = 0;
					gchar* _tmp42_ = NULL;
					gchar* _tmp43_ = NULL;
					gchar* _tmp44_ = NULL;
					gchar* _tmp45_ = NULL;
					if (!_tmp22_) {
						gint _tmp23_ = 0;
						_tmp23_ = i;
						i = _tmp23_ + 1;
					}
					_tmp22_ = FALSE;
					_tmp24_ = i;
					_tmp25_ = n_values;
					if (!(((guint) _tmp24_) < _tmp25_)) {
						break;
					}
					_tmp26_ = prefix;
					_tmp26__length1 = prefix_length1;
					_tmp27_ = (_tmp26_ != NULL) ? _vala_array_dup2 (_tmp26_, _tmp26__length1) : ((gpointer) _tmp26_);
					_tmp27__length1 = _tmp26__length1;
					new_params = _tmp27_;
					new_params_length1 = _tmp27__length1;
					_new_params_size_ = new_params_length1;
					_tmp28_ = new_params;
					_tmp28__length1 = new_params_length1;
					_tmp29_ = p;
					_tmp30_ = i;
					valadate_runner_param_info_to_parameter (_tmp29_, _tmp30_, &_tmp31_);
					_vala_array_add6 (&new_params, &new_params_length1, &_new_params_size_, &_tmp31_);
					_tmp32_ = suite;
					_tmp33_ = marshaller;
					_tmp33__target = marshaller_target;
					_tmp34_ = arg1;
					_tmp35_ = arg2;
					_tmp36_ = next_param;
					_tmp37_ = _tmp36_->next;
					_tmp38_ = new_params;
					_tmp38__length1 = new_params_length1;
					new_params = NULL;
					new_params_length1 = 0;
					_tmp39_ = name;
					_tmp40_ = p;
					_tmp41_ = i;
					_tmp42_ = valadate_runner_param_info_to_name (_tmp40_, _tmp41_);
					_tmp43_ = _tmp42_;
					_tmp44_ = g_strconcat (_tmp39_, _tmp43_, NULL);
					_tmp45_ = _tmp44_;
					valadate_runner_suite_info_parametrize_test (self, _tmp32_, _tmp33_, _tmp33__target, _tmp34_, _tmp35_, _tmp37_, _tmp38_, _tmp38__length1, _tmp45_);
					_g_free0 (_tmp45_);
					_g_free0 (_tmp43_);
					new_params = (_vala_GParameter_array_free (new_params, new_params_length1), NULL);
				}
			}
		}
		_valadate_runner_param_info_unref0 (p);
	}
	prefix = (_vala_GParameter_array_free (prefix, prefix_length1), NULL);
}


static void valadate_runner_value_suite_info_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void valadate_runner_value_suite_info_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		valadate_runner_suite_info_unref (value->data[0].v_pointer);
	}
}


static void valadate_runner_value_suite_info_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = valadate_runner_suite_info_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer valadate_runner_value_suite_info_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* valadate_runner_value_suite_info_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ValadateRunnerSuiteInfo* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = valadate_runner_suite_info_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* valadate_runner_value_suite_info_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ValadateRunnerSuiteInfo** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = valadate_runner_suite_info_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* valadate_runner_param_spec_suite_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ValadateRunnerParamSpecSuiteInfo* spec;
	g_return_val_if_fail (g_type_is_a (object_type, VALADATE_RUNNER_TYPE_SUITE_INFO), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer valadate_runner_value_get_suite_info (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALADATE_RUNNER_TYPE_SUITE_INFO), NULL);
	return value->data[0].v_pointer;
}


void valadate_runner_value_set_suite_info (GValue* value, gpointer v_object) {
	ValadateRunnerSuiteInfo* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALADATE_RUNNER_TYPE_SUITE_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALADATE_RUNNER_TYPE_SUITE_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		valadate_runner_suite_info_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		valadate_runner_suite_info_unref (old);
	}
}


void valadate_runner_value_take_suite_info (GValue* value, gpointer v_object) {
	ValadateRunnerSuiteInfo* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, VALADATE_RUNNER_TYPE_SUITE_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, VALADATE_RUNNER_TYPE_SUITE_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		valadate_runner_suite_info_unref (old);
	}
}


static void valadate_runner_suite_info_class_init (ValadateRunnerSuiteInfoClass * klass) {
	valadate_runner_suite_info_parent_class = g_type_class_peek_parent (klass);
	((ValadateRunnerSuiteInfoClass *) klass)->finalize = valadate_runner_suite_info_finalize;
	g_type_class_add_private (klass, sizeof (ValadateRunnerSuiteInfoPrivate));
}


static void valadate_runner_suite_info_instance_init (ValadateRunnerSuiteInfo * self) {
	self->priv = VALADATE_RUNNER_SUITE_INFO_GET_PRIVATE (self);
	self->priv->parameters = NULL;
	self->priv->tests = NULL;
	self->ref_count = 1;
}


static void valadate_runner_suite_info_finalize (ValadateRunnerSuiteInfo* obj) {
	ValadateRunnerSuiteInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfo);
	g_signal_handlers_destroy (self);
	_g_type_class_unref0 (self->priv->klass);
	__g_slist_free__valadate_runner_param_info_unref0_0 (self->priv->parameters);
	__g_slist_free__valadate_runner_test_info_unref0_0 (self->priv->tests);
}


GType valadate_runner_suite_info_get_type (void) {
	static volatile gsize valadate_runner_suite_info_type_id__volatile = 0;
	if (g_once_init_enter (&valadate_runner_suite_info_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { valadate_runner_value_suite_info_init, valadate_runner_value_suite_info_free_value, valadate_runner_value_suite_info_copy_value, valadate_runner_value_suite_info_peek_pointer, "p", valadate_runner_value_suite_info_collect_value, "p", valadate_runner_value_suite_info_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ValadateRunnerSuiteInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valadate_runner_suite_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValadateRunnerSuiteInfo), 0, (GInstanceInitFunc) valadate_runner_suite_info_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType valadate_runner_suite_info_type_id;
		valadate_runner_suite_info_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ValadateRunnerSuiteInfo", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&valadate_runner_suite_info_type_id__volatile, valadate_runner_suite_info_type_id);
	}
	return valadate_runner_suite_info_type_id__volatile;
}


gpointer valadate_runner_suite_info_ref (gpointer instance) {
	ValadateRunnerSuiteInfo* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void valadate_runner_suite_info_unref (gpointer instance) {
	ValadateRunnerSuiteInfo* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		VALADATE_RUNNER_SUITE_INFO_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



