/* vapisuiteinfo.c generated by valac 0.30.0, the Vala compiler
 * generated from vapisuiteinfo.vala, do not modify */

/*
 * Valadate - Unit testing library for GObject-based libraries.
 * Copyright (C) 2009  Jan Hudec <bulb@ucw.cz>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <gmodule.h>
#include <valagee.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <valacodegen.h>
#include "libvaladate.h"


#define VALADATE_RUNNER_TYPE_SUITE_INFO (valadate_runner_suite_info_get_type ())
#define VALADATE_RUNNER_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfo))
#define VALADATE_RUNNER_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoClass))
#define VALADATE_RUNNER_IS_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO))
#define VALADATE_RUNNER_IS_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_SUITE_INFO))
#define VALADATE_RUNNER_SUITE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_SUITE_INFO, ValadateRunnerSuiteInfoClass))

typedef struct _ValadateRunnerSuiteInfo ValadateRunnerSuiteInfo;
typedef struct _ValadateRunnerSuiteInfoClass ValadateRunnerSuiteInfoClass;
typedef struct _ValadateRunnerSuiteInfoPrivate ValadateRunnerSuiteInfoPrivate;

#define VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO (valadate_runner_vapi_suite_info_get_type ())
#define VALADATE_RUNNER_VAPI_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO, ValadateRunnerVapiSuiteInfo))
#define VALADATE_RUNNER_VAPI_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO, ValadateRunnerVapiSuiteInfoClass))
#define VALADATE_RUNNER_IS_VAPI_SUITE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO))
#define VALADATE_RUNNER_IS_VAPI_SUITE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO))
#define VALADATE_RUNNER_VAPI_SUITE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO, ValadateRunnerVapiSuiteInfoClass))

typedef struct _ValadateRunnerVapiSuiteInfo ValadateRunnerVapiSuiteInfo;
typedef struct _ValadateRunnerVapiSuiteInfoClass ValadateRunnerVapiSuiteInfoClass;
typedef struct _ValadateRunnerVapiSuiteInfoPrivate ValadateRunnerVapiSuiteInfoPrivate;

#define VALADATE_RUNNER_VAPI_SUITE_INFO_TYPE_TEST_TYPE (valadate_runner_vapi_suite_info_test_type_get_type ())
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _valadate_runner_suite_info_unref0(var) ((var == NULL) ? NULL : (var = (valadate_runner_suite_info_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _g_module_close0(var) ((var == NULL) ? NULL : (var = (g_module_close (var), NULL)))

typedef GType (*ValadateRunnerGetType) ();
struct _ValadateRunnerSuiteInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ValadateRunnerSuiteInfoPrivate * priv;
};

struct _ValadateRunnerSuiteInfoClass {
	GTypeClass parent_class;
	void (*finalize) (ValadateRunnerSuiteInfo *self);
};

struct _ValadateRunnerVapiSuiteInfo {
	ValadateRunnerSuiteInfo parent_instance;
	ValadateRunnerVapiSuiteInfoPrivate * priv;
};

struct _ValadateRunnerVapiSuiteInfoClass {
	ValadateRunnerSuiteInfoClass parent_class;
};

struct _ValadateRunnerVapiSuiteInfoPrivate {
	ValaClass* cl;
};

typedef enum  {
	VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_NONE,
	VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_SYNC,
	VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_ASYNC,
	VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_CANCELLABLE
} ValadateRunnerVapiSuiteInfoTestType;

typedef enum  {
	VALADATE_RUNNER_RUNNER_ERROR_UNRECOGNIZED_FILE,
	VALADATE_RUNNER_RUNNER_ERROR_CANNOT_READ,
	VALADATE_RUNNER_RUNNER_ERROR_COMPILATION_FAILED,
	VALADATE_RUNNER_RUNNER_ERROR_TYPE_NOT_LOADED,
	VALADATE_RUNNER_RUNNER_ERROR_NOT_FOUND,
	VALADATE_RUNNER_RUNNER_ERROR_VAPI_ERROR
} ValadateRunnerRunnerError;
#define VALADATE_RUNNER_RUNNER_ERROR valadate_runner_runner_error_quark ()
typedef GValueArray* (*ValadateRunnerGenerator) (void* user_data);
typedef void (*ValadateRunnerTestMarshaller) (ValadateFixture* fixture, void* arg1, void* arg2, void* user_data);

static gpointer valadate_runner_vapi_suite_info_parent_class = NULL;
static GModule** valadate_runner_vapi_suite_info_modules;
static gint valadate_runner_vapi_suite_info_modules_length1;
static GModule** valadate_runner_vapi_suite_info_modules = NULL;
static gint valadate_runner_vapi_suite_info_modules_length1 = 0;
static gint _valadate_runner_vapi_suite_info_modules_size_ = 0;
static gboolean valadate_runner_vapi_suite_info_modules_loaded;
static gboolean valadate_runner_vapi_suite_info_modules_loaded = FALSE;
extern gboolean valadate_runner_verbose;
extern gchar** valadate_runner_libs;
extern gchar** valadate_runner_path;

gpointer valadate_runner_suite_info_ref (gpointer instance);
void valadate_runner_suite_info_unref (gpointer instance);
GParamSpec* valadate_runner_param_spec_suite_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void valadate_runner_value_set_suite_info (GValue* value, gpointer v_object);
void valadate_runner_value_take_suite_info (GValue* value, gpointer v_object);
gpointer valadate_runner_value_get_suite_info (const GValue* value);
GType valadate_runner_suite_info_get_type (void) G_GNUC_CONST;
GType valadate_runner_vapi_suite_info_get_type (void) G_GNUC_CONST;
#define VALADATE_RUNNER_VAPI_SUITE_INFO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO, ValadateRunnerVapiSuiteInfoPrivate))
enum  {
	VALADATE_RUNNER_VAPI_SUITE_INFO_DUMMY_PROPERTY
};
static GType valadate_runner_vapi_suite_info_test_type_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
GQuark valadate_runner_runner_error_quark (void);
ValadateRunnerVapiSuiteInfo* valadate_runner_vapi_suite_info_new (ValaClass* cl, GError** error);
ValadateRunnerVapiSuiteInfo* valadate_runner_vapi_suite_info_construct (GType object_type, ValaClass* cl, GError** error);
static GType valadate_runner_vapi_suite_info_get_g_type (ValaClass* cl, GError** error);
ValadateRunnerSuiteInfo* valadate_runner_suite_info_new (GType type, GError** error);
ValadateRunnerSuiteInfo* valadate_runner_suite_info_construct (GType object_type, GType type, GError** error);
void valadate_runner_vapi_suite_info_create_tests (ValadateRunnerVapiSuiteInfo* self, GTestSuite* suite, GError** error);
static void valadate_runner_vapi_suite_info_gather_methods (ValadateRunnerVapiSuiteInfo* self, ValaObjectTypeSymbol* ots, ValaArrayList** methods);
static gboolean valadate_runner_vapi_suite_info_is_generator (ValadateRunnerVapiSuiteInfo* self, ValaMethod* method);
static void* valadate_runner_vapi_suite_info_load_symbol (const gchar* name, GError** error);
void valadate_runner_suite_info_add_generator (ValadateRunnerSuiteInfo* self, const gchar* prop, ValadateRunnerGenerator gen, void* gen_target);
static gboolean valadate_runner_vapi_suite_info_is_test (ValadateRunnerVapiSuiteInfo* self, ValaMethod* method);
static ValadateRunnerVapiSuiteInfoTestType valadate_runner_vapi_suite_info_test_type (ValadateRunnerVapiSuiteInfo* self, ValaMethod* method);
void valadate_runner_suite_info_add_test (ValadateRunnerSuiteInfo* self, GTestSuite* suite, const gchar* name, ValadateRunnerTestMarshaller marshaller, void* marshaller_target, void* arg1, void* arg2);
void valadate_runner_test_marshal_synchronous (ValadateFixture* it, void* arg1, void* arg2);
static void _valadate_runner_test_marshal_synchronous_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self);
void valadate_runner_test_marshal_asynchronous (ValadateFixture* it, void* arg1, void* arg2);
static void _valadate_runner_test_marshal_asynchronous_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self);
void valadate_runner_test_marshal_cancellable (ValadateFixture* it, void* arg1, void* arg2);
static void _valadate_runner_test_marshal_cancellable_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self);
static void valadate_runner_vapi_suite_info_load_modules (GError** error);
static GModule* valadate_runner_vapi_suite_info_load_module (const gchar* name);
static void _vala_array_add7 (GModule*** array, int* length, int* size, GModule* value);
static void valadate_runner_vapi_suite_info_finalize (ValadateRunnerSuiteInfo* obj);
static gint _vala_array_length (gpointer array);


static GType valadate_runner_vapi_suite_info_test_type_get_type (void) {
	static volatile gsize valadate_runner_vapi_suite_info_test_type_type_id__volatile = 0;
	if (g_once_init_enter (&valadate_runner_vapi_suite_info_test_type_type_id__volatile)) {
		static const GEnumValue values[] = {{VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_NONE, "VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_NONE", "none"}, {VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_SYNC, "VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_SYNC", "sync"}, {VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_ASYNC, "VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_ASYNC", "async"}, {VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_CANCELLABLE, "VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_CANCELLABLE", "cancellable"}, {0, NULL, NULL}};
		GType valadate_runner_vapi_suite_info_test_type_type_id;
		valadate_runner_vapi_suite_info_test_type_type_id = g_enum_register_static ("ValadateRunnerVapiSuiteInfoTestType", values);
		g_once_init_leave (&valadate_runner_vapi_suite_info_test_type_type_id__volatile, valadate_runner_vapi_suite_info_test_type_type_id);
	}
	return valadate_runner_vapi_suite_info_test_type_type_id__volatile;
}


static gpointer _vala_code_node_ref0 (gpointer self) {
	return self ? vala_code_node_ref (self) : NULL;
}


ValadateRunnerVapiSuiteInfo* valadate_runner_vapi_suite_info_construct (GType object_type, ValaClass* cl, GError** error) {
	ValadateRunnerVapiSuiteInfo* self = NULL;
	GType _tmp0_ = 0UL;
	ValaClass* _tmp1_ = NULL;
	GType _tmp2_ = 0UL;
	ValaClass* _tmp3_ = NULL;
	ValaClass* _tmp4_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (cl != NULL, NULL);
	_tmp1_ = cl;
	_tmp2_ = valadate_runner_vapi_suite_info_get_g_type (_tmp1_, &_inner_error_);
	_tmp0_ = _tmp2_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
			g_propagate_error (error, _inner_error_);
			_valadate_runner_suite_info_unref0 (self);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	self = (ValadateRunnerVapiSuiteInfo*) valadate_runner_suite_info_construct (object_type, _tmp0_, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
			g_propagate_error (error, _inner_error_);
			_valadate_runner_suite_info_unref0 (self);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp3_ = cl;
	_tmp4_ = _vala_code_node_ref0 (_tmp3_);
	_vala_code_node_unref0 (self->priv->cl);
	self->priv->cl = _tmp4_;
	return self;
}


ValadateRunnerVapiSuiteInfo* valadate_runner_vapi_suite_info_new (ValaClass* cl, GError** error) {
	return valadate_runner_vapi_suite_info_construct (VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO, cl, error);
}


static gpointer _vala_iterable_ref0 (gpointer self) {
	return self ? vala_iterable_ref (self) : NULL;
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


static gchar* string_delimit (const gchar* self, const gchar* delimiters, gchar new_delimiter) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar _tmp3_ = '\0';
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (delimiters != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	_tmp2_ = delimiters;
	_tmp3_ = new_delimiter;
	g_strdelimit (_tmp1_, _tmp2_, _tmp3_);
	result = _result_;
	return result;
}


static void _valadate_runner_test_marshal_synchronous_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self) {
	valadate_runner_test_marshal_synchronous (fixture, arg1, arg2);
}


static void _valadate_runner_test_marshal_asynchronous_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self) {
	valadate_runner_test_marshal_asynchronous (fixture, arg1, arg2);
}


static void _valadate_runner_test_marshal_cancellable_valadate_runner_test_marshaller (ValadateFixture* fixture, void* arg1, void* arg2, gpointer self) {
	valadate_runner_test_marshal_cancellable (fixture, arg1, arg2);
}


void valadate_runner_vapi_suite_info_create_tests (ValadateRunnerVapiSuiteInfo* self, GTestSuite* suite, GError** error) {
	ValaArrayList* methods = NULL;
	GEqualFunc _tmp0_ = NULL;
	ValaArrayList* _tmp1_ = NULL;
	ValaClass* _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (suite != NULL);
	_tmp0_ = g_direct_equal;
	_tmp1_ = vala_array_list_new (VALA_TYPE_METHOD, (GBoxedCopyFunc) vala_code_node_ref, vala_code_node_unref, _tmp0_);
	methods = _tmp1_;
	_tmp2_ = self->priv->cl;
	valadate_runner_vapi_suite_info_gather_methods (self, (ValaObjectTypeSymbol*) _tmp2_, &methods);
	{
		ValaArrayList* _method_list = NULL;
		ValaArrayList* _tmp3_ = NULL;
		ValaArrayList* _tmp4_ = NULL;
		gint _method_size = 0;
		ValaArrayList* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gint _method_index = 0;
		_tmp3_ = methods;
		_tmp4_ = _vala_iterable_ref0 (_tmp3_);
		_method_list = _tmp4_;
		_tmp5_ = _method_list;
		_tmp6_ = vala_collection_get_size ((ValaCollection*) _tmp5_);
		_tmp7_ = _tmp6_;
		_method_size = _tmp7_;
		_method_index = -1;
		while (TRUE) {
			gint _tmp8_ = 0;
			gint _tmp9_ = 0;
			gint _tmp10_ = 0;
			ValaMethod* method = NULL;
			ValaArrayList* _tmp11_ = NULL;
			gint _tmp12_ = 0;
			gpointer _tmp13_ = NULL;
			ValaMethod* _tmp14_ = NULL;
			gboolean _tmp15_ = FALSE;
			gboolean _tmp16_ = FALSE;
			void* _tmp21_ = NULL;
			ValaMethod* _tmp22_ = NULL;
			gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
			void* _tmp25_ = NULL;
			void* _tmp26_ = NULL;
			ValaMethod* _tmp27_ = NULL;
			const gchar* _tmp28_ = NULL;
			const gchar* _tmp29_ = NULL;
			gchar* _tmp30_ = NULL;
			gchar* _tmp31_ = NULL;
			gchar* _tmp32_ = NULL;
			gchar* _tmp33_ = NULL;
			_tmp8_ = _method_index;
			_method_index = _tmp8_ + 1;
			_tmp9_ = _method_index;
			_tmp10_ = _method_size;
			if (!(_tmp9_ < _tmp10_)) {
				break;
			}
			_tmp11_ = _method_list;
			_tmp12_ = _method_index;
			_tmp13_ = vala_list_get ((ValaList*) _tmp11_, _tmp12_);
			method = (ValaMethod*) _tmp13_;
			_tmp14_ = method;
			_tmp15_ = valadate_runner_vapi_suite_info_is_generator (self, _tmp14_);
			if (!_tmp15_) {
				_vala_code_node_unref0 (method);
				continue;
			}
			_tmp16_ = valadate_runner_verbose;
			if (_tmp16_) {
				FILE* _tmp17_ = NULL;
				ValaMethod* _tmp18_ = NULL;
				const gchar* _tmp19_ = NULL;
				const gchar* _tmp20_ = NULL;
				_tmp17_ = stdout;
				_tmp18_ = method;
				_tmp19_ = vala_symbol_get_name ((ValaSymbol*) _tmp18_);
				_tmp20_ = _tmp19_;
				fprintf (_tmp17_, "        found generator %s\n", _tmp20_);
			}
			_tmp22_ = method;
			_tmp23_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp22_);
			_tmp24_ = _tmp23_;
			_tmp25_ = valadate_runner_vapi_suite_info_load_symbol (_tmp24_, &_inner_error_);
			_tmp26_ = _tmp25_;
			_g_free0 (_tmp24_);
			_tmp21_ = _tmp26_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
					g_propagate_error (error, _inner_error_);
					_vala_code_node_unref0 (method);
					_vala_iterable_unref0 (_method_list);
					_vala_iterable_unref0 (methods);
					return;
				} else {
					_vala_code_node_unref0 (method);
					_vala_iterable_unref0 (_method_list);
					_vala_iterable_unref0 (methods);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
			}
			_tmp27_ = method;
			_tmp28_ = vala_symbol_get_name ((ValaSymbol*) _tmp27_);
			_tmp29_ = _tmp28_;
			_tmp30_ = string_substring (_tmp29_, (glong) 9, (glong) -1);
			_tmp31_ = _tmp30_;
			_tmp32_ = string_delimit (_tmp31_, "_", '-');
			_tmp33_ = _tmp32_;
			valadate_runner_suite_info_add_generator ((ValadateRunnerSuiteInfo*) self, _tmp33_, (ValadateRunnerGenerator) _tmp21_, NULL);
			_g_free0 (_tmp33_);
			_g_free0 (_tmp31_);
			_vala_code_node_unref0 (method);
		}
		_vala_iterable_unref0 (_method_list);
	}
	{
		ValaArrayList* _method_list = NULL;
		ValaArrayList* _tmp34_ = NULL;
		ValaArrayList* _tmp35_ = NULL;
		gint _method_size = 0;
		ValaArrayList* _tmp36_ = NULL;
		gint _tmp37_ = 0;
		gint _tmp38_ = 0;
		gint _method_index = 0;
		_tmp34_ = methods;
		_tmp35_ = _vala_iterable_ref0 (_tmp34_);
		_method_list = _tmp35_;
		_tmp36_ = _method_list;
		_tmp37_ = vala_collection_get_size ((ValaCollection*) _tmp36_);
		_tmp38_ = _tmp37_;
		_method_size = _tmp38_;
		_method_index = -1;
		while (TRUE) {
			gint _tmp39_ = 0;
			gint _tmp40_ = 0;
			gint _tmp41_ = 0;
			ValaMethod* method = NULL;
			ValaArrayList* _tmp42_ = NULL;
			gint _tmp43_ = 0;
			gpointer _tmp44_ = NULL;
			ValaMethod* _tmp45_ = NULL;
			gboolean _tmp46_ = FALSE;
			ValaMethod* _tmp47_ = NULL;
			ValadateRunnerVapiSuiteInfoTestType _tmp48_ = 0;
			_tmp39_ = _method_index;
			_method_index = _tmp39_ + 1;
			_tmp40_ = _method_index;
			_tmp41_ = _method_size;
			if (!(_tmp40_ < _tmp41_)) {
				break;
			}
			_tmp42_ = _method_list;
			_tmp43_ = _method_index;
			_tmp44_ = vala_list_get ((ValaList*) _tmp42_, _tmp43_);
			method = (ValaMethod*) _tmp44_;
			_tmp45_ = method;
			_tmp46_ = valadate_runner_vapi_suite_info_is_test (self, _tmp45_);
			if (!_tmp46_) {
				_vala_code_node_unref0 (method);
				continue;
			}
			_tmp47_ = method;
			_tmp48_ = valadate_runner_vapi_suite_info_test_type (self, _tmp47_);
			switch (_tmp48_) {
				case VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_SYNC:
				{
					gboolean _tmp49_ = FALSE;
					void* _tmp54_ = NULL;
					ValaMethod* _tmp55_ = NULL;
					gchar* _tmp56_ = NULL;
					gchar* _tmp57_ = NULL;
					void* _tmp58_ = NULL;
					void* _tmp59_ = NULL;
					GTestSuite* _tmp60_ = NULL;
					ValaMethod* _tmp61_ = NULL;
					const gchar* _tmp62_ = NULL;
					const gchar* _tmp63_ = NULL;
					gchar* _tmp64_ = NULL;
					gchar* _tmp65_ = NULL;
					_tmp49_ = valadate_runner_verbose;
					if (_tmp49_) {
						FILE* _tmp50_ = NULL;
						ValaMethod* _tmp51_ = NULL;
						const gchar* _tmp52_ = NULL;
						const gchar* _tmp53_ = NULL;
						_tmp50_ = stdout;
						_tmp51_ = method;
						_tmp52_ = vala_symbol_get_name ((ValaSymbol*) _tmp51_);
						_tmp53_ = _tmp52_;
						fprintf (_tmp50_, "        found sync test %s\n", _tmp53_);
					}
					_tmp55_ = method;
					_tmp56_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp55_);
					_tmp57_ = _tmp56_;
					_tmp58_ = valadate_runner_vapi_suite_info_load_symbol (_tmp57_, &_inner_error_);
					_tmp59_ = _tmp58_;
					_g_free0 (_tmp57_);
					_tmp54_ = _tmp59_;
					if (G_UNLIKELY (_inner_error_ != NULL)) {
						if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
							g_propagate_error (error, _inner_error_);
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							return;
						} else {
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
							g_clear_error (&_inner_error_);
							return;
						}
					}
					_tmp60_ = suite;
					_tmp61_ = method;
					_tmp62_ = vala_symbol_get_name ((ValaSymbol*) _tmp61_);
					_tmp63_ = _tmp62_;
					_tmp64_ = string_substring (_tmp63_, (glong) 5, (glong) -1);
					_tmp65_ = _tmp64_;
					valadate_runner_suite_info_add_test ((ValadateRunnerSuiteInfo*) self, _tmp60_, _tmp65_, _valadate_runner_test_marshal_synchronous_valadate_runner_test_marshaller, NULL, _tmp54_, NULL);
					_g_free0 (_tmp65_);
					break;
				}
				case VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_ASYNC:
				{
					gboolean _tmp66_ = FALSE;
					void* _tmp71_ = NULL;
					ValaMethod* _tmp72_ = NULL;
					gchar* _tmp73_ = NULL;
					gchar* _tmp74_ = NULL;
					void* _tmp75_ = NULL;
					void* _tmp76_ = NULL;
					void* _tmp77_ = NULL;
					ValaMethod* _tmp78_ = NULL;
					gchar* _tmp79_ = NULL;
					gchar* _tmp80_ = NULL;
					void* _tmp81_ = NULL;
					void* _tmp82_ = NULL;
					GTestSuite* _tmp83_ = NULL;
					ValaMethod* _tmp84_ = NULL;
					const gchar* _tmp85_ = NULL;
					const gchar* _tmp86_ = NULL;
					gchar* _tmp87_ = NULL;
					gchar* _tmp88_ = NULL;
					_tmp66_ = valadate_runner_verbose;
					if (_tmp66_) {
						FILE* _tmp67_ = NULL;
						ValaMethod* _tmp68_ = NULL;
						const gchar* _tmp69_ = NULL;
						const gchar* _tmp70_ = NULL;
						_tmp67_ = stdout;
						_tmp68_ = method;
						_tmp69_ = vala_symbol_get_name ((ValaSymbol*) _tmp68_);
						_tmp70_ = _tmp69_;
						fprintf (_tmp67_, "        found async test %s\n", _tmp70_);
					}
					_tmp72_ = method;
					_tmp73_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp72_);
					_tmp74_ = _tmp73_;
					_tmp75_ = valadate_runner_vapi_suite_info_load_symbol (_tmp74_, &_inner_error_);
					_tmp76_ = _tmp75_;
					_g_free0 (_tmp74_);
					_tmp71_ = _tmp76_;
					if (G_UNLIKELY (_inner_error_ != NULL)) {
						if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
							g_propagate_error (error, _inner_error_);
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							return;
						} else {
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
							g_clear_error (&_inner_error_);
							return;
						}
					}
					_tmp78_ = method;
					_tmp79_ = vala_ccode_base_module_get_ccode_finish_name (_tmp78_);
					_tmp80_ = _tmp79_;
					_tmp81_ = valadate_runner_vapi_suite_info_load_symbol (_tmp80_, &_inner_error_);
					_tmp82_ = _tmp81_;
					_g_free0 (_tmp80_);
					_tmp77_ = _tmp82_;
					if (G_UNLIKELY (_inner_error_ != NULL)) {
						if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
							g_propagate_error (error, _inner_error_);
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							return;
						} else {
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
							g_clear_error (&_inner_error_);
							return;
						}
					}
					_tmp83_ = suite;
					_tmp84_ = method;
					_tmp85_ = vala_symbol_get_name ((ValaSymbol*) _tmp84_);
					_tmp86_ = _tmp85_;
					_tmp87_ = string_substring (_tmp86_, (glong) 5, (glong) -1);
					_tmp88_ = _tmp87_;
					valadate_runner_suite_info_add_test ((ValadateRunnerSuiteInfo*) self, _tmp83_, _tmp88_, _valadate_runner_test_marshal_asynchronous_valadate_runner_test_marshaller, NULL, _tmp71_, _tmp77_);
					_g_free0 (_tmp88_);
					break;
				}
				case VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_CANCELLABLE:
				{
					gboolean _tmp89_ = FALSE;
					void* _tmp94_ = NULL;
					ValaMethod* _tmp95_ = NULL;
					gchar* _tmp96_ = NULL;
					gchar* _tmp97_ = NULL;
					void* _tmp98_ = NULL;
					void* _tmp99_ = NULL;
					void* _tmp100_ = NULL;
					ValaMethod* _tmp101_ = NULL;
					gchar* _tmp102_ = NULL;
					gchar* _tmp103_ = NULL;
					void* _tmp104_ = NULL;
					void* _tmp105_ = NULL;
					GTestSuite* _tmp106_ = NULL;
					ValaMethod* _tmp107_ = NULL;
					const gchar* _tmp108_ = NULL;
					const gchar* _tmp109_ = NULL;
					gchar* _tmp110_ = NULL;
					gchar* _tmp111_ = NULL;
					_tmp89_ = valadate_runner_verbose;
					if (_tmp89_) {
						FILE* _tmp90_ = NULL;
						ValaMethod* _tmp91_ = NULL;
						const gchar* _tmp92_ = NULL;
						const gchar* _tmp93_ = NULL;
						_tmp90_ = stdout;
						_tmp91_ = method;
						_tmp92_ = vala_symbol_get_name ((ValaSymbol*) _tmp91_);
						_tmp93_ = _tmp92_;
						fprintf (_tmp90_, "        found cancellable test %s\n", _tmp93_);
					}
					_tmp95_ = method;
					_tmp96_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp95_);
					_tmp97_ = _tmp96_;
					_tmp98_ = valadate_runner_vapi_suite_info_load_symbol (_tmp97_, &_inner_error_);
					_tmp99_ = _tmp98_;
					_g_free0 (_tmp97_);
					_tmp94_ = _tmp99_;
					if (G_UNLIKELY (_inner_error_ != NULL)) {
						if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
							g_propagate_error (error, _inner_error_);
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							return;
						} else {
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
							g_clear_error (&_inner_error_);
							return;
						}
					}
					_tmp101_ = method;
					_tmp102_ = vala_ccode_base_module_get_ccode_finish_name (_tmp101_);
					_tmp103_ = _tmp102_;
					_tmp104_ = valadate_runner_vapi_suite_info_load_symbol (_tmp103_, &_inner_error_);
					_tmp105_ = _tmp104_;
					_g_free0 (_tmp103_);
					_tmp100_ = _tmp105_;
					if (G_UNLIKELY (_inner_error_ != NULL)) {
						if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
							g_propagate_error (error, _inner_error_);
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							return;
						} else {
							_vala_code_node_unref0 (method);
							_vala_iterable_unref0 (_method_list);
							_vala_iterable_unref0 (methods);
							g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
							g_clear_error (&_inner_error_);
							return;
						}
					}
					_tmp106_ = suite;
					_tmp107_ = method;
					_tmp108_ = vala_symbol_get_name ((ValaSymbol*) _tmp107_);
					_tmp109_ = _tmp108_;
					_tmp110_ = string_substring (_tmp109_, (glong) 5, (glong) -1);
					_tmp111_ = _tmp110_;
					valadate_runner_suite_info_add_test ((ValadateRunnerSuiteInfo*) self, _tmp106_, _tmp111_, _valadate_runner_test_marshal_cancellable_valadate_runner_test_marshaller, NULL, _tmp94_, _tmp100_);
					_g_free0 (_tmp111_);
					break;
				}
				default:
				break;
			}
			_vala_code_node_unref0 (method);
		}
		_vala_iterable_unref0 (_method_list);
	}
	_vala_iterable_unref0 (methods);
}


static void valadate_runner_vapi_suite_info_gather_methods (ValadateRunnerVapiSuiteInfo* self, ValaObjectTypeSymbol* ots, ValaArrayList** methods) {
	ValaObjectTypeSymbol* _tmp13_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (ots != NULL);
	g_return_if_fail (*methods != NULL);
	{
		ValaList* _method_list = NULL;
		ValaObjectTypeSymbol* _tmp0_ = NULL;
		ValaList* _tmp1_ = NULL;
		gint _method_size = 0;
		ValaList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _method_index = 0;
		_tmp0_ = ots;
		_tmp1_ = vala_object_type_symbol_get_methods (_tmp0_);
		_method_list = _tmp1_;
		_tmp2_ = _method_list;
		_tmp3_ = vala_collection_get_size ((ValaCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_method_size = _tmp4_;
		_method_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			ValaMethod* method = NULL;
			ValaList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			ValaArrayList* _tmp11_ = NULL;
			ValaMethod* _tmp12_ = NULL;
			_tmp5_ = _method_index;
			_method_index = _tmp5_ + 1;
			_tmp6_ = _method_index;
			_tmp7_ = _method_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _method_list;
			_tmp9_ = _method_index;
			_tmp10_ = vala_list_get (_tmp8_, _tmp9_);
			method = (ValaMethod*) _tmp10_;
			_tmp11_ = *methods;
			_tmp12_ = method;
			vala_collection_add ((ValaCollection*) _tmp11_, _tmp12_);
			_vala_code_node_unref0 (method);
		}
		_vala_iterable_unref0 (_method_list);
	}
	_tmp13_ = ots;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, VALA_TYPE_CLASS)) {
		{
			ValaList* _base_type_list = NULL;
			ValaObjectTypeSymbol* _tmp14_ = NULL;
			ValaList* _tmp15_ = NULL;
			gint _base_type_size = 0;
			ValaList* _tmp16_ = NULL;
			gint _tmp17_ = 0;
			gint _tmp18_ = 0;
			gint _base_type_index = 0;
			_tmp14_ = ots;
			_tmp15_ = vala_class_get_base_types (G_TYPE_CHECK_INSTANCE_CAST (_tmp14_, VALA_TYPE_CLASS, ValaClass));
			_base_type_list = _tmp15_;
			_tmp16_ = _base_type_list;
			_tmp17_ = vala_collection_get_size ((ValaCollection*) _tmp16_);
			_tmp18_ = _tmp17_;
			_base_type_size = _tmp18_;
			_base_type_index = -1;
			while (TRUE) {
				gint _tmp19_ = 0;
				gint _tmp20_ = 0;
				gint _tmp21_ = 0;
				ValaDataType* base_type = NULL;
				ValaList* _tmp22_ = NULL;
				gint _tmp23_ = 0;
				gpointer _tmp24_ = NULL;
				ValaDataType* _tmp25_ = NULL;
				ValaTypeSymbol* _tmp26_ = NULL;
				ValaTypeSymbol* _tmp27_ = NULL;
				_tmp19_ = _base_type_index;
				_base_type_index = _tmp19_ + 1;
				_tmp20_ = _base_type_index;
				_tmp21_ = _base_type_size;
				if (!(_tmp20_ < _tmp21_)) {
					break;
				}
				_tmp22_ = _base_type_list;
				_tmp23_ = _base_type_index;
				_tmp24_ = vala_list_get (_tmp22_, _tmp23_);
				base_type = (ValaDataType*) _tmp24_;
				_tmp25_ = base_type;
				_tmp26_ = vala_data_type_get_data_type (_tmp25_);
				_tmp27_ = _tmp26_;
				valadate_runner_vapi_suite_info_gather_methods (self, G_TYPE_CHECK_INSTANCE_CAST (_tmp27_, VALA_TYPE_OBJECT_TYPE_SYMBOL, ValaObjectTypeSymbol), methods);
				_vala_code_node_unref0 (base_type);
			}
			_vala_iterable_unref0 (_base_type_list);
		}
	}
}


static gboolean valadate_runner_vapi_suite_info_is_generator (ValadateRunnerVapiSuiteInfo* self, ValaMethod* method) {
	gboolean result = FALSE;
	ValaMethod* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	ValaMethod* _tmp4_ = NULL;
	ValaMemberBinding _tmp5_ = 0;
	ValaMemberBinding _tmp6_ = 0;
	ValaMethod* _tmp10_ = NULL;
	ValaList* _tmp11_ = NULL;
	ValaList* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	gboolean _tmp15_ = FALSE;
	ValaMethod* _tmp24_ = NULL;
	ValaList* _tmp25_ = NULL;
	ValaList* _tmp26_ = NULL;
	gint _tmp27_ = 0;
	gint _tmp28_ = 0;
	gboolean _tmp29_ = FALSE;
	ValaMethod* _tmp38_ = NULL;
	gboolean _tmp39_ = FALSE;
	gboolean _tmp40_ = FALSE;
	gboolean _tmp44_ = FALSE;
	ValaMethod* _tmp45_ = NULL;
	ValaDataType* _tmp46_ = NULL;
	ValaDataType* _tmp47_ = NULL;
	ValaTypeSymbol* _tmp48_ = NULL;
	ValaTypeSymbol* _tmp49_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (method != NULL, FALSE);
	_tmp0_ = method;
	_tmp1_ = vala_symbol_get_name ((ValaSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_str_has_prefix (_tmp2_, "generate_");
	if (!_tmp3_) {
		result = FALSE;
		return result;
	}
	_tmp4_ = method;
	_tmp5_ = vala_method_get_binding (_tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_ != VALA_MEMBER_BINDING_STATIC) {
		ValaMethod* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		_tmp7_ = method;
		_tmp8_ = vala_symbol_get_name ((ValaSymbol*) _tmp7_);
		_tmp9_ = _tmp8_;
		g_warning ("vapisuiteinfo.vala:103: %s is named like a generator, but it's not sta" \
"tic", _tmp9_);
		result = FALSE;
		return result;
	}
	_tmp10_ = method;
	_tmp11_ = vala_method_get_type_parameters (_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = vala_collection_get_size ((ValaCollection*) _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = _tmp14_ != 0;
	_vala_iterable_unref0 (_tmp12_);
	if (_tmp15_) {
		ValaMethod* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		const gchar* _tmp18_ = NULL;
		ValaMethod* _tmp19_ = NULL;
		ValaList* _tmp20_ = NULL;
		ValaList* _tmp21_ = NULL;
		gint _tmp22_ = 0;
		gint _tmp23_ = 0;
		_tmp16_ = method;
		_tmp17_ = vala_symbol_get_name ((ValaSymbol*) _tmp16_);
		_tmp18_ = _tmp17_;
		_tmp19_ = method;
		_tmp20_ = vala_method_get_type_parameters (_tmp19_);
		_tmp21_ = _tmp20_;
		_tmp22_ = vala_collection_get_size ((ValaCollection*) _tmp21_);
		_tmp23_ = _tmp22_;
		g_warning ("vapisuiteinfo.vala:108: %s is named like a generator, but it is generi" \
"c (with %i type params)", _tmp18_, _tmp23_);
		_vala_iterable_unref0 (_tmp21_);
		result = FALSE;
		return result;
	}
	_tmp24_ = method;
	_tmp25_ = vala_method_get_parameters (_tmp24_);
	_tmp26_ = _tmp25_;
	_tmp27_ = vala_collection_get_size ((ValaCollection*) _tmp26_);
	_tmp28_ = _tmp27_;
	_tmp29_ = _tmp28_ != 0;
	_vala_iterable_unref0 (_tmp26_);
	if (_tmp29_) {
		ValaMethod* _tmp30_ = NULL;
		const gchar* _tmp31_ = NULL;
		const gchar* _tmp32_ = NULL;
		ValaMethod* _tmp33_ = NULL;
		ValaList* _tmp34_ = NULL;
		ValaList* _tmp35_ = NULL;
		gint _tmp36_ = 0;
		gint _tmp37_ = 0;
		_tmp30_ = method;
		_tmp31_ = vala_symbol_get_name ((ValaSymbol*) _tmp30_);
		_tmp32_ = _tmp31_;
		_tmp33_ = method;
		_tmp34_ = vala_method_get_parameters (_tmp33_);
		_tmp35_ = _tmp34_;
		_tmp36_ = vala_collection_get_size ((ValaCollection*) _tmp35_);
		_tmp37_ = _tmp36_;
		g_warning ("vapisuiteinfo.vala:113: %s is named like a generator, but it has %i pa" \
"rameters", _tmp32_, _tmp37_);
		_vala_iterable_unref0 (_tmp35_);
		result = FALSE;
		return result;
	}
	_tmp38_ = method;
	_tmp39_ = vala_code_node_get_tree_can_fail ((ValaCodeNode*) _tmp38_);
	_tmp40_ = _tmp39_;
	if (_tmp40_) {
		ValaMethod* _tmp41_ = NULL;
		const gchar* _tmp42_ = NULL;
		const gchar* _tmp43_ = NULL;
		_tmp41_ = method;
		_tmp42_ = vala_symbol_get_name ((ValaSymbol*) _tmp41_);
		_tmp43_ = _tmp42_;
		g_warning ("vapisuiteinfo.vala:118: %s is named like a generator, but it throws er" \
"ror", _tmp43_);
		result = FALSE;
		return result;
	}
	_tmp45_ = method;
	_tmp46_ = vala_method_get_return_type (_tmp45_);
	_tmp47_ = _tmp46_;
	_tmp48_ = vala_data_type_get_data_type (_tmp47_);
	_tmp49_ = _tmp48_;
	if (_tmp49_ == NULL) {
		_tmp44_ = TRUE;
	} else {
		ValaMethod* _tmp50_ = NULL;
		ValaDataType* _tmp51_ = NULL;
		ValaDataType* _tmp52_ = NULL;
		ValaTypeSymbol* _tmp53_ = NULL;
		ValaTypeSymbol* _tmp54_ = NULL;
		gchar* _tmp55_ = NULL;
		gchar* _tmp56_ = NULL;
		_tmp50_ = method;
		_tmp51_ = vala_method_get_return_type (_tmp50_);
		_tmp52_ = _tmp51_;
		_tmp53_ = vala_data_type_get_data_type (_tmp52_);
		_tmp54_ = _tmp53_;
		_tmp55_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp54_);
		_tmp56_ = _tmp55_;
		_tmp44_ = g_strcmp0 (_tmp56_, "GLib.ValueArray") != 0;
		_g_free0 (_tmp56_);
	}
	if (_tmp44_) {
		ValaMethod* _tmp57_ = NULL;
		const gchar* _tmp58_ = NULL;
		const gchar* _tmp59_ = NULL;
		_tmp57_ = method;
		_tmp58_ = vala_symbol_get_name ((ValaSymbol*) _tmp57_);
		_tmp59_ = _tmp58_;
		g_warning ("vapisuiteinfo.vala:124: %s is named like a generator, but it does not " \
"return GLib.ValueArray", _tmp59_);
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


static gboolean valadate_runner_vapi_suite_info_is_test (ValadateRunnerVapiSuiteInfo* self, ValaMethod* method) {
	gboolean result = FALSE;
	ValaMethod* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	ValaMethod* _tmp4_ = NULL;
	ValaMemberBinding _tmp5_ = 0;
	ValaMemberBinding _tmp6_ = 0;
	ValaMethod* _tmp10_ = NULL;
	ValaDataType* _tmp11_ = NULL;
	ValaDataType* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	ValaMethod* _tmp19_ = NULL;
	gboolean _tmp20_ = FALSE;
	gboolean _tmp21_ = FALSE;
	ValaMethod* _tmp25_ = NULL;
	ValaList* _tmp26_ = NULL;
	ValaList* _tmp27_ = NULL;
	gint _tmp28_ = 0;
	gint _tmp29_ = 0;
	gboolean _tmp30_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (method != NULL, FALSE);
	_tmp0_ = method;
	_tmp1_ = vala_symbol_get_name ((ValaSymbol*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_str_has_prefix (_tmp2_, "test_");
	if (!_tmp3_) {
		result = FALSE;
		return result;
	}
	_tmp4_ = method;
	_tmp5_ = vala_method_get_binding (_tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_ != VALA_MEMBER_BINDING_INSTANCE) {
		ValaMethod* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		_tmp7_ = method;
		_tmp8_ = vala_symbol_get_name ((ValaSymbol*) _tmp7_);
		_tmp9_ = _tmp8_;
		g_warning ("vapisuiteinfo.vala:135: %s is named like a test, but it it not an inst" \
"ance method", _tmp9_);
		result = FALSE;
		return result;
	}
	_tmp10_ = method;
	_tmp11_ = vala_method_get_return_type (_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = vala_ccode_base_module_get_ccode_name ((ValaCodeNode*) _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strcmp0 (_tmp14_, "void") != 0;
	_g_free0 (_tmp14_);
	if (_tmp15_) {
		ValaMethod* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		const gchar* _tmp18_ = NULL;
		_tmp16_ = method;
		_tmp17_ = vala_symbol_get_name ((ValaSymbol*) _tmp16_);
		_tmp18_ = _tmp17_;
		g_warning ("vapisuiteinfo.vala:140: %s is named like a test, but it has non-void r" \
"eturn type", _tmp18_);
		result = FALSE;
		return result;
	}
	_tmp19_ = method;
	_tmp20_ = vala_code_node_get_tree_can_fail ((ValaCodeNode*) _tmp19_);
	_tmp21_ = _tmp20_;
	if (_tmp21_) {
		ValaMethod* _tmp22_ = NULL;
		const gchar* _tmp23_ = NULL;
		const gchar* _tmp24_ = NULL;
		_tmp22_ = method;
		_tmp23_ = vala_symbol_get_name ((ValaSymbol*) _tmp22_);
		_tmp24_ = _tmp23_;
		g_warning ("vapisuiteinfo.vala:145: %s is named like a test, but it throws error", _tmp24_);
		result = FALSE;
		return result;
	}
	_tmp25_ = method;
	_tmp26_ = vala_method_get_type_parameters (_tmp25_);
	_tmp27_ = _tmp26_;
	_tmp28_ = vala_collection_get_size ((ValaCollection*) _tmp27_);
	_tmp29_ = _tmp28_;
	_tmp30_ = _tmp29_ != 0;
	_vala_iterable_unref0 (_tmp27_);
	if (_tmp30_) {
		ValaMethod* _tmp31_ = NULL;
		const gchar* _tmp32_ = NULL;
		const gchar* _tmp33_ = NULL;
		ValaMethod* _tmp34_ = NULL;
		ValaList* _tmp35_ = NULL;
		ValaList* _tmp36_ = NULL;
		gint _tmp37_ = 0;
		gint _tmp38_ = 0;
		_tmp31_ = method;
		_tmp32_ = vala_symbol_get_name ((ValaSymbol*) _tmp31_);
		_tmp33_ = _tmp32_;
		_tmp34_ = method;
		_tmp35_ = vala_method_get_type_parameters (_tmp34_);
		_tmp36_ = _tmp35_;
		_tmp37_ = vala_collection_get_size ((ValaCollection*) _tmp36_);
		_tmp38_ = _tmp37_;
		g_warning ("vapisuiteinfo.vala:150: %s is named like a test, but is generic with %" \
"i type params", _tmp33_, _tmp38_);
		_vala_iterable_unref0 (_tmp36_);
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


static ValadateRunnerVapiSuiteInfoTestType valadate_runner_vapi_suite_info_test_type (ValadateRunnerVapiSuiteInfo* self, ValaMethod* method) {
	ValadateRunnerVapiSuiteInfoTestType result = 0;
	ValaMethod* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (method != NULL, 0);
	_tmp0_ = method;
	_tmp1_ = vala_method_get_coroutine (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		ValaMethod* _tmp3_ = NULL;
		ValaList* _tmp4_ = NULL;
		ValaList* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gboolean _tmp8_ = FALSE;
		gboolean _tmp9_ = FALSE;
		ValaMethod* _tmp10_ = NULL;
		ValaList* _tmp11_ = NULL;
		ValaList* _tmp12_ = NULL;
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		gboolean _tmp15_ = FALSE;
		ValaMethod* _tmp25_ = NULL;
		const gchar* _tmp26_ = NULL;
		const gchar* _tmp27_ = NULL;
		_tmp3_ = method;
		_tmp4_ = vala_method_get_parameters (_tmp3_);
		_tmp5_ = _tmp4_;
		_tmp6_ = vala_collection_get_size ((ValaCollection*) _tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = _tmp7_ == 0;
		_vala_iterable_unref0 (_tmp5_);
		if (_tmp8_) {
			result = VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_ASYNC;
			return result;
		}
		_tmp10_ = method;
		_tmp11_ = vala_method_get_parameters (_tmp10_);
		_tmp12_ = _tmp11_;
		_tmp13_ = vala_collection_get_size ((ValaCollection*) _tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = _tmp14_ == 1;
		_vala_iterable_unref0 (_tmp12_);
		if (_tmp15_) {
			ValaMethod* _tmp16_ = NULL;
			ValaList* _tmp17_ = NULL;
			ValaList* _tmp18_ = NULL;
			gpointer _tmp19_ = NULL;
			ValaParameter* _tmp20_ = NULL;
			ValaDataType* _tmp21_ = NULL;
			ValaDataType* _tmp22_ = NULL;
			gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
			_tmp16_ = method;
			_tmp17_ = vala_method_get_parameters (_tmp16_);
			_tmp18_ = _tmp17_;
			_tmp19_ = vala_list_get (_tmp18_, 0);
			_tmp20_ = (ValaParameter*) _tmp19_;
			_tmp21_ = vala_variable_get_variable_type ((ValaVariable*) _tmp20_);
			_tmp22_ = _tmp21_;
			_tmp23_ = vala_code_node_to_string ((ValaCodeNode*) _tmp22_);
			_tmp24_ = _tmp23_;
			_tmp9_ = g_strcmp0 (_tmp24_, "GLib.Cancellable") == 0;
			_g_free0 (_tmp24_);
			_vala_code_node_unref0 (_tmp20_);
			_vala_iterable_unref0 (_tmp18_);
		} else {
			_tmp9_ = FALSE;
		}
		if (_tmp9_) {
			result = VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_CANCELLABLE;
			return result;
		}
		_tmp25_ = method;
		_tmp26_ = vala_symbol_get_name ((ValaSymbol*) _tmp25_);
		_tmp27_ = _tmp26_;
		g_warning ("vapisuiteinfo.vala:173: %s is named like a test, but async test must h" \
"ave either no parameters or one parameter of type GLib.Cancellable", _tmp27_);
	} else {
		ValaMethod* _tmp28_ = NULL;
		ValaList* _tmp29_ = NULL;
		ValaList* _tmp30_ = NULL;
		gint _tmp31_ = 0;
		gint _tmp32_ = 0;
		gboolean _tmp33_ = FALSE;
		ValaMethod* _tmp34_ = NULL;
		const gchar* _tmp35_ = NULL;
		const gchar* _tmp36_ = NULL;
		ValaMethod* _tmp37_ = NULL;
		ValaList* _tmp38_ = NULL;
		ValaList* _tmp39_ = NULL;
		gint _tmp40_ = 0;
		gint _tmp41_ = 0;
		_tmp28_ = method;
		_tmp29_ = vala_method_get_parameters (_tmp28_);
		_tmp30_ = _tmp29_;
		_tmp31_ = vala_collection_get_size ((ValaCollection*) _tmp30_);
		_tmp32_ = _tmp31_;
		_tmp33_ = _tmp32_ == 0;
		_vala_iterable_unref0 (_tmp30_);
		if (_tmp33_) {
			result = VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_SYNC;
			return result;
		}
		_tmp34_ = method;
		_tmp35_ = vala_symbol_get_name ((ValaSymbol*) _tmp34_);
		_tmp36_ = _tmp35_;
		_tmp37_ = method;
		_tmp38_ = vala_method_get_parameters (_tmp37_);
		_tmp39_ = _tmp38_;
		_tmp40_ = vala_collection_get_size ((ValaCollection*) _tmp39_);
		_tmp41_ = _tmp40_;
		g_warning ("vapisuiteinfo.vala:179: %s is named like a test, but has %i parameters", _tmp36_, _tmp41_);
		_vala_iterable_unref0 (_tmp39_);
	}
	result = VALADATE_RUNNER_VAPI_SUITE_INFO_TEST_TYPE_NONE;
	return result;
}


static GType valadate_runner_vapi_suite_info_get_g_type (ValaClass* cl, GError** error) {
	GType result = 0UL;
	void* _tmp0_ = NULL;
	ValaClass* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	void* _tmp6_ = NULL;
	void* _tmp7_ = NULL;
	ValadateRunnerGetType get_type = NULL;
	GType type = 0UL;
	ValadateRunnerGetType _tmp8_ = NULL;
	GType _tmp9_ = 0UL;
	gboolean _tmp10_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (cl != NULL, 0UL);
	valadate_runner_vapi_suite_info_load_modules (&_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
			g_propagate_error (error, _inner_error_);
			return 0UL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0UL;
		}
	}
	_tmp1_ = cl;
	_tmp2_ = vala_ccode_base_module_get_ccode_lower_case_prefix ((ValaSymbol*) _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat (_tmp3_, "get_type", NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = valadate_runner_vapi_suite_info_load_symbol (_tmp5_, &_inner_error_);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	_tmp0_ = _tmp7_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
			g_propagate_error (error, _inner_error_);
			return 0UL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0UL;
		}
	}
	get_type = (ValadateRunnerGetType) _tmp0_;
	_tmp8_ = get_type;
	_tmp9_ = _tmp8_ ();
	type = _tmp9_;
	_tmp10_ = valadate_runner_verbose;
	if (_tmp10_) {
		FILE* _tmp11_ = NULL;
		GType _tmp12_ = 0UL;
		const gchar* _tmp13_ = NULL;
		ValaClass* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		gchar* _tmp16_ = NULL;
		_tmp11_ = stdout;
		_tmp12_ = type;
		_tmp13_ = g_type_name (_tmp12_);
		_tmp14_ = cl;
		_tmp15_ = vala_symbol_get_full_name ((ValaSymbol*) _tmp14_);
		_tmp16_ = _tmp15_;
		fprintf (_tmp11_, "        Loaded type %s for class %s\n", _tmp13_, _tmp16_);
		_g_free0 (_tmp16_);
	}
	result = type;
	return result;
}


static void _vala_array_add7 (GModule*** array, int* length, int* size, GModule* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GModule*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void valadate_runner_vapi_suite_info_load_modules (GError** error) {
	gboolean _tmp0_ = FALSE;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	_tmp0_ = valadate_runner_vapi_suite_info_modules_loaded;
	if (_tmp0_) {
		return;
	}
	_tmp1_ = valadate_runner_libs;
	_tmp1__length1 = _vala_array_length (valadate_runner_libs);
	{
		gchar** name_collection = NULL;
		gint name_collection_length1 = 0;
		gint _name_collection_size_ = 0;
		gint name_it = 0;
		name_collection = _tmp1_;
		name_collection_length1 = _tmp1__length1;
		for (name_it = 0; name_it < _tmp1__length1; name_it = name_it + 1) {
			const gchar* name = NULL;
			name = name_collection[name_it];
			{
				GModule* mod = NULL;
				const gchar* _tmp2_ = NULL;
				GModule* _tmp3_ = NULL;
				GModule* _tmp4_ = NULL;
				_tmp2_ = name;
				_tmp3_ = valadate_runner_vapi_suite_info_load_module (_tmp2_);
				mod = _tmp3_;
				_tmp4_ = mod;
				if (_tmp4_ != NULL) {
					GModule** _tmp5_ = NULL;
					gint _tmp5__length1 = 0;
					GModule* _tmp6_ = NULL;
					_tmp5_ = valadate_runner_vapi_suite_info_modules;
					_tmp5__length1 = valadate_runner_vapi_suite_info_modules_length1;
					_tmp6_ = mod;
					mod = NULL;
					_vala_array_add7 (&valadate_runner_vapi_suite_info_modules, &valadate_runner_vapi_suite_info_modules_length1, &_valadate_runner_vapi_suite_info_modules_size_, _tmp6_);
				}
				_g_module_close0 (mod);
			}
		}
	}
	valadate_runner_vapi_suite_info_modules_loaded = TRUE;
}


static GModule* valadate_runner_vapi_suite_info_load_module (const gchar* name) {
	GModule* result = NULL;
	GModule* mod = NULL;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	GModule* _tmp10_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	mod = NULL;
	_tmp0_ = valadate_runner_path;
	_tmp0__length1 = _vala_array_length (valadate_runner_path);
	{
		gchar** dir_collection = NULL;
		gint dir_collection_length1 = 0;
		gint _dir_collection_size_ = 0;
		gint dir_it = 0;
		dir_collection = _tmp0_;
		dir_collection_length1 = _tmp0__length1;
		for (dir_it = 0; dir_it < _tmp0__length1; dir_it = dir_it + 1) {
			const gchar* dir = NULL;
			dir = dir_collection[dir_it];
			{
				const gchar* _tmp1_ = NULL;
				const gchar* _tmp2_ = NULL;
				gchar* _tmp3_ = NULL;
				gchar* _tmp4_ = NULL;
				GModule* _tmp5_ = NULL;
				GModule* _tmp6_ = NULL;
				_tmp1_ = dir;
				_tmp2_ = name;
				_tmp3_ = g_module_build_path (_tmp1_, _tmp2_);
				_tmp4_ = _tmp3_;
				_tmp5_ = g_module_open (_tmp4_, G_MODULE_BIND_LAZY | G_MODULE_BIND_LOCAL);
				_g_module_close0 (mod);
				mod = _tmp5_;
				_g_free0 (_tmp4_);
				_tmp6_ = mod;
				if (_tmp6_ != NULL) {
					result = mod;
					return result;
				}
			}
		}
	}
	_tmp7_ = name;
	_tmp8_ = g_module_build_path (NULL, _tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_module_open (_tmp9_, G_MODULE_BIND_LAZY | G_MODULE_BIND_LOCAL);
	_g_module_close0 (mod);
	mod = _tmp10_;
	_g_free0 (_tmp9_);
	result = mod;
	return result;
}


static void* valadate_runner_vapi_suite_info_load_symbol (const gchar* name, GError** error) {
	void* result = NULL;
	void* sym = NULL;
	GModule** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	const gchar* _tmp6_ = NULL;
	GError* _tmp7_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	sym = NULL;
	_tmp0_ = valadate_runner_vapi_suite_info_modules;
	_tmp0__length1 = valadate_runner_vapi_suite_info_modules_length1;
	{
		GModule** mod_collection = NULL;
		gint mod_collection_length1 = 0;
		gint _mod_collection_size_ = 0;
		gint mod_it = 0;
		mod_collection = _tmp0_;
		mod_collection_length1 = _tmp0__length1;
		for (mod_it = 0; mod_it < _tmp0__length1; mod_it = mod_it + 1) {
			GModule* mod = NULL;
			mod = mod_collection[mod_it];
			{
				GModule* _tmp1_ = NULL;
				const gchar* _tmp2_ = NULL;
				void* _tmp3_ = NULL;
				gboolean _tmp4_ = FALSE;
				_tmp1_ = mod;
				_tmp2_ = name;
				_tmp4_ = g_module_symbol (_tmp1_, _tmp2_, &_tmp3_);
				sym = _tmp3_;
				if (_tmp4_) {
					void* _tmp5_ = NULL;
					_tmp5_ = sym;
					result = _tmp5_;
					return result;
				}
			}
		}
	}
	_tmp6_ = name;
	_tmp7_ = g_error_new (VALADATE_RUNNER_RUNNER_ERROR, VALADATE_RUNNER_RUNNER_ERROR_TYPE_NOT_LOADED, "Symbol %s not found.\n", _tmp6_);
	_inner_error_ = _tmp7_;
	if (_inner_error_->domain == VALADATE_RUNNER_RUNNER_ERROR) {
		g_propagate_error (error, _inner_error_);
		return NULL;
	} else {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static void valadate_runner_vapi_suite_info_class_init (ValadateRunnerVapiSuiteInfoClass * klass) {
	valadate_runner_vapi_suite_info_parent_class = g_type_class_peek_parent (klass);
	((ValadateRunnerSuiteInfoClass *) klass)->finalize = valadate_runner_vapi_suite_info_finalize;
	g_type_class_add_private (klass, sizeof (ValadateRunnerVapiSuiteInfoPrivate));
}


static void valadate_runner_vapi_suite_info_instance_init (ValadateRunnerVapiSuiteInfo * self) {
	self->priv = VALADATE_RUNNER_VAPI_SUITE_INFO_GET_PRIVATE (self);
}


static void valadate_runner_vapi_suite_info_finalize (ValadateRunnerSuiteInfo* obj) {
	ValadateRunnerVapiSuiteInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALADATE_RUNNER_TYPE_VAPI_SUITE_INFO, ValadateRunnerVapiSuiteInfo);
	_vala_code_node_unref0 (self->priv->cl);
	VALADATE_RUNNER_SUITE_INFO_CLASS (valadate_runner_vapi_suite_info_parent_class)->finalize (obj);
}


GType valadate_runner_vapi_suite_info_get_type (void) {
	static volatile gsize valadate_runner_vapi_suite_info_type_id__volatile = 0;
	if (g_once_init_enter (&valadate_runner_vapi_suite_info_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValadateRunnerVapiSuiteInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) valadate_runner_vapi_suite_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValadateRunnerVapiSuiteInfo), 0, (GInstanceInitFunc) valadate_runner_vapi_suite_info_instance_init, NULL };
		GType valadate_runner_vapi_suite_info_type_id;
		valadate_runner_vapi_suite_info_type_id = g_type_register_static (VALADATE_RUNNER_TYPE_SUITE_INFO, "ValadateRunnerVapiSuiteInfo", &g_define_type_info, 0);
		g_once_init_leave (&valadate_runner_vapi_suite_info_type_id__volatile, valadate_runner_vapi_suite_info_type_id);
	}
	return valadate_runner_vapi_suite_info_type_id__volatile;
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



