def build(bld):
    prg = bld.new_task_gen(
            features='cc cprogram',
            target='valadate',
            vapi_dirs='../vapi',
            includes='../vapi',
            packages='glib-2.0 vala-1.0 gmodule-2.0 gobject-introspection-1.0 posix',
            uselib='glib-2.0 vala-1.0 gmodule-2.0 gobject-introspection-1.0',
            uselib_local='valadate-0.0',
            ccflags=['-ggdb'])
    prg.find_sources_in_dirs('.')

# vim: set ft=python:
