def build(bld):
    bld.program(source=bld.path.ant_glob('*.vala'),
                target='valadate',
                vapi_dirs='../vapi',
                includes='../vapi',
                packages='glib-2.0 gobject-2.0 libvala-0.20 gmodule-2.0 gobject-introspection-1.0 posix',
                uselib='glib-2.0 gobject-2.0 libvala-0.20 gmodule-2.0 gobject-introspection-1.0',
                use='valadate-%(API_VER)s' % bld.env,
                cflags=['-ggdb'])

